import { ChangeDetectionStrategy,Component,computed,inject,signal } from '@angular/core';import { Router,RouterLink } from '@angular/router';import { VOCABULARY_N5 } from '../../data/vocabulary-n5.generated';import { KANJI_N5 } from '../../data/kanji-n5.generated';import { ALL_KANA } from '../../data/kana';import { VocabularyEntry,VocabularyQuestionType,VocabularyStudyCategory,VOCABULARY_CATEGORIES,VOCABULARY_QUESTION_TYPES } from '../../core/models/vocabulary.model';import { TranslationService } from '../../core/services/translation.service';import { isReadingQuestionEligible } from '../../core/services/vocabulary-selection';import { VocabularyProgressService } from '../../core/services/vocabulary-progress.service';import { FuriganaText } from '../../shared/components/furigana-text/furigana-text';
@Component({selector:'app-vocabulary-all-page',imports:[RouterLink,FuriganaText],templateUrl:'./vocabulary-all.page.html',styleUrl:'./vocabulary-all.page.scss',changeDetection:ChangeDetectionStrategy.OnPush,host:{'(document:keydown.escape)':'closeOverlay()'}})export class VocabularyAllPage{readonly i18n=inject(TranslationService);readonly progress=inject(VocabularyProgressService);readonly searching=signal(false);readonly query=signal('');readonly grouped=signal(false);readonly selected=signal<VocabularyEntry|null>(null);readonly categories=VOCABULARY_CATEGORIES;private readonly router=inject(Router);readonly filtered=computed(()=>VOCABULARY_N5.filter(entry=>vocabularyEntryMatchesQuery(entry,this.query())));back(){void this.router.navigateByUrl('/vocabulary')}setQuery(e:Event){this.query.set((e.target as HTMLInputElement).value)}closeOverlay(){if(this.selected())this.selected.set(null);else if(this.searching()){this.searching.set(false);this.query.set('')}}meaning(e:VocabularyEntry){return e.quizMeaning[this.i18n.language()]}entries(c:VocabularyStudyCategory){return this.filtered().filter(e=>e.studyCategory===c)}types(e:VocabularyEntry){return VOCABULARY_QUESTION_TYPES.filter(t=>!t.includes('reading')||isReadingQuestionEligible(e))}statusKey(e:VocabularyEntry,t:VocabularyQuestionType){const p=this.progress.get(`vocab:${e.id}:${t}`);return!p?'home.new':p.fsrs.state==='review'?'home.memorized':'home.pending'}variants(e:VocabularyEntry){return e.writtenForms.filter(form=>form!==e.primaryWrittenForm)}readingVariants(e:VocabularyEntry){return e.readings.filter(reading=>reading!==e.primaryReading)}knownKanji(e:VocabularyEntry){return e.kanjiCharacters.filter(c=>KANJI_N5.some(k=>k.character===c))}}

const ROMAJI=new Map(ALL_KANA.map(k=>[k.character,k.romaji]));export function romanizeVocabularyReading(reading:string){let result='';for(let i=0;i<reading.length;){const pair=reading.slice(i,i+2),mapped=ROMAJI.get(pair)??ROMAJI.get(reading[i]);if(reading[i]==='っ'||reading[i]==='ッ'){const next=ROMAJI.get(reading.slice(i+1,i+3))??ROMAJI.get(reading[i+1])??'';result+=next[0]??'';i++;continue}result+=mapped??reading[i];i+=ROMAJI.has(pair)?2:1}return result}






export function vocabularyEntryMatchesQuery(entry:VocabularyEntry,query:string){const normalized=normalizeSearch(query);return !normalized||[entry.primaryWrittenForm,...entry.writtenForms,entry.primaryReading,...entry.readings,...entry.readings.map(reading=>romanizeVocabularyReading(reading)),'N5',...Object.values(entry.meanings).flat(),...Object.values(entry.quizMeaning),...entry.partOfSpeech,...entry.examples.flatMap(example=>[example.romaji??'',example.japanese,example.reading,...Object.values(example.translations)])].some(value=>normalizeSearch(value).includes(normalized))}
function normalizeSearch(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}

