import { TestBed } from '@angular/core/testing';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { DictionaryTerm } from '../models/dictionary.model';
import { DictionaryRepository } from './dictionary.repository';
import { JapaneseLookupService, japaneseCandidates, japaneseCaretSpans } from './japanese-lookup.service';
function term(expression:string,rules='',score=0,id=expression):DictionaryTerm{return {id,dictionaryId:'test',expression,reading:expression==='食べる'?'たべる':expression,glossaries:['meaning'],definitionTags:'',rules,score,sequence:1,termTags:''};}
describe('Assisted Japanese lookup',()=>{
  let rows:DictionaryTerm[],service:JapaneseLookupService;
  beforeEach(()=>{rows=[];TestBed.configureTestingModule({providers:[{provide:DictionaryRepository,useValue:{cleanup:async()=>{},ready:async()=>({dictionaryId:'test'}),find:vi.fn(async(_:string,query:string,field:'expression'|'reading')=>rows.filter(row=>row[field]===query))}}]});service=TestBed.inject(JapaneseLookupService);});
  it.each(['selection','caret'] as const)('rejects high-score noun 汁 as a します deinflection in %s mode',async mode=>{rows=[{...term('汁','',99999999),reading:'しる',definitionTags:'n n-suf'},{...term('する','vs',1),reading:'する'}];const result=mode==='selection'?await service.lookupSelection('します'):await service.lookupAt('します',1);expect(result.principal?.expression).toBe('する');expect(result.terms.map(row=>row.expression)).not.toContain('汁');expect((await service.lookupAt('汁',0)).principal?.expression).toBe('汁');});
  it.each([0,1,2,3,4,5])('keeps full させたかった at character %s inside a real OCR line',async position=>{rows=[term('する','vs',20),term('さす','v5s',10),{...term('鷹','',99999),reading:'たか'},term('させ'),term('た')];const result=await service.lookupAt('させたかったんですけど',position);expect(result.surface).toBe('させたかった');expect(result.terms.map(row=>row.expression).sort()).toEqual(['さす','する']);});
  it('bounds containing-caret spans by codepoints and deduplicates them',()=>{const text='あ'.repeat(40)+'𠮷'+'い'.repeat(40),offset=40;const spans=japaneseCaretSpans(text,offset);expect(spans.length).toBeLessThanOrEqual(136);expect(spans.every(span=>span.start<=offset&&span.end>offset&&Array.from(span.text).length<=16)).toBe(true);expect(new Set(spans.map(span=>span.start+':'+span.end)).size).toBe(spans.length);});
  it('rejects a Segmenter fragment crossing the end of a validated inflected surface',async()=>{rows=[term('する','vs',20),term('さす','v5',10),term('たん','',999999)];const original=Intl.Segmenter;Object.defineProperty(Intl,'Segmenter',{configurable:true,value:class {segment(){return [{segment:'させ',index:0},{segment:'たかっ',index:2},{segment:'たん',index:5},{segment:'です',index:7},{segment:'けど',index:9}];}}});try{expect((await service.lookupAt('させたかったんですけど',5)).surface).toBe('させたかった');}finally{Object.defineProperty(Intl,'Segmenter',{configurable:true,value:original});}});
  it.each([['負けぬ','負ける','v1'],['行かぬ','行く','v5k-s'],['書かぬ','書く','v5k'],['読まぬ','読む','v5m'],['せぬ','する','vs-i'],['来ぬ','来る','vk'],['こぬ','来る','vk']])('resolves %s to %s with POS validation',async(surface,base,rules)=>{rows=[{...term(base,rules),reading:base==='来る'?'くる':base}];expect(await service.lookupAt(surface,surface.length-1)).toMatchObject({surface,principal:{expression:base},reasons:['negative-nu']});});
  it('keeps exact 死ぬ ahead of suffix transformations',async()=>{rows=[term('死ぬ','v5n'),term('死る','v1',99999)];expect(await service.lookupAt('死ぬ',1)).toMatchObject({surface:'死ぬ',principal:{expression:'死ぬ'},reasons:[]});});
  it.each([['ありがとう','有難う','ありがとう',''],['そういう','そう言う','そういう',''],['髪型','髪型','かみがた',''],['百合','百合','ゆり',''],['お願い','お願い','おねがい',''],['も','も','も',''],['ございました','ございます','ございます','v5r'],['悪かった','悪い','わるい','adj-i'],['読んでる','読む','よむ','v5m']])('preserves real dictionary behavior for %s',async(surface,expression,reading,rules)=>{rows=[{...term(expression,rules),reading}];for(const offset of [0,Math.floor(surface.length/2),surface.length-1])expect((await service.lookupAt(surface,offset)).principal?.expression).toBe(expression);});
  it.each(['selection','caret'] as const)('preserves both いった interpretations in %s mode regardless of row order',async mode=>{for(const reverse of [false,true]){rows=[{...term('行く','v5'),reading:'いく'},{...term('言う','v5'),reading:'いう'}];if(reverse)rows.reverse();const result=mode==='selection'?await service.lookupSelection('いった'):await service.lookupAt('いった',1);expect(result.terms.map(row=>row.expression).sort()).toEqual(['行く','言う']);expect(result.alternatives).toHaveLength(1);}});
  it.each(['selection','caret'] as const)('preserves 来る and 着る for きた in %s mode',async mode=>{rows=[{...term('来る','vk'),reading:'くる'},{...term('着る','v1'),reading:'きる'}];const result=mode==='selection'?await service.lookupSelection('きた'):await service.lookupAt('きた',1);expect(result.terms.map(row=>row.expression).sort()).toEqual(['来る','着る']);expect(result.alternatives).toHaveLength(1);});
  it.each(['きて','きました','こない','こなかった'])('validates the kana irregular 来る surface %s',async surface=>{rows=[{...term('来る','vk'),reading:'くる'}];expect((await service.lookupSelection(surface)).principal?.expression).toBe('来る');});
  it('prefers an exact expression over deinflection',async()=>{rows=[term('食べる','v1'),term('食べなかった')];expect((await service.lookup('食べなかった',0)).principal?.expression).toBe('食べなかった');});
  it('keeps the irregular 行った → 行く match ahead of generic 行う in both modes',async()=>{rows=[term('行う','v5'),term('行く','v5')];for(const offset of [0,1,2])expect((await service.lookupAt('行った',offset)).baseForm).toBe('行く');expect((await service.lookupSelection('行った')).baseForm).toBe('行く');});
  it('returns surface, base, reasons and reading for conjugated lookup',async()=>{rows=[term('食べる','v1')];expect(await service.lookup('食べなかった',1)).toMatchObject({surface:'食べなかった',baseForm:'食べる',surfaceReading:'たべなかった',reasons:['negative-past']});});
  it('looks up dictionary readings',async()=>{rows=[{...term('学校'),reading:'がっこう'}];expect((await service.lookup('がっこう',0)).principal?.expression).toBe('学校');});
  it('does not let fragments hide the complete conjugated verb at any caret position',async()=>{rows=[term('食べる','v1'),term('た'),term('食'),term('なか'),term('っ')];for(const offset of [0,1,2,3,4,5])expect((await service.lookup('食べなかった',offset)).baseForm).toBe('食べる');});
  it('ranks by dictionary score and removes redundant alternatives',async()=>{rows=[term('学校','',1,'low'),term('学校','',10,'high'),{...term('学校','',5,'other'),glossaries:['alternative']}];const result=await service.lookup('学校',0);expect(result.principal?.id).toBe('high');expect(result.terms.length).toBe(2);expect(result.alternatives?.length).toBe(1);});
  it('rejects incompatible POS',async()=>{rows=[term('食べる','n')];expect((await service.lookup('食べなかった',0)).terms).toEqual([]);});
  it('handles invalid caret, punctuation and non-Japanese safely',async()=>{for(const [text,offset] of [['hello',0],['学校',-1],['学校',2],['。学校',0]] as const)expect((await service.lookup(text,offset)).terms).toEqual([]);});
  it('resolves both UTF-16 positions of a supplementary kanji',async()=>{rows=[term('𠮷田')];expect(japaneseCandidates('𠮷田',1)).toContain('𠮷田');expect((await service.lookup('𠮷田',1)).principal?.expression).toBe('𠮷田');});
  it('works without Intl.Segmenter',async()=>{const previous=Intl.Segmenter;Object.defineProperty(Intl,'Segmenter',{configurable:true,value:undefined});try{rows=[term('食べる','v1')];expect((await service.lookup('食べなかった',0)).baseForm).toBe('食べる');}finally{Object.defineProperty(Intl,'Segmenter',{configurable:true,value:previous});}});

  it.each(['ひとり','ここ','そこ','これ','それ','あなた','ありがとう'])('prefers valid kana word %s at every caret position',async(word)=>{const expression=word==='ひとり'?'一人':word;rows=[{...term(expression),reading:word},...Array.from(word).map(char=>term(char,'',9999999))];for(let offset=0;offset<word.length;offset++)expect((await service.lookupAt(word,offset)).principal?.expression).toBe(expression);});
  it('postpones a single-kana Segmenter result inside a sentence',async()=>{rows=[{...term('一人'),reading:'ひとり'},term('ひ','',9999999),term('と','',9999999),term('り','',9999999)];const original=Intl.Segmenter;Object.defineProperty(Intl,'Segmenter',{configurable:true,value:class {segment(text:string){return Array.from(text).map((segment,index)=>({segment,index}));}}});try{for(const offset of [3,4,5])expect((await service.lookupAt('今日はひとりで行く',offset)).principal?.expression).toBe('一人');}finally{Object.defineProperty(Intl,'Segmenter',{configurable:true,value:original});}});
  it('allows an intentional single kana when no multi-kana entry exists',async()=>{rows=[term('ひ')];expect((await service.lookupAt('ひ',0)).principal?.expression).toBe('ひ');expect((await service.lookupAt('ひとり',0)).principal?.expression).toBe('ひ');});
  it('does not assume an unknown kana sequence is one word',async()=>{rows=[];expect((await service.lookupAt('ほげほげ',2)).terms).toEqual([]);});
  it('preserves explicit selection and separates its matched reading query',async()=>{rows=[{...term('一人'),reading:'ひとり'},term('ひ')];expect(await service.lookupSelection(' ひとり\n')).toMatchObject({mode:'selection',requestedText:'ひとり',selectedText:'ひとり',matchedQuery:'ひとり',principal:{expression:'一人'}});});
  it('never substitutes a selected phrase with an internal dictionary word',async()=>{rows=[{...term('一人'),reading:'ひとり'},term('行く','v5')];expect(await service.lookupSelection('ひとりで行く')).toMatchObject({requestedText:'ひとりで行く',surface:'ひとりで行く',query:'ひとりで行く',terms:[]});});
  it('enriches complete conjugated selection without changing the selected text',async()=>{rows=[term('食べる','v1')];expect(await service.lookupSelection('食べなかった')).toMatchObject({selectedText:'食べなかった',requestedText:'食べなかった',matchedQuery:'食べる',baseForm:'食べる'});});
});
