import { WeaknessService } from './weakness.service';
import { KANJI_QUESTION_TYPES } from '../models/kanji.model';
import { computed,inject,Injectable,signal } from '@angular/core';
import { KANJI_N5 } from '../../data/kanji-n5.generated';
import { AppLanguage } from '../models/country.model';
import { KanjiStudyUnit } from '../models/kanji.model';
import { KanjiLearningSession,KanjiSessionFeedback } from '../models/kanji-session.model';
import { LearningMode,SessionItem } from '../models/learning-session.model';
import { MedalState } from '../models/medal.model';import { StudyRating } from '../models/progress.model';
import { buildKanjiOptions,kanjiMeaning } from './kanji-options';import { KanjiProgressService } from './kanji-progress.service';import { KanjiMedalService } from './kanji-medal.service';import { SessionHistoryService } from './session-history.service';import { DailyLearningService } from './daily-learning.service';
interface State{readonly practice:boolean;readonly session:KanjiLearningSession;readonly queue:readonly string[];readonly queueIndex:number;readonly revealed:boolean;readonly feedback:KanjiSessionFeedback|null}
export const KANJI_MAX_APPEARANCES=4;const AGAIN_GAP=2,HARD_GAP=4;
@Injectable({providedIn:'root'}) export class KanjiSessionService{private readonly weaknesses=inject(WeaknessService);private readonly progress=inject(KanjiProgressService);private readonly history=inject(SessionHistoryService);private readonly medals=inject(KanjiMedalService);private readonly dailyLearning=inject(DailyLearningService);private readonly state=signal<State|null>(null);private readonly medalState=signal<readonly MedalState[]>([]);readonly isPractice=computed(()=>this.state()?.practice??false);readonly session=computed(()=>this.state()?.session??null);readonly newlyUnlockedMedals=this.medalState.asReadonly();readonly currentUnit=computed(()=>{const s=this.state();if(!s||s.session.completedAt)return null;return s.session.units.find(u=>u.key===s.queue[s.queueIndex])??null});readonly currentKanji=computed(()=>{const u=this.currentUnit();return u?KANJI_N5.find(k=>k.id===u.kanjiId)??null:null});readonly currentItem=computed(()=>{const u=this.currentUnit();return u?this.session()?.items.find(i=>i.studyKey===u.key)??null:null});readonly feedback=computed(()=>this.state()?.feedback??null);readonly revealed=computed(()=>this.state()?.revealed??false);readonly completed=computed(()=>Boolean(this.session()?.completedAt));readonly resolvedCount=computed(()=>this.session()?.items.filter(i=>i.resolved).length??0);readonly progressPercent=computed(()=>this.session()?.sessionSize?this.resolvedCount()/this.session()!.sessionSize*100:0);readonly firstTrySuccessCount=computed(()=>this.session()?.items.filter(i=>i.initialRating==='good').length??0);readonly firstTryPercentage=computed(()=>this.session()?.sessionSize?Math.round(this.firstTrySuccessCount()/this.session()!.sessionSize*100):0);
start(mode:LearningMode){if(this.dailyLearning.isCompletedToday('kanji'))return false;const units=this.progress.buildRound();return this.initialize(units,mode,false)}startPractice(units:readonly KanjiStudyUnit[],mode:LearningMode='quick-practice'){const valid=units.filter(u=>KANJI_N5.some(e=>e.id===u.kanjiId&&e.enabled)&&KANJI_QUESTION_TYPES.includes(u.questionType));const unique=[...new Map(valid.map(u=>[u.kanjiId+':'+u.questionType,{...u,key:'kanji:'+u.kanjiId+':'+u.questionType}])).values()];return this.initialize(unique,mode,true)}private initialize(units:readonly KanjiStudyUnit[],mode:LearningMode,practice:boolean){if(!units.length)return false;const session:KanjiLearningSession={id:globalThis.crypto?.randomUUID?.()??`kanji-session-${Date.now()}`,startedAt:new Date().toISOString(),completedAt:null,mode,sessionSize:units.length,units,items:units.map(u=>this.newItem(u)),attempts:0};this.medalState.set([]);this.state.set({session,practice,queue:units.map(u=>u.key),queueIndex:0,revealed:false,feedback:null});this.markAppearance();return true}options(language:AppLanguage){const u=this.currentUnit(),s=this.session();return u&&s?buildKanjiOptions(u,KANJI_N5,language,`${s.id}:${u.key}`):[]}meaning(language:AppLanguage){const k=this.currentKanji();return k?kanjiMeaning(k,language):''}answerQuick(id:string){const s=this.state(),u=this.currentUnit();if(!s||!u||s.feedback)return;const correct=id===u.kanjiId;this.register(correct?'good':'again',correct);this.patch({feedback:{correct,selectedId:id,correctId:u.kanjiId}})}continueQuick(){const s=this.state();if(!s?.feedback)return;if(!s.feedback.correct&&!this.currentItem()?.resolved)this.enqueue('again');this.advance()}reveal(){if(this.state())this.patch({revealed:true})}rate(rating:StudyRating){if(!this.state()?.revealed)return;this.register(rating,rating==='good');if(rating!=='good'&&!this.currentItem()?.resolved)this.enqueue(rating);this.advance()}restart(mode=this.session()?.mode??'quick-practice'){return this.isPractice()?this.startPractice(this.session()!.units,mode):this.start(mode)}clear(){this.state.set(null);this.medalState.set([])}dismissNextMedal(){this.medalState.update(v=>v.slice(1))}
private register(rating:StudyRating,resolved:boolean){const s=this.state(),u=this.currentUnit();if(!s||!u)return;this.weaknesses.recordLearn('kanji',u.kanjiId,u.questionType,rating);const items=s.session.items.map(item=>{if(item.studyKey!==u.key)return item;const first=item.initialRating===null;if(!s.practice&&first)this.progress.recordReview(u,rating,rating==='good',s.session.id);else if(!s.practice)this.progress.recordPracticeAttempt(u,rating==='good');const limit=!resolved&&item.appearances>=KANJI_MAX_APPEARANCES;return{...item,attempts:item.attempts+1,initialRating:item.initialRating??rating,resolved:item.resolved||resolved||limit,needsPractice:item.needsPractice||rating!=='good'}});this.state.set({...s,session:{...s.session,items,attempts:s.session.attempts+1}})}
private enqueue(rating:Exclude<StudyRating,'good'>){const s=this.state(),u=this.currentUnit();if(!s||!u)return;const gap=rating==='again'?AGAIN_GAP:HARD_GAP,at=Math.min(s.queueIndex+1+gap,s.queue.length);this.patch({queue:[...s.queue.slice(0,at),u.key,...s.queue.slice(at)]})}private advance(){const s=this.state();if(!s)return;const next=s.queueIndex+1;if(next>=s.queue.length){const now=new Date();if(!s.practice)this.dailyLearning.refresh(now);const session={...s.session,completedAt:now.toISOString()};this.state.set({...s,session,feedback:null,revealed:false});if(s.practice)return;this.history.record({module:'kanji',sessionId:session.id,completedAt:session.completedAt,mode:session.mode,exercisesCompleted:session.sessionSize,firstTrySuccesses:session.items.filter(i=>i.initialRating==='good').length,attempts:session.attempts,needsPracticeCount:session.items.filter(i=>i.needsPractice).length,durationSeconds:Math.max(0,Math.round((now.getTime()-new Date(session.startedAt).getTime())/1000)),questionTypes:[...new Set(session.units.map(u=>u.questionType))],kanjiIds:[...new Set(session.units.map(u=>u.kanjiId))]});this.medalState.set(this.medals.evaluateUnlocks(now));return}this.state.set({...s,queueIndex:next,feedback:null,revealed:false});this.markAppearance()}private markAppearance(){const s=this.state(),u=this.currentUnit();if(!s||!u)return;this.state.set({...s,session:{...s.session,items:s.session.items.map(i=>i.studyKey===u.key?{...i,appearances:i.appearances+1}:i)}})}private patch(p:Partial<State>){this.state.update(s=>s?{...s,...p}:null)}private newItem(u:KanjiStudyUnit):SessionItem{return{studyKey:u.key,attempts:0,appearances:0,initialRating:null,resolved:false,needsPractice:false}}}

