import { STUDY_MONOTONIC_NOW } from './study-clock';
import { TestBed } from '@angular/core/testing';import { KanjiStudyUnit } from '../models/kanji.model';import { KanjiProgressService } from './kanji-progress.service';import { KANJI_MAX_APPEARANCES,KanjiSessionService } from './kanji-session.service';import { KanjiMedalService } from './kanji-medal.service';import { SessionHistoryService } from './session-history.service';import { DailyLearningService } from './daily-learning.service';
describe('KanjiSessionService',()=>{let monotonic=0;let service:KanjiSessionService;let round:KanjiStudyUnit[];let progress:{buildRound:ReturnType<typeof vi.fn>;recordReview:ReturnType<typeof vi.fn>;recordPracticeAttempt:ReturnType<typeof vi.fn>};let history:{record:ReturnType<typeof vi.fn>};beforeEach(()=>{monotonic=0;round=[{key:'kanji:日:kanji-to-meaning',kanjiId:'日',questionType:'kanji-to-meaning'}];progress={buildRound:vi.fn(()=>round),recordReview:vi.fn(),recordPracticeAttempt:vi.fn()};history={record:vi.fn()};TestBed.configureTestingModule({providers:[{provide:STUDY_MONOTONIC_NOW,useValue:()=>monotonic},KanjiSessionService,{provide:KanjiProgressService,useValue:progress},{provide:SessionHistoryService,useValue:history},{provide:KanjiMedalService,useValue:{evaluateUnlocks:vi.fn(()=>[])}},{provide:DailyLearningService,useValue:{isCompletedToday:vi.fn(()=>false),refresh:vi.fn()}}]});service=TestBed.inject(KanjiSessionService)});afterEach(()=>TestBed.resetTestingModule());
it('records Good for a correct first quick answer',()=>{service.start('quick-practice');service.answerQuick('日');expect(progress.recordReview).toHaveBeenCalledWith(round[0],'good',true,expect.any(String))});
it('records one FSRS review across later intra-round training',()=>{service.start('self-assessment');service.reveal();service.rate('again');service.reveal();service.rate('hard');service.reveal();service.rate('good');expect(progress.recordReview).toHaveBeenCalledTimes(1);expect(progress.recordReview.mock.calls[0][1]).toBe('again');expect(progress.recordPracticeAttempt).toHaveBeenCalledTimes(2)});
it('places Again sooner than Hard when intervening units exist',()=>{round=Array.from({length:8},(_,i)=>({key:`kanji:${i}:kanji-to-meaning`,kanjiId:String(i),questionType:'kanji-to-meaning'}));service.start('self-assessment');service.reveal();service.rate('again');expect(service.currentUnit()?.kanjiId).toBe('1');service.reveal();service.rate('good');service.reveal();service.rate('good');expect(service.currentUnit()?.kanjiId).toBe('0');service.clear();service.start('self-assessment');service.reveal();service.rate('hard');for(let i=1;i<=4;i++){expect(service.currentUnit()?.kanjiId).toBe(String(i));service.reveal();service.rate('good')}expect(service.currentUnit()?.kanjiId).toBe('0')});
it('stops at four appearances and marks unresolved study for practice',()=>{service.start('self-assessment');for(let i=0;i<KANJI_MAX_APPEARANCES;i++){service.reveal();service.rate('again')}const item=service.session()!.items[0];expect(item.appearances).toBe(4);expect(item.needsPractice).toBe(true);expect(item.resolved).toBe(true);expect(service.completed()).toBe(true)});
it('calculates results from first responses and resolved unique units',()=>{round=[{key:'kanji:日:kanji-to-meaning',kanjiId:'日',questionType:'kanji-to-meaning'},{key:'kanji:月:kanji-to-meaning',kanjiId:'月',questionType:'kanji-to-meaning'}];service.start('self-assessment');service.reveal();service.rate('again');service.reveal();service.rate('good');expect(service.resolvedCount()).toBe(1);expect(service.progressPercent()).toBe(50);service.reveal();service.rate('good');expect(service.firstTrySuccessCount()).toBe(1);expect(service.firstTryPercentage()).toBe(50)});
it('blocks a second daily Kanji round even through direct navigation',()=>{const daily=TestBed.inject(DailyLearningService);vi.mocked(daily.isCompletedToday).mockReturnValue(true);expect(service.start('quick-practice')).toBe(false);expect(progress.buildRound).not.toHaveBeenCalled()});it('records Kanji module metadata on completion',()=>{service.start('quick-practice');service.answerQuick('日');service.continueQuick();expect(history.record).toHaveBeenCalledWith(expect.objectContaining({module:'kanji',kanjiIds:['日'],questionTypes:['kanji-to-meaning']}))})
 it('credits a fresh ten second allowance on failure repetition and records once',()=>{
 round=round.slice(0,1);service.start('self-assessment');service.clock.attach();
 monotonic+=15000;service.reveal();service.rate('again');expect(service.clock.committedSeconds).toBe(10);
 monotonic+=4000;service.reveal();service.rate('good');expect(service.clock.committedSeconds).toBe(14);
 service.reveal();service.rate('good');expect(history.record).toHaveBeenCalledTimes(1);
 expect(history.record).toHaveBeenCalledWith(expect.objectContaining({durationSeconds:14}));
 monotonic+=60000;expect(service.clock.label()).toBe('00:14');
 service.clear();expect(service.clock.seconds()).toBe(0);
 service.start('self-assessment');monotonic+=60000;expect(service.clock.appearanceMilliseconds()).toBe(0);
 service.clock.attach();monotonic+=7000;service.reveal();service.rate('good');expect(history.record).toHaveBeenLastCalledWith(expect.objectContaining({durationSeconds:7}));
 });
});

