import { TestBed } from '@angular/core/testing';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MangaContextService, MANGA_ASSISTANT_ENDPOINT, limitedMangaRequest, validMangaContext } from './manga-context.service';
const request={selectedText:'食べなかった',targetLanguage:'es' as const};const location={volumeId:'volume',pageIndex:1,blockIndex:0};
describe('Manga context contract',()=>{
  it.each([
    [undefined,true], [['Posible error de OCR.'],true], [['a'.repeat(501)],false],
    [Array(6).fill('Aviso'),false], [['<script>alert(1)</script>'],false], [['<div>texto</div>'],false],
  ])('validates optional bounded plain study notes %j', (notes,valid)=>{
    expect(validMangaContext({natural:'Incierto',vocabulary:[],grammar:[],notes},'study')).toBe(valid);
  });
  it('sends exact selection and containing block separately and invalidates cache when context changes',async()=>{const fetch=vi.fn(async()=>({ok:true,body:null,text:async()=>JSON.stringify({natural:'No hay remedio.'})}));vi.stubGlobal('fetch',fetch);const context=service(),selected={...request,selectedText:'しょうがない',contextText:'しょうがないだろ。明日早いんだから。'};await context.request('translate',selected,location,new AbortController().signal);const options=fetch.mock.calls[0] as unknown as [string,RequestInit];expect(JSON.parse(options[1].body as string).request).toEqual(selected);await context.request('translate',selected,location,new AbortController().signal);expect(fetch).toHaveBeenCalledTimes(1);await context.request('translate',{...selected,contextText:'しょうがないだろ。今日は休みだから。'},location,new AbortController().signal);expect(fetch).toHaveBeenCalledTimes(2);expect(limitedMangaRequest({...selected,contextText:'あ'.repeat(1201)}).contextText).toHaveLength(1200);});
  beforeEach(()=>{localStorage.clear();});afterEach(()=>vi.unstubAllGlobals());
  function service(endpoint:string|null='https://example.test/assist'){TestBed.configureTestingModule({providers:[{provide:MANGA_ASSISTANT_ENDPOINT,useValue:endpoint}]});return TestBed.inject(MangaContextService);}
  it('does not fetch without configured backend',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const context=service(null);expect(context.available).toBe(false);await expect(context.request('translate',request,location,new AbortController().signal)).rejects.toThrow('unavailable');expect(fetch).not.toHaveBeenCalled();});
  it('bounds context and excludes page text and images',()=>{const bounded=limitedMangaRequest({...request,selectedText:'あ'.repeat(4000),previousText:'い'.repeat(500),pageTexts:['entire-page']});expect(bounded.selectedText.length).toBe(1200);expect(bounded.previousText?.length).toBe(300);expect(bounded.pageTexts).toBeUndefined();});
  it('validates structured translation and study results',()=>{expect(validMangaContext({natural:'No comí.',notes:['Sujeto omitido']},'translate')).toBe(true);expect(validMangaContext({natural:'No comí.',vocabulary:[{expression:'食べる',meaning:'comer'}],grammar:[{expression:'なかった',explanation:'pasado negativo'}]},'study')).toBe(true);expect(validMangaContext({natural:'text',grammar:'HTML'},'study')).toBe(false);expect(validMangaContext({natural:42},'translate')).toBe(false);});
  it('sends only explicit bounded requests and caches by OCR, language, mode and location',async()=>{const fetch=vi.fn(async()=>({ok:true,body:null,text:async()=>JSON.stringify({natural:'No comí.'})}));vi.stubGlobal('fetch',fetch);const context=service();await context.request('translate',request,location,new AbortController().signal);await context.request('translate',request,location,new AbortController().signal);expect(fetch).toHaveBeenCalledTimes(1);await context.request('translate',{...request,selectedText:'食べた'},location,new AbortController().signal);await context.request('translate',{...request,targetLanguage:'en'},location,new AbortController().signal);await context.request('translate',request,{...location,pageIndex:2},new AbortController().signal);expect(fetch).toHaveBeenCalledTimes(4);const options=fetch.mock.calls[0] as unknown as [string,RequestInit];expect(options[1].credentials).toBe('omit');expect(JSON.parse(options[1].body as string)).toEqual({schemaVersion:1,mode:'translate',request});expect(context.loading()).toBe(false);});
  it('reports HTTP errors and rejects invalid JSON without caching',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>({ok:false})));const context=service();await expect(context.request('translate',request,location,new AbortController().signal)).rejects.toThrow('http');expect(context.error()).toBe(true);expect(localStorage.getItem('kana-study-manga-context-v1')).toBeNull();});
  it('cancels an in-flight request without reporting an assistance error',async()=>{vi.stubGlobal('fetch',vi.fn((_:string,options:RequestInit)=>new Promise((_,reject)=>options.signal!.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))))));const context=service(),controller=new AbortController();const pending=context.request('translate',request,location,controller.signal);expect(context.loading()).toBe(true);controller.abort();await expect(pending).rejects.toThrow();expect(context.loading()).toBe(false);expect(context.error()).toBe(false);expect(localStorage.getItem('kana-study-manga-context-v1')).toBeNull();});
  it('honors cancellation before making any request',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const context=service(),controller=new AbortController();controller.abort();await expect(context.request('translate',request,location,controller.signal)).rejects.toThrow();expect(fetch).not.toHaveBeenCalled();});
});
