import { TestBed } from '@angular/core/testing';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import { RushAggregateStats,RushSession } from '../models/rush.model';
import { RushMedalService } from './rush-medal.service';
import { LocalRushRepository, RushRepository } from './rush-repository.service';
import { RushSessionService } from './rush-session.service';
class FakeRepository extends RushRepository{sessions=new Map<string,RushSession>();coverage=new Set<string>();async markOpenSessionsInterrupted(){}async createSession(s:RushSession){this.sessions.set(s.id,s)}async saveProgress(s:RushSession,id?:string){this.sessions.set(s.id,s);if(id)this.coverage.add(`${s.module}:${id}`)}async finishSession(s:RushSession){this.sessions.set(s.id,s)}async discardSession(id:string){this.sessions.delete(id)}async getStats():Promise<RushAggregateStats>{return{sessions:[...this.sessions.values()],coverage:[...this.coverage].map(key=>{const [module,contentId]=key.split(':');return{module:module as any,contentId,firstSeenAt:0}})}}}
const fakeMedals={refresh:vi.fn(async()=>[]),newlyUnlocked:()=>[],dismiss:vi.fn(),presentation:vi.fn()};
describe('RushSessionService',()=>{let service:RushSessionService;let repo:FakeRepository;beforeEach(()=>{vi.useFakeTimers();repo=new FakeRepository();TestBed.configureTestingModule({providers:[RushSessionService,{provide:LocalRushRepository,useValue:repo},{provide:RushMedalService,useValue:fakeMedals}]});service=TestBed.inject(RushSessionService)});it('counts only after reveal plus Next and tracks unique content',async()=>{await service.start('kana',[{key:'a1',module:'kana',contentId:'a',questionType:'one'},{key:'a2',module:'kana',contentId:'a',questionType:'two'},{key:'b',module:'kana',contentId:'b',questionType:'one'}]);expect(service.session()!.cardsCompleted).toBe(0);service.reveal();expect(service.session()!.cardsCompleted).toBe(0);await service.next();expect(service.session()!.cardsCompleted).toBe(1);expect(service.session()!.uniqueContentsSeen).toBe(1)});it('does not count a revealed card when exiting',async()=>{await service.start('kanji',[{key:'a',module:'kanji',contentId:'a',questionType:'one'}]);service.reveal();expect((await service.finish())).toBeNull();expect(repo.sessions.size).toBe(0)});it('blocks duplicate Next while persistence is pending',async()=>{let release!:()=>void;repo.saveProgress=vi.fn(async()=>new Promise<void>(resolve=>release=resolve));await service.start('kana',[{key:'a',module:'kana',contentId:'a',questionType:'one'}]);service.reveal();const first=service.next();const second=service.next();expect(repo.saveProgress).toHaveBeenCalledTimes(1);release();await Promise.all([first,second]);expect(service.session()!.cardsCompleted).toBe(1)});it('never modifies normal FSRS progress or review events',async()=>{const keys=['kana-study.study-progress.v2','kana-study.review-events.v1','kana-study.kanji-progress.v1','kana-study.kanji-review-events.v1','kana-study.vocabulary-progress.v1','kana-study.vocabulary-review-events.v1'];for(const key of keys)localStorage.setItem(key,JSON.stringify({sentinel:key}));const before=keys.map(key=>localStorage.getItem(key));await service.start('vocabulary',[{key:'v',module:'vocabulary',contentId:'entry',questionType:'japanese-to-meaning'}]);service.reveal();await service.next();expect(keys.map(key=>localStorage.getItem(key))).toEqual(before)})});

