import { signal } from '@angular/core';
import { ComponentFixture,TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import { RushSessionService } from '../../core/services/rush-session.service';
import { RushSettingsService } from '../../core/services/rush-settings.service';
import { TranslationService } from '../../core/services/translation.service';
import { VocabularySettingsService } from '../../core/services/vocabulary-settings.service';
import { VOCABULARY_N5 } from '../../data/vocabulary-n5.generated';
import { VocabularyRushPage } from './vocabulary-rush.page';
class RushStub{readonly loading=signal(false);readonly summary=signal(null);readonly session=signal({id:'s',module:'vocabulary',startedAt:0,endedAt:null,localDay:'2026-09-30',activeSeconds:0,cardsCompleted:0,uniqueContentsSeen:0,cyclesCompleted:0,initialUnitCount:1,interrupted:false});readonly currentUnit=signal({key:'u',module:'vocabulary',contentId:VOCABULARY_N5.find(e=>e.primaryWrittenForm!==e.primaryReading)!.id,questionType:'japanese-to-reading'});readonly revealed=signal(false);readonly saving=signal(false);readonly error=signal(false);readonly activeSeconds=signal(0);readonly medals={newlyUnlocked:signal([]),presentation:vi.fn(),dismiss:vi.fn()};start=vi.fn(async()=>true);checkpoint=vi.fn(async()=>{});finish=vi.fn();clear=vi.fn();reveal=vi.fn(()=>this.revealed.set(true));next=vi.fn(async()=>{this.revealed.set(false)})}
describe('VocabularyRushPage',()=>{let fixture:ComponentFixture<VocabularyRushPage>;let rush:RushStub;beforeEach(async()=>{rush=new RushStub();await TestBed.configureTestingModule({imports:[VocabularyRushPage],providers:[provideRouter([]),{provide:RushSessionService,useValue:rush},{provide:RushSettingsService,useValue:{getOrInitialize:()=>({selectedContentIds:['nouns'],questionTypes:['japanese-to-reading']})}},{provide:VocabularySettingsService,useValue:{selection:()=>({levels:{N5:true},categories:{nouns:true},questionTypes:['japanese-to-reading']})}},{provide:TranslationService,useValue:{language:()=> 'es',t:(key:string)=>key}}]}).compileComponents();fixture=TestBed.createComponent(VocabularyRushPage);fixture.detectChanges();await fixture.whenStable();fixture.detectChanges()});it('does not leak reading or furigana before reveal, then displays both',()=>{const entry=VOCABULARY_N5.find(e=>e.id===rush.currentUnit()!.contentId)!;expect(fixture.nativeElement.textContent).not.toContain(entry.primaryReading);expect(fixture.nativeElement.querySelector('rt')).toBeNull();rush.revealed.set(true);fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain(entry.primaryReading);expect(fixture.nativeElement.querySelector('.answer')).not.toBeNull()});it('uses Space for reveal and Next and ignores repeated keys',()=>{fixture.componentInstance.key(new KeyboardEvent('keydown',{code:'Space',repeat:true}));expect(rush.reveal).not.toHaveBeenCalled();fixture.componentInstance.key(new KeyboardEvent('keydown',{code:'Space'}));expect(rush.reveal).toHaveBeenCalledOnce();fixture.componentInstance.key(new KeyboardEvent('keydown',{code:'Space'}));expect(rush.next).toHaveBeenCalledOnce()})});
