import { computed,signal } from '@angular/core';import { TestBed } from '@angular/core/testing';import { Router } from '@angular/router';import { VOCABULARY_N5 } from '../../data/vocabulary-n5.generated';import { TranslationService } from '../../core/services/translation.service';import { VocabularyProgressService } from '../../core/services/vocabulary-progress.service';import { VocabularySessionService } from '../../core/services/vocabulary-session.service';import { VocabularyQuestionType } from '../../core/models/vocabulary.model';import { VocabularyPlayPage } from './vocabulary-play.page';
describe('VocabularyPlayPage furigana disclosure',()=>{const entry=VOCABULARY_N5.find(item=>item.primaryWrittenForm==='食べる')!;const type=signal<VocabularyQuestionType>('japanese-to-meaning'),mode=signal<'quick-practice'|'self-assessment'>('quick-practice'),feedback=signal<null|{correct:boolean;selectedId:string;correctId:string}>(null),revealed=signal(false);const learning={isPractice:signal(false),session:computed(()=>({id:'s',startedAt:new Date().toISOString(),completedAt:null,mode:mode(),sessionSize:1,units:[],items:[],attempts:0})),currentEntry:signal(entry),currentUnit:computed(()=>({key:`vocab:${entry.id}:${type()}`,entryId:entry.id,questionType:type()})),completed:signal(false),resolvedCount:signal(0),progressPercent:signal(0),firstTryPercentage:signal(0),feedback,revealed,newlyUnlockedMedals:signal([]),options:vi.fn(()=>VOCABULARY_N5.filter(item=>item.furigana.some(segment=>segment.reading)).slice(0,4).map((item,index)=>({id:item.id,label:item.primaryWrittenForm,correct:index===0}))),answerQuick:vi.fn(),continueQuick:vi.fn(),reveal:vi.fn(),rate:vi.fn(),clear:vi.fn(),restart:vi.fn(),dismissNextMedal:vi.fn()};beforeEach(async()=>{vi.clearAllMocks();learning.currentEntry.set(entry);learning.isPractice.set(false);learning.completed.set(false);type.set('japanese-to-meaning');mode.set('quick-practice');feedback.set(null);revealed.set(false);await TestBed.configureTestingModule({imports:[VocabularyPlayPage],providers:[{provide:VocabularySessionService,useValue:learning},{provide:VocabularyProgressService,useValue:{get:()=>null,roundSummary:signal({roundDue:0,roundNew:10})}},{provide:TranslationService,useValue:{t:(key:string)=>key,language:signal('es')}},{provide:Router,useValue:{navigateByUrl:vi.fn()}}]}).compileComponents()});afterEach(()=>TestBed.resetTestingModule());function render(){const fixture=TestBed.createComponent(VocabularyPlayPage);fixture.detectChanges();return fixture}
it('keeps romaji hidden before reveal and shows it in N5 self assessment',()=>{mode.set('self-assessment');const f=render();expect(f.nativeElement.querySelector('.romaji')).toBeNull();revealed.set(true);f.detectChanges();expect(f.nativeElement.querySelector('.answer .romaji').textContent).toBe('taberu');});
it('shows romaji only after quick-practice feedback',()=>{const f=render();expect(f.nativeElement.querySelector('.romaji')).toBeNull();feedback.set({correct:true,selectedId:entry.id,correctId:entry.id});f.detectChanges();expect(f.nativeElement.querySelector('.feedback-answer .romaji').textContent).toBe('taberu');});
it('hides romaji for a disabled level capability even after reveal',()=>{mode.set('self-assessment');learning.currentEntry.set({...entry,jlptApproxLevel:'N4'});revealed.set(true);expect(render().nativeElement.querySelector('.romaji')).toBeNull();});
it('Space reveals once, prevents scrolling and ignores repeat',()=>{mode.set('self-assessment');const f=render();const e=new KeyboardEvent('keydown',{code:'Space',key:' ',cancelable:true});f.componentInstance.handleKey(e);expect(learning.reveal).toHaveBeenCalledOnce();expect(e.defaultPrevented).toBe(true);f.componentInstance.handleKey(new KeyboardEvent('keydown',{code:'Space',key:' ',repeat:true,cancelable:true}));expect(learning.reveal).toHaveBeenCalledOnce();});
it.each([['1','again'],['2','hard'],['3','good']] as const)('only rates %s after reveal', (key,rating)=>{mode.set('self-assessment');const f=render();f.componentInstance.handleKey(new KeyboardEvent('keydown',{key}));expect(learning.rate).not.toHaveBeenCalled();revealed.set(true);f.componentInstance.handleKey(new KeyboardEvent('keydown',{key}));expect(learning.rate).toHaveBeenCalledExactlyOnceWith(rating);f.componentInstance.handleKey(new KeyboardEvent('keydown',{key,repeat:true}));expect(learning.rate).toHaveBeenCalledOnce();});
it.each(['input','textarea','select','div'])('ignores keyboard actions inside %s',tag=>{mode.set('self-assessment');const f=render();const element=document.createElement(tag);if(tag==='div')element.setAttribute('contenteditable','true');document.body.append(element);const event=new KeyboardEvent('keydown',{code:'Space',key:' ',bubbles:true,cancelable:true});element.dispatchEvent(event);expect(learning.reveal).not.toHaveBeenCalled();revealed.set(true);element.dispatchEvent(new KeyboardEvent('keydown',{key:'3',bubbles:true}));expect(learning.rate).not.toHaveBeenCalled();element.remove();});
it('ignores shortcuts in quick practice and exit confirmation',()=>{const f=render();f.componentInstance.handleKey(new KeyboardEvent('keydown',{code:'Space',key:' '}));expect(learning.reveal).not.toHaveBeenCalled();mode.set('self-assessment');f.componentInstance.showExit.set(true);f.componentInstance.handleKey(new KeyboardEvent('keydown',{code:'Space',key:' '}));expect(learning.reveal).not.toHaveBeenCalled();});
it('ignores Space after reveal',()=>{mode.set('self-assessment');revealed.set(true);const f=render();f.componentInstance.handleKey(new KeyboardEvent('keydown',{code:'Space',key:' '}));expect(learning.reveal).not.toHaveBeenCalled();expect(learning.rate).not.toHaveBeenCalled();});
it('shows ruby before answering Japanese to Meaning',()=>{type.set('japanese-to-meaning');expect(render().nativeElement.querySelector('rt')?.textContent).toBe('た')});it('shows ruby in Meaning to Japanese choices',()=>{type.set('meaning-to-japanese');expect(render().nativeElement.querySelector('.options rt')).not.toBeNull()});it('does not render any hidden reading before Japanese to Reading, then reveals it after feedback',()=>{type.set('japanese-to-reading');const fixture=render();expect(fixture.nativeElement.querySelector('rt')).toBeNull();feedback.set({correct:true,selectedId:entry.id,correctId:entry.id});fixture.detectChanges();expect(fixture.nativeElement.querySelector('.feedback-answer rt')?.textContent).toBe('た')});it('keeps Reading to Japanese choices free of rt until evaluated',()=>{type.set('reading-to-japanese');const fixture=render();expect(fixture.nativeElement.querySelector('.options rt')).toBeNull();feedback.set({correct:true,selectedId:entry.id,correctId:entry.id});fixture.detectChanges();expect(fixture.nativeElement.querySelector('rt')).not.toBeNull()});for(const questionType of ['meaning-to-japanese','japanese-to-reading','reading-to-japanese'] as const){it(`reveals annotated answer after self assessment for ${questionType}`,()=>{type.set(questionType);mode.set('self-assessment');revealed.set(false);const fixture=render();expect(fixture.nativeElement.querySelector('rt')).toBeNull();revealed.set(true);fixture.detectChanges();expect(fixture.nativeElement.querySelector('.answer rt')?.textContent).toBe('た')})}});

describe('Vocabulary additional-practice results',()=>{
  for(const practice of [true,false])it(`keeps daily completion UI exclusive to normal sessions: ${practice}`,()=>{
    const entry=VOCABULARY_N5[0];
    TestBed.configureTestingModule({providers:[
      {provide:VocabularySessionService,useValue:{isPractice:signal(practice),completed:signal(true),clear:vi.fn(),session:signal({sessionSize:1,attempts:1,items:[],startedAt:new Date().toISOString(),completedAt:new Date().toISOString()}),firstTryPercentage:signal(100),resolvedCount:signal(1),progressPercent:signal(100),newlyUnlockedMedals:signal([])}},
      {provide:VocabularyProgressService,useValue:{roundSummary:signal({roundDue:0,roundNew:1})}},
      {provide:TranslationService,useValue:{t:(key:string)=>key,language:signal('es')}},
      {provide:Router,useValue:{navigateByUrl:vi.fn()}},
    ]});
    const f=TestBed.createComponent(VocabularyPlayPage);f.detectChanges();
    expect(f.nativeElement.textContent.includes('daily.completedButton')).toBe(!practice);
    expect(f.nativeElement.querySelector('.next-round')!==null).toBe(!practice);
    expect(f.nativeElement.textContent.includes('writing.finished')).toBe(practice);
  });
});
