import { TestBed } from '@angular/core/testing';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { MangaOcrComponent } from './manga-ocr.component';
import { MokuroPage } from '../../core/models/manga.model';
import { ocrSelectionPoint } from './manga-ocr-selection';
const page=(vertical=false):MokuroPage=>({img_path:'test.png',img_width:1000,img_height:1400,blocks:[{box:[0,0,900,500],vertical,font_size:30,lines:['今日はひとりで行く','昨日は','ひとりで行った'],lines_coords:[[[0,0],[900,0],[900,50],[0,50]],[[0,100],[900,100],[900,150],[0,150]],[[0,200],[900,200],[900,250],[0,250]]]},{box:[0,600,900,800],vertical,font_size:30,lines:['ありがとう'],lines_coords:[[[0,600],[900,600],[900,650],[0,650]]]}]});
function setup(vertical=false){const fixture=TestBed.createComponent(MangaOcrComponent);fixture.componentRef.setInput('page',page(vertical));fixture.detectChanges();return fixture;}
function select(host:HTMLElement,startLine:number,start:number,endLine=startLine,end=start){const lines=host.querySelectorAll('.ocr-line'),range=document.createRange();range.setStart(lines[startLine].firstChild!,start);range.setEnd(lines[endLine].firstChild!,end);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);return selection;}
function pointer(x=0,y=0){return {isPrimary:true,button:0,clientX:x,clientY:y} as PointerEvent;}
function click(line:Element,x=0,y=0){return {currentTarget:line,clientX:x,clientY:y,stopPropagation:vi.fn()} as unknown as MouseEvent;}
describe('Manga OCR native selection',()=>{
  it('keeps a pointercancel selection snapshot through subsequent native collapse and emits once',()=>{vi.useFakeTimers();const fixture=setup(),component=fixture.componentInstance,host=fixture.nativeElement as HTMLElement,emitted=vi.fn();component.wordClicked.subscribe(emitted);component.pointerStart(pointer());select(host,0,3,0,6);component.selectionChanged();component.pointerCancel();window.getSelection()!.collapse(host.querySelector('.ocr-line')!.firstChild,4);component.selectionChanged();vi.advanceTimersByTime(650);component.selectionChanged();vi.runAllTimers();expect(emitted).toHaveBeenCalledOnce();expect(emitted.mock.calls[0][0].selectedText).toBe('ひとり');});
  it('does not emit after pointercancel without a valid selection',()=>{vi.useFakeTimers();const fixture=setup(),component=fixture.componentInstance,emitted=vi.fn();component.wordClicked.subscribe(emitted);component.pointerStart(pointer());component.pointerCancel();vi.runAllTimers();expect(emitted).not.toHaveBeenCalled();});
  afterEach(()=>{window.getSelection()?.removeAllRanges();vi.useRealTimers();vi.restoreAllMocks();TestBed.resetTestingModule();});
  it.each([false,true])('preserves same-line ひとり exactly, vertical=%s',vertical=>{const fixture=setup(vertical),host=fixture.nativeElement as HTMLElement;const selected=select(host,0,3,0,6);expect(ocrSelectionPoint(host,page(vertical),selected)).toMatchObject({mode:'selection',selectedText:'ひとり',startOffset:3,endOffset:6,blockIndex:0,lineIndex:0});});
  it('preserves a selected phrase instead of a single word',()=>{const fixture=setup(),host=fixture.nativeElement as HTMLElement;expect(ocrSelectionPoint(host,page(),select(host,0,3,0,9))?.selectedText).toBe('ひとりで行く');});
  it('reconstructs multiple lines of one block using Mokuro newline boundaries',()=>{const fixture=setup(),host=fixture.nativeElement as HTMLElement;expect(ocrSelectionPoint(host,page(),select(host,1,0,2,7))).toMatchObject({selectedText:'昨日は\nひとりで行った',lineIndex:1,endLineIndex:2});});
  it('preserves native cross-block text and records both blocks',()=>{const fixture=setup(),host=fixture.nativeElement as HTMLElement;const selection=select(host,2,0,3,5);expect(ocrSelectionPoint(host,page(),selection)).toMatchObject({selectedText:selection.toString().trim(),blockIndex:0,endBlockIndex:1});});
  it('ignores empty selections and selections outside OCR',()=>{const fixture=setup(),host=fixture.nativeElement as HTMLElement;expect(ocrSelectionPoint(host,page(),select(host,0,0))).toBeNull();const outside=document.createElement('p');outside.textContent='日本語';document.body.append(outside);const range=document.createRange();range.selectNodeContents(outside);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);expect(ocrSelectionPoint(host,page(),selection)).toBeNull();outside.remove();});
  it('manual selection wins over caret and survives collapse after pointerup',()=>{vi.useFakeTimers();const fixture=setup(),host=fixture.nativeElement as HTMLElement,component=fixture.componentInstance,emitted=vi.fn();component.wordClicked.subscribe(emitted);component.pointerStart(pointer());select(host,0,3,0,6);component.pointerEnd(pointer());window.getSelection()!.collapse(host.querySelector('.ocr-line')!.firstChild,4);component.lookupClick(click(host.querySelector('.ocr-line')!),0,0);vi.runAllTimers();expect(emitted).toHaveBeenCalledOnce();expect(emitted.mock.calls[0][0]).toMatchObject({mode:'selection',selectedText:'ひとり'});});
  it('dragging without a valid selection never emits a caret lookup',()=>{const fixture=setup(),component=fixture.componentInstance,emitted=vi.fn();component.wordClicked.subscribe(emitted);component.pointerStart(pointer());component.pointerMove(pointer(50));component.pointerEnd(pointer(50));component.lookupClick(click(fixture.nativeElement.querySelector('.ocr-line'),50),0,0);expect(emitted).not.toHaveBeenCalled();});
  it('normal tap still emits a caret lookup with OCR context',()=>{const fixture=setup(),component=fixture.componentInstance,line=fixture.nativeElement.querySelector('.ocr-line') as HTMLElement,emitted=vi.fn();component.wordClicked.subscribe(emitted);Object.defineProperty(document,'caretPositionFromPoint',{configurable:true,value:vi.fn(()=>({offsetNode:line.firstChild,offset:4}))});component.pointerStart(pointer());component.pointerEnd(pointer());component.lookupClick(click(line),0,0);expect(emitted.mock.calls[0][0]).toMatchObject({mode:'caret',text:'今日はひとりで行く\n昨日は\nひとりで行った',offset:4,blockIndex:0,lineIndex:0});Reflect.deleteProperty(document,'caretPositionFromPoint');});
  it('native mobile selection changes settle without preventing default or clearing ranges',()=>{vi.useFakeTimers();const fixture=setup(),component=fixture.componentInstance,emitted=vi.fn();component.wordClicked.subscribe(emitted);const event=pointer();const preventDefault=vi.fn();Object.assign(event,{pointerType:'touch',preventDefault});component.pointerStart(event);select(fixture.nativeElement,0,3,0,6);component.selectionChanged();vi.advanceTimersByTime(1000);expect(emitted).not.toHaveBeenCalled();component.pointerEnd(event);vi.advanceTimersByTime(180);expect(emitted.mock.calls[0][0].selectedText).toBe('ひとり');expect(preventDefault).not.toHaveBeenCalled();expect(window.getSelection()!.toString()).toBe('ひとり');});
  it('supports selection handles/keyboard updates after pointer release and cancels timers on destruction',()=>{vi.useFakeTimers();const fixture=setup(),component=fixture.componentInstance,emitted=vi.fn();component.wordClicked.subscribe(emitted);select(fixture.nativeElement,0,3,0,9);component.selectionChanged();vi.advanceTimersByTime(650);expect(emitted.mock.calls[0][0].selectedText).toBe('ひとりで行く');select(fixture.nativeElement,0,3,0,6);component.selectionChanged();fixture.destroy();vi.runAllTimers();expect(emitted).toHaveBeenCalledOnce();});
});
