import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { DictionaryPopup } from '../../shared/components/dictionary-popup/dictionary-popup';
import { MangaGuidePage } from './manga-guide.page';
import { MangaPage } from './manga.page';
import { DictionaryInstallComponent } from './dictionary-install.component';
import { DictionaryRepository } from '../../core/services/dictionary.repository';
import { MangaRepository } from '../../core/services/manga.repository';
import { MangaContextService } from '../../core/services/manga-context.service';
import { MANGA_ROUTES } from './manga.routes';
import { DictionaryLookup } from '../../core/models/dictionary.model';
import { SettingsService } from '../../core/services/settings.service';
const exact:DictionaryLookup={installed:true,query:'学校',terms:[{id:'school',dictionaryId:'test',expression:'学校',reading:'がっこう',glossaries:['escuela'],definitionTags:'',rules:'n',score:0,sequence:1,termTags:''}]};
describe('Manga assisted reading UI',()=>{
  it('renders translation notes as text and allows responses without notes',()=>{
    const fixture=popup();fixture.componentInstance.tab.set('context');
    fixture.componentInstance.translation.set({natural:'Incierto',notes:['Posible OCR: <b>texto</b>']});fixture.detectChanges();
    expect(fixture.nativeElement.textContent).toContain('Posible OCR: <b>texto</b>');expect(fixture.nativeElement.querySelector('.dictionary-sheet b')).toBeNull();
    fixture.componentInstance.translation.set({natural:'Anterior'});fixture.detectChanges();expect(fixture.nativeElement.textContent).not.toContain('Posible OCR');
  });
  it('exposes only Translate with endpoint and blocks Study invocation from the popup',async()=>{
    const request=vi.fn(async(_mode:string)=>({natural:'Traducción'}));TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request}});
    const fixture=popup();fixture.componentRef.setInput('context',{text:'学校',offset:0,x:0,y:0,blockIndex:0});fixture.componentInstance.tab.set('context');fixture.detectChanges();
    const actions=fixture.nativeElement.querySelectorAll('.context-actions button');expect(actions).toHaveLength(1);expect(actions[0].disabled).toBe(false);expect(actions[0].textContent).toContain('Traducir');
    await fixture.componentInstance.ask('study');expect(request).not.toHaveBeenCalled();
    actions[0].click();await fixture.whenStable();expect(request.mock.calls[0]?.[0]).toBe('translate');
  });
  it('keeps dictionary results available when translation fails',async()=>{
    TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request:vi.fn(async()=>{throw new Error('AI unavailable');})}});
    const fixture=popup();fixture.componentRef.setInput('context',{text:'学校',offset:0,x:0,y:0,blockIndex:0});fixture.componentInstance.tab.set('context');fixture.detectChanges();
    await fixture.componentInstance.ask('translate');fixture.detectChanges();expect(fixture.nativeElement.querySelector('[role=alert]')).not.toBeNull();
    fixture.componentInstance.tab.set('word');fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('escuela');
  });
  it.each(['es','en','ca'] as const)('separates senses and interpretations and translates negative-nu in %s',language=>{TestBed.inject(SettingsService).setLanguage(language);const fixture=popup({...exact,baseForm:'行く',reasons:['negative-nu'],terms:[{...exact.terms[0],id:'go',expression:'行く',reading:'いく'},{...exact.terms[0],id:'go-sense',expression:'行く',reading:'いく',glossaries:['another sense']},{...exact.terms[0],id:'say',expression:'言う',reading:'いう'}]});const details=fixture.nativeElement.querySelectorAll('details');expect(details).toHaveLength(2);expect(details[0].textContent).toContain('another sense');expect(details[0].textContent).not.toContain('言う');expect(details[1].textContent).toContain('言う');expect(fixture.nativeElement.textContent).not.toMatch(/manga\.(assist|reason)\./);expect(details[1].querySelector('summary').textContent).toBe(language==='es'?'Posibles interpretaciones':language==='en'?'Possible interpretations':'Possibles interpretacions');});
  it('keeps plausible ambiguous deinflections visible in the existing alternatives section',()=>{const fixture=popup({...exact,surface:'きた',baseForm:'くる',terms:[{...exact.terms[0],id:'come',expression:'来る',reading:'くる'},{...exact.terms[0],id:'wear',expression:'着る',reading:'きる'}]});const details=fixture.nativeElement.querySelector('details') as HTMLDetailsElement;expect(details).not.toBeNull();details.open=true;expect(details.textContent).toContain('着る · きる');expect(fixture.nativeElement.querySelector('.base').textContent).toContain('くる');});
  it('does not duplicate caret blocks or manufacture cross-block context',async()=>{const request=vi.fn(async(_mode:string,_request:unknown)=>({natural:'text'}));TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request}});const fixture=popup();for(const point of [{mode:'caret',text:'学校へ行く',selectedText:'学校へ行く',blockIndex:0},{mode:'selection',text:'学校へ行く',selectedText:'学校へ行く\n明日。',blockIndex:0,endBlockIndex:1}] as const){fixture.componentRef.setInput('context',{...point,offset:0,x:0,y:0});fixture.detectChanges();await fixture.componentInstance.ask('translate');expect(request.mock.calls.at(-1)![1]).toMatchObject({selectedText:point.selectedText,contextText:undefined});}});
  it('passes exact manual selection with the full containing Mokuro block',async()=>{const request=vi.fn(async(_mode:string,_request:unknown)=>({natural:'No hay remedio.'}));TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request}});const fixture=popup({...exact,terms:[]});fixture.componentRef.setInput('context',{mode:'selection',text:'しょうがないだろ。明日早いんだから。',selectedText:'しょうがない',offset:0,x:0,y:0,blockIndex:1,endBlockIndex:1,previousText:'前。',nextText:'後。'});fixture.detectChanges();await fixture.componentInstance.ask('translate');expect(request.mock.calls[0][1]).toMatchObject({selectedText:'しょうがない',contextText:'しょうがないだろ。明日早いんだから。',previousText:'前。',nextText:'後。'});});
  it('keeps one hidden manga file input connected to the landing buttons',async()=>{const fixture=TestBed.createComponent(MangaPage);fixture.detectChanges();await fixture.whenStable();fixture.detectChanges();const input=fixture.nativeElement.querySelector('input[accept=".zip,.cbz"]') as HTMLInputElement;expect(fixture.nativeElement.querySelectorAll('input[accept=".zip,.cbz"]')).toHaveLength(1);expect(input.hidden).toBe(true);expect(input.getAttribute('aria-label')).toBeTruthy();expect(fixture.nativeElement.querySelector('label.import-button')).toBeNull();const click=vi.spyOn(input,'click').mockImplementation(()=>{});for(const button of fixture.nativeElement.querySelectorAll('.primary-action'))button.click();expect(click).toHaveBeenCalledTimes(2);});
  beforeEach(()=>{vi.stubGlobal("matchMedia",vi.fn(()=>({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()})));localStorage.clear();TestBed.configureTestingModule({providers:[provideRouter([]),{provide:DictionaryRepository,useValue:{cleanup:async()=>{},ready:async()=>undefined}},{provide:MangaRepository,useValue:{cleanup:async()=>false,volumes:async()=>[],page:async()=>undefined,progress:async()=>undefined}}]});});
  afterEach(()=>{TestBed.resetTestingModule();vi.restoreAllMocks();vi.unstubAllGlobals();});
  function popup(result=exact){const fixture=TestBed.createComponent(DictionaryPopup);fixture.componentRef.setInput('result',result);fixture.detectChanges();return fixture;}
  it('shows exact words and keeps word/context controls clear',()=>{const fixture=popup();expect(fixture.nativeElement.querySelector('h2').textContent).toBe('学校');expect(fixture.nativeElement.textContent).toContain('escuela');expect(fixture.nativeElement.querySelectorAll('.tabs button').length).toBe(2);});
  it('shows conjugated surface, base and readable reasons',()=>{const fixture=popup({...exact,surface:'食べなかった',baseForm:'食べる',surfaceReading:'たべなかった',reading:'たべる',reasons:['negative-past']});expect(fixture.nativeElement.textContent).toContain('食べなかった');expect(fixture.nativeElement.textContent).toContain('Forma base');expect(fixture.nativeElement.textContent).toContain('Pasado negativo');});
  it.each([['missing',{...exact,installed:false,terms:[]},'Instala'],['empty',{...exact,query:'未知',terms:[]},'未知']] as const)('shows %s state',(_,result,text)=>{const fixture=popup({...result,terms:[...result.terms]});expect(fixture.nativeElement.textContent).toContain(text);});
  it('shows loading and errors as accessible status',()=>{const fixture=popup();fixture.componentRef.setInput('loading',true);fixture.detectChanges();expect(fixture.nativeElement.querySelector('[role=status]')).not.toBeNull();fixture.componentRef.setInput('loading',false);fixture.componentRef.setInput('failed',true);fixture.detectChanges();expect(fixture.nativeElement.querySelector('[role=alert]')).not.toBeNull();});
  it('highlights selected OCR text and disables unconfigured context requests',()=>{const fixture=popup();fixture.componentRef.setInput('context',{text:'今日は学校へ',offset:3,x:0,y:0,blockIndex:2,lineIndex:0});fixture.componentInstance.tab.set('context');fixture.detectChanges();expect(fixture.nativeElement.querySelector('mark').textContent).toBe('学校');expect([...fixture.nativeElement.querySelectorAll('.context-actions button')].every((button:any)=>button.disabled)).toBe(true);expect(fixture.nativeElement.textContent).toContain('configurar');});
  it('focuses close, traps focus, handles Escape and restores prior focus',async()=>{const previous=document.createElement('button');document.body.append(previous);previous.focus();const fixture=popup();await fixture.whenStable();fixture.detectChanges();const close=fixture.nativeElement.querySelector('.close') as HTMLButtonElement;expect(document.activeElement).toBe(close);const tab=new KeyboardEvent("keydown",{key:"Tab",shiftKey:true,cancelable:true});fixture.componentInstance.key(tab);expect(tab.defaultPrevented).toBe(true);expect(document.activeElement).toBe([...fixture.nativeElement.querySelectorAll("button:not(:disabled),a,summary")].at(-1));const escaped=vi.fn();fixture.componentInstance.closed.subscribe(escaped);fixture.componentInstance.key(new KeyboardEvent('keydown',{key:'Escape',cancelable:true}));expect(escaped).toHaveBeenCalledOnce();fixture.destroy();expect(document.activeElement).toBe(previous);previous.remove();});
  it('uses the responsive sheet class for mobile and bounds desktop position',()=>{const fixture=popup();fixture.componentRef.setInput('x',10000);fixture.componentRef.setInput('y',10000);fixture.detectChanges();expect(fixture.nativeElement.querySelector('.dictionary-sheet')).not.toBeNull();expect(fixture.componentInstance.left()).toBeLessThan(window.innerWidth);expect(fixture.componentInstance.top()).toBeLessThan(window.innerHeight);});
  it('landing shows hero, useful empty state and guide links',async()=>{const fixture=TestBed.createComponent(MangaPage);fixture.detectChanges();await fixture.whenStable();fixture.detectChanges();expect(fixture.nativeElement.querySelector('h1').textContent).toBe('Lee manga en japonés de verdad');expect(fixture.nativeElement.querySelector('.empty-library').textContent).toContain('No tienes mangas');expect(fixture.nativeElement.querySelector('a[href="/manga/guide"]')).not.toBeNull();});
  it('library cards keep read primary and delete in a secondary menu',async()=>{const fixture=TestBed.createComponent(MangaPage);fixture.detectChanges();await fixture.whenStable();fixture.componentInstance.volumes.set([{id:'vol',title:'Uno',seriesTitle:'Serie',pageCount:12,storageBytes:100,complete:true,createdAt:'',updatedAt:'',mokuro:{version:'0.2.0',title:'Serie',volume:'Uno'}}]);fixture.detectChanges();expect(fixture.nativeElement.querySelector('.library-grid h2').textContent).toBe('Uno');expect(fixture.nativeElement.querySelector('.volume-menu button').textContent).toContain('Eliminar');expect(fixture.nativeElement.querySelector('.library-grid a').textContent).toContain('Leer');});
  it('dictionary shows real installed count, offline status and advanced import',async()=>{const fixture=TestBed.createComponent(DictionaryInstallComponent);fixture.detectChanges();await fixture.whenStable();fixture.componentInstance.ready.set({id:'active',dictionaryId:'test',title:'JMdict',revision:'test',count:42,status:'ready',updatedAt:''});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('42');expect(fixture.nativeElement.textContent).toContain('sin conexión');expect(fixture.nativeElement.querySelector('details input[type=file]')).not.toBeNull();});
  it('dictionary missing state offers install first and preserves manual import',async()=>{const fixture=TestBed.createComponent(DictionaryInstallComponent);fixture.detectChanges();await fixture.whenStable();fixture.detectChanges();expect(fixture.nativeElement.querySelector('button').textContent).toContain('Instalar diccionario');expect(fixture.nativeElement.querySelector('details summary').textContent).toBe('Opciones avanzadas');});
  it('guide is lazily routed and explains all steps without unresolved keys in ES/EN/CA',async()=>{const route=MANGA_ROUTES.find(route=>route.path==='guide');expect(route?.loadComponent).toBeTypeOf('function');const fixture=TestBed.createComponent(MangaGuidePage);for(const language of ['es','en','ca'] as const){TestBed.inject(SettingsService).setLanguage(language);fixture.detectChanges();expect(fixture.nativeElement.querySelectorAll('.guide-section').length).toBe(5);expect(fixture.nativeElement.querySelectorAll('.guide-faq details').length).toBe(5);expect(fixture.nativeElement.textContent).not.toMatch(/manga\.(guide|assist|landing)\./);}expect((await (route!.loadComponent as ()=>Promise<unknown>)())).toBe(MangaGuidePage);});

  it('shows a selected phrase with a neutral dictionary message and keeps context available',()=>{const fixture=popup({query:'ひとりで行く',terms:[],installed:true,mode:'selection',requestedText:'ひとりで行く'});expect(fixture.nativeElement.querySelector('.selected-text').textContent).toBe('ひとりで行く');expect(fixture.nativeElement.textContent).toContain('Texto seleccionado');expect(fixture.nativeElement.textContent).toContain('No hay una entrada única');expect(fixture.nativeElement.textContent).not.toContain('Sin resultados');fixture.componentInstance.tab.set('context');fixture.detectChanges();expect(fixture.nativeElement.querySelector('.context-actions')).not.toBeNull();});
  it('selected words retain the exact selection alongside their dictionary written form',()=>{const fixture=popup({...exact,mode:'selection',requestedText:'ひとり',terms:[{...exact.terms[0],expression:'一人',reading:'ひとり'}]});expect(fixture.nativeElement.querySelector('.selected-text').textContent).toBe('ひとり');expect(fixture.nativeElement.querySelector('h2').textContent).toBe('一人');});
  it.each(['selection','caret'] as const)('context request respects %s intent',async(mode)=>{const request=vi.fn(async(_mode:string,_request:unknown)=>({natural:'Solo voy.'}));TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request}});const fixture=popup({query:mode==='selection'?'ひとりで行く':'ひとり',terms:mode==='selection'?[]:exact.terms,installed:true,surface:'ひとり'});fixture.componentRef.setInput('context',{mode,text:'今日はひとりで行く',selectedText:mode==='selection'?'ひとりで行く':'今日はひとりで行く',offset:3,x:0,y:0,blockIndex:0,lineIndex:0});fixture.detectChanges();await fixture.componentInstance.ask('translate');expect(request.mock.calls[0]?.[1]).toEqual(expect.objectContaining({selectedText:mode==='selection'?'ひとりで行く':'今日はひとりで行く',selectedExpression:mode==='selection'?undefined:'ひとり',targetLanguage:'es'}));});
  it('does not silently truncate oversized manual selections in contextual requests',async()=>{const request=vi.fn();TestBed.overrideProvider(MangaContextService,{useValue:{available:true,request}});const fixture=popup({...exact,terms:[],mode:'selection'}),selectedText='あ'.repeat(1201);fixture.componentRef.setInput('context',{mode:'selection',text:selectedText,selectedText,offset:0,x:0,y:0});fixture.componentInstance.tab.set('context');fixture.detectChanges();await fixture.componentInstance.ask('translate');fixture.detectChanges();expect(request).not.toHaveBeenCalled();expect(fixture.nativeElement.querySelector('.selected-text').textContent).toBe(selectedText);expect(fixture.nativeElement.querySelector('[role=alert]').textContent).toContain('no hemos recortado');});
});
