import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { KANJI_N5 } from '../../data/kanji-n5.generated';
import { Kanji, KanjiQuestionType } from '../../core/models/kanji.model';
import { KanjiProgressService } from '../../core/services/kanji-progress.service';
import { TranslationService } from '../../core/services/translation.service';
@Component({selector:'app-kanji-all-page',templateUrl:'./kanji-all.page.html',styleUrl:'./kanji-all.page.scss',changeDetection:ChangeDetectionStrategy.OnPush,host:{'(document:keydown.escape)':'closeOverlay()'}})
export class KanjiAllPage {readonly i18n=inject(TranslationService);readonly progress=inject(KanjiProgressService);readonly searching=signal(false);readonly query=signal('');readonly selected=signal<Kanji|null>(null);private readonly router=inject(Router);private readonly route=inject(ActivatedRoute);readonly filtered=computed(()=>{const q=this.normalize(this.query());return KANJI_N5.filter(k=>!q||[k.character,'N5',String(k.strokeCount),...Object.values(k.meanings).flat(),...k.onyomi,...k.kunyomi,...k.examples.flatMap(e=>[e.word,e.reading,e.romaji,...Object.values(e.translations)])].some(v=>this.normalize(v).includes(q)))});back(){void this.router.navigateByUrl('/kanji')}setQuery(event:Event){this.query.set((event.target as HTMLInputElement).value)}closeOverlay(){if(this.selected())this.selected.set(null);else if(this.searching()){this.searching.set(false);this.query.set('')}}meaning(k:Kanji){return k.meanings[this.i18n.language()].join(' · ')}statusKey(k:Kanji,type:KanjiQuestionType){const p=this.progress.get(`kanji:${k.id}:${type}`);if(!p)return'home.new';return p.fsrs.state==='review'?'home.memorized':'home.pending'}constructor(){const character=this.route.snapshot.queryParamMap.get('selected');if(character)this.selected.set(KANJI_N5.find(k=>k.character===character)??null)}private normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}}

