/** Reviewed UI entry points. Update this map whenever a public route is introduced.
 * Dynamic routes require an existing deck/volume/topic; programmatic session actions
 * are UI entry points too. Auth and upload also accept external callbacks/deep-links.
 */
export interface RouteAuditEntry {route:string;entryPoint:string;type:'ui'|'dynamic'|'external-deeplink';}
export const NAVIGATION_AUDIT:readonly RouteAuditEntry[]=[
  {route:'',entryPoint:'Home / brand',type:'ui'},
  {route:'settings',entryPoint:'Home settings / More tools',type:'ui'},
  {route:'learn',entryPoint:'Home Learn start panel',type:'ui'},
  {route:'cards',entryPoint:'Home Explore cards',type:'ui'},
  {route:'selection',entryPoint:'Home Explore selection / Grammar kana links',type:'ui'},
  {route:'medals',entryPoint:'Home medals',type:'ui'},
  {route:'more',entryPoint:'Home Explore modules / module back links',type:'ui'},
  {route:'auth',entryPoint:'AccountControl / auth email callbacks',type:'external-deeplink'},
  {route:'profile',entryPoint:'AccountControl',type:'ui'},
  {route:'writing',entryPoint:'Home Writing / Kana card practice',type:'ui'},
  {route:'weaknesses',entryPoint:'More tools',type:'ui'},
  {route:'stats',entryPoint:'More tools',type:'ui'},
  {route:'rush/medals',entryPoint:'RUSH configuration / results',type:'ui'},
  {route:'rush',entryPoint:'Home RUSH configuration start action',type:'ui'},
  {route:'upload',entryPoint:'Manga remote link form / compatible external deep-link',type:'external-deeplink'},
  {route:'flags',entryPoint:'More Flags',type:'ui'},
  {route:'flags/selection',entryPoint:'Flags selection button / Explore',type:'ui'},
  {route:'flags/play',entryPoint:'Flags start panel action',type:'ui'},
  {route:'flags/countries',entryPoint:'Flags Explore countries',type:'ui'},
  {route:'flags/medals',entryPoint:'Flags medals',type:'ui'},
  {route:'kanji',entryPoint:'More Kanji',type:'ui'},
  {route:'kanji/selection',entryPoint:'Kanji selection button / Explore',type:'ui'},
  {route:'kanji/play',entryPoint:'Kanji Learn start panel',type:'ui'},
  {route:'kanji/all',entryPoint:'Kanji Explore all',type:'ui'},
  {route:'kanji/medals',entryPoint:'Kanji medals',type:'ui'},
  {route:'kanji/rush',entryPoint:'Kanji RUSH configuration start action',type:'ui'},
  {route:'kanji/writing',entryPoint:'Kanji Writing / detail practice',type:'ui'},
  {route:'vocabulary',entryPoint:'More Vocabulary',type:'ui'},
  {route:'vocabulary/selection',entryPoint:'Vocabulary selection button / Explore',type:'ui'},
  {route:'vocabulary/play',entryPoint:'Vocabulary Learn start panel',type:'ui'},
  {route:'vocabulary/all',entryPoint:'Vocabulary Explore all',type:'ui'},
  {route:'vocabulary/medals',entryPoint:'Vocabulary medals',type:'ui'},
  {route:'vocabulary/rush',entryPoint:'Vocabulary RUSH configuration start action',type:'ui'},
  {route:'vocabulary/writing',entryPoint:'Vocabulary Writing / detail practice',type:'ui'},
  {route:'vocabulary/listening',entryPoint:'Vocabulary Listening / weaknesses focused practice',type:'ui'},
  {route:'anki',entryPoint:'More Decks',type:'ui'},
  {route:'anki/:deckId/cards',entryPoint:'Deck card browse action',type:'dynamic'},
  {route:'anki/:deckId/stats',entryPoint:'Deck card statistics action',type:'dynamic'},
  {route:'anki/:deckId/settings',entryPoint:'Deck card configuration action',type:'dynamic'},
  {route:'anki/:deckId/study',entryPoint:'Deck card study action',type:'dynamic'},
  {route:'manga',entryPoint:'More Manga',type:'ui'},
  {route:'manga/study',entryPoint:'Manga saved words link',type:'ui'},
  {route:'manga/study/review',entryPoint:'Saved Manga words: review button',type:'ui'},
  {route:'manga/guide',entryPoint:'Manga how-to link',type:'ui'},
  {route:'manga/read/:volumeId',entryPoint:'Manga library volume read action',type:'dynamic'},
  {route:'grammar',entryPoint:'More Grammar',type:'ui'},
  {route:'grammar/review',entryPoint:'Grammar roadmap mixed practice',type:'ui'},
  {route:'grammar/n5/:topicId',entryPoint:'Grammar roadmap / sidebar',type:'dynamic'},
  {route:'grammar/n5/:topicId/:lessonId',entryPoint:'Grammar topic session / concept links',type:'dynamic'},
  {route:'grammar/n5/:topicId/practice',entryPoint:'Grammar lesson practice link / topic practice',type:'dynamic'},
];
