"""Publish audited pre-generated MP3 assets only; no synthesis or Angular build hook."""
import hashlib
import json
import shutil
from kokoro_audio import ROOT, vocabulary, eligibility_reason


def select_rows(entries, report, approvals):
    by_id = {entry['id']: entry for entry in entries}
    rows = {row['id']: row for row in report['rows']}
    if len(rows) != len(report['rows']) or not set(approvals) <= set(rows):
        raise ValueError('Duplicate audio IDs or unknown approval IDs')
    selected = []
    for id, row in sorted(rows.items()):
        entry = by_id.get(id)
        if not entry or eligibility_reason(entry['primaryReading']) or row['ttsInput'] != entry['primaryReading']:
            raise ValueError('Invalid source entry/reading: ' + id)
        if row['flags'] and id not in approvals:
            continue
        selected.append(row)
    return selected


def main():
    source = ROOT / '.cache/vocabulary-audio'
    report = json.loads((source/'report.json').read_text(encoding='utf-8'))
    approvals = json.loads((ROOT/'scripts/vocabulary-audio-approved.json').read_text(encoding='utf-8'))
    if not isinstance(approvals, list) or len(approvals) != len(set(approvals)):
        raise ValueError('Approvals must be a unique list of audited entry IDs')
    rows = select_rows(vocabulary(), report, approvals)
    target = ROOT/'public/audio/vocabulary/n5'
    target.mkdir(parents=True, exist_ok=True)
    expected = {row['id']+'.mp3' for row in rows}
    if {file.name for file in target.glob('*.mp3')} - expected:
        raise ValueError('Unexpected existing MP3 assets; review instead of silently deleting')
    for row in rows:
        file = source/'catalog'/f'{row["id"]}.mp3'
        if hashlib.sha256(file.read_bytes()).hexdigest() != row['sha256']:
            raise ValueError('Source audio hash mismatch: ' + row['id'])
        shutil.copyfile(file, target/file.name)
    manifest = {row['id']:f'audio/vocabulary/n5/{row["id"]}.mp3' for row in rows}
    payload = json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True)
    (target/'manifest.json').write_text(payload+'\n', encoding='utf-8')
    (target/'eligibility.json').write_text(json.dumps(dict(
        excluded=[entry['id'] for entry in report['exclusions']],
        pendingReview=[row['id'] for row in report['rows'] if row['flags'] and row['id'] not in approvals],
        approved=approvals, model=report['model'], revision=report['revision'], voice=report['voice'],
    ),indent=2,sort_keys=True)+'\n',encoding='utf-8')
    shutil.copyfile(source/'catalog/PROVENANCE.md', target/'PROVENANCE.md')
    (ROOT/'src/app/data/vocabulary-audio-manifest.generated.ts').write_text(
        '// Generated by scripts/export-vocabulary-audio.py; pre-generated approved audio only.\n'
        'export const VOCABULARY_AUDIO_MANIFEST: Readonly<Record<string,string>> = '+payload+';\n', encoding='utf-8')
    print(f'{len(rows)} MP3 assets; {sum(f.stat().st_size for f in target.iterdir())} bytes including metadata')


if __name__ == '__main__':
    main()
