import {addExperienceV2} from './grammar-n5-v2-experience.mjs';
import {addConnectionsV2} from './grammar-n5-v2-connections.mjs';
import {addInteractionV2} from './grammar-n5-v2-interaction.mjs';
import {addTeV2} from './grammar-n5-v2-te.mjs';
// Canonical, original Kana Study copy. Triplets are ES | EN | CA, never fallbacks.
// Editorial references are source-only; the PDF is not reproduced in the runtime.
import {addAdjectivesV2} from './grammar-n5-v2-adjectives.mjs';
import {addVerbsV2} from './grammar-n5-v2-verbs.mjs';
import {addLocationV2} from './grammar-n5-v2-location.mjs';
import {grammarKanaBank} from './grammar-kana-bank.mjs';
import {addClausesV2} from './grammar-n5-v2-clauses.mjs';
import {addPoliteV2} from './grammar-n5-v2-polite.mjs';
const tr = value => value.split('|');
const jp = value => [value,value,value];
export function buildGrammarV2() {
  const copy={es:{},en:{},ca:{}};
  const key=(id,value)=>{const k=`grammar.v2.${id}`;const texts=typeof value==='string'?tr(value):value;if(texts.length!==3)throw new Error(`Missing translation: ${id}`);['es','en','ca'].forEach((lang,i)=>copy[lang][k]=texts[i]);return k;};
  const ui={
    before:'Antes de empezar|Before you begin|Abans de començar',
    prerequisite:'Para estudiar la gramática necesitas poder leer hiragana y katakana básicos.|To study grammar, you need to be able to read basic hiragana and katakana.|Per estudiar gramàtica necessites poder llegir hiragana i katakana bàsics.',
    reminder:'Tres lecturas que encontrarás como partículas|Three readings you will encounter in particles|Tres lectures que trobaràs com a partícules',
    waReading:'は se pronuncia わ cuando funciona como partícula.|は is pronounced わ when used as a particle.|は es pronuncia わ quan funciona com a partícula.',
    heReading:'へ se pronuncia え cuando funciona como partícula.|へ is pronounced え when used as a particle.|へ es pronuncia え quan funciona com a partícula.',
    woReading:'を normalmente se pronuncia お como partícula.|を is usually pronounced お as a particle.|を normalment es pronuncia お com a partícula.',
    start:'Ya puedo leer kana → Empezar Tema 01|I can read kana → Start Topic 01|Ja puc llegir kana → Començar el Tema 01',
    optional:'Puedes continuar sin hacer ninguna prueba. Vuelve a practicar kana cuando lo necesites.|You can continue without taking a test. Return to kana practice whenever you need it.|Pots continuar sense fer cap prova. Torna a practicar kana quan ho necessitis.',
    topic:'La frase japonesa|The Japanese sentence|L’oració japonesa',
    topicGoal:'Entender el contexto, declarar estados y relacionar ideas con partículas.|Understand context, state what things are and connect ideas with particles.|Entendre el context, declarar estats i relacionar idees amb partícules.',
    goal:'🎯 Qué vas a aprender|🎯 What you will learn|🎯 Què aprendràs', idea:'💡 Idea esencial|💡 Essential idea|💡 Idea clau',
    formation:'🔧 Cómo se forma|🔧 How it is formed|🔧 Com es forma', examples:'例 Ejemplos|例 Examples|例 Exemples',
    mistakes:'⚠️ Errores frecuentes|⚠️ Common mistakes|⚠️ Errors freqüents', contrasts:'🔀 Comparación|🔀 Comparison|🔀 Comparació',
    details:'📘 Explicación detallada|📘 Detailed explanation|📘 Explicació detallada', practice:'🎯 Practicar|🎯 Practice|🎯 Practicar ara',
    detailWhy:'Por qué funciona|Why it works|Per què funciona', detailNuance:'Contexto y matices|Context and nuance|Context i matisos',
    pattern:'Estructura|Pattern|Estructura bàsica', review:'Práctica acumulativa del Tema 01|Topic 01 cumulative practice|Pràctica acumulativa del Tema 01',
    reviewBody:'Combina las formas nominales, las partículas y las familias de demostrativos en contextos nuevos.|Combine nominal forms, particles and demonstrative families in new contexts.|Combina les formes nominals, les partícules i les famílies de demostratius en contextos nous.',
    reviewTip:'Lee primero la situación|Read the situation first|Llegeix primer la situació',
    reviewHelp:'Distingue el significado que buscas de la validez gramatical. Dos frases pueden ser válidas y responder a preguntas diferentes.|Distinguish the intended meaning from grammatical validity. Two valid sentences may answer different questions.|Distingeix el significat que busques de la validesa gramatical. Dues frases poden ser vàlides i respondre a preguntes diferents.',
    nextTopic:'Continuar al Tema 02|Continue to Topic 02|Continuar al Tema 02: adjectius',
    identified:'Has identificado correctamente el error.|You have correctly identified the error.|Has identificat correctament l’error.',
    invalid:'❌ Construcción incorrecta|❌ Incorrect construction|❌ Construcció incorrecta', valid:'✔ Construcción válida|✔ Valid construction|✔ Construcció vàlida',
    errorTarget:'La construcción que debías identificar|The construction to identify|La construcció que havies d’identificar',
    choose:'Elige la respuesta para esta situación.|Choose the answer for this situation.|Tria la resposta per a aquesta situació.',
    detect:'Identifica la construcción incorrecta.|Identify the incorrect construction.|Identifica la construcció incorrecta.',
    fill:'Escribe la parte que falta.|Write the missing part.|Escriu la part que falta.',
    order:'Ordena los bloques para expresar la idea.|Arrange the blocks to express the idea.|Ordena els blocs per expressar la idea.',
    match:'Relaciona cada forma con su función.|Match each form to its function.|Relaciona cada forma amb la seva funció.',
    retry:'Reintentar los ejercicios pendientes|Retry the remaining exercises|Tornar a provar els exercicis pendents',
    pending:'Para completar este concepto, acierta al menos una vez cada ejercicio. Puedes corregir los fallos sin perder los aciertos.|To complete this concept, answer every exercise correctly at least once. You can correct mistakes without losing successful answers.|Per completar aquest concepte, encerta almenys una vegada cada exercici. Pots corregir els errors sense perdre els encerts.',
    nonpast:'No pasado|Non-past|No passat', past:'Pasado|Past|Passat', positive:'Afirmativo|Affirmative|Afirmatiu', negative:'Negativo|Negative|Negatiu',
    forms:'Tiempo y negación se combinan|Time and negation combine|El temps i la negació es combinen',
    family:'Familia|Family|Família', speaker:'Cerca de mí|Near me|A prop meu', listener:'Cerca de ti / contexto|Near you / context|A prop teu / context',
    far:'Lejos de ambos|Far from both|Lluny de tots dos', question:'Pregunta|Question|Interrogació', thing:'Cosa|Thing|Objecte', noun:'Con nombre|With a noun|Amb un nom', place:'Lugar|Place|Lloc',
    system:'Un sistema, tres familias|One system, three families|Un sistema amb tres famílies',
  };
  Object.entries(ui).forEach(([id,value])=>key(id,value));
  const K=id=>`grammar.v2.${id}`;
  const concepts=[];const editorialReferences={};
  const add=(id,title,goal,idea,patterns,examples,details,{mistakes=[],contrasts=[],prerequisites=[],sections=[],topicId='01'}={})=>{
    const prefix=id;
    const concept={id,level:'N5',track:'core',topicId,order:concepts.filter(c=>c.topicId===topicId).length+1,titleKey:key(`${prefix}.title`,title),summaryKey:key(`${prefix}.summary`,idea),goalKey:key(`${prefix}.goal`,goal),prerequisiteIds:prerequisites,relatedIds:[],lesson:{
      ideaKey:key(`${prefix}.idea`,idea),formation:patterns.map(pattern=>({labelKey:K('pattern'),pattern})),
      examples:examples.map(([japanese,reading,meaning],i)=>({japanese,reading,meaningKey:key(`${prefix}.example.${i}`,meaning)})),
      detailedExplanation:details.map((body,i)=>({id:i?'nuance':'why',titleKey:K(i?'detailNuance':'detailWhy'),bodyKey:key(`${prefix}.detail.${i}`,body)})),
      mistakes:mistakes.map(([wrong,correction,explanation],i)=>({wrong,correction,explanationKey:key(`${prefix}.mistake.${i}`,explanation)})),
      contrasts:contrasts.map(([left,right,explanation],i)=>({left,right,explanationKey:key(`${prefix}.contrast.${i}`,explanation)})),
    },exercises:[]};concepts.push(concept);editorialReferences[id]=[{source:'tae-kim',sections}];return concept;
  };
  add('sentence-structure-context','Cómo funciona una frase japonesa|How a Japanese sentence works|Com funciona una frase japonesa',
    'Interpretar una respuesta breve sin inventar un sujeto obligatorio.|Interpret a short answer without requiring an explicit subject.|Interpretar una resposta breu sense exigir un subjecte explícit.',
    'El contexto aporta lo que ya sabemos. El predicado suele cerrar la frase; no traduzcas palabra por palabra.|Context supplies what we already know. The predicate usually closes the sentence; avoid word-for-word translation.|El context aporta el que ja sabem. El predicat sol tancar la frase; evita traduir paraula per paraula.',
    ['学生 + だ → 学生だ。'],[['学生？ → 学生だ。','がくせい？ → がくせいだ。','¿Estudiante? → Es estudiante. La persona se entiende por el contexto.|A student? → A student. Context tells us who is meant.|Estudiant? → És estudiant. El context indica de qui parlem.']],
    ['Una conversación no empieza de cero en cada frase. Si ambos interlocutores saben de quién hablan, 学生だ basta para afirmar que esa persona es estudiante. La frase no especifica por sí sola yo, tú o él.|A conversation does not restart with each sentence. If both speakers know who they mean, 学生だ is enough to state that the person is a student. The sentence itself does not specify I, you or he.|Una conversa no comença de zero a cada frase. Si tots dos interlocutors saben de qui parlen, 学生だ basta per afirmar que aquella persona és estudiant. La frase no especifica per si sola jo, tu o ell.',
    'Omitir información conocida no significa omitir todo al azar. Si cambia la persona o aparece ambigüedad, hay que dar más información. En este bloque observaremos primero el cierre de la frase y después aprenderemos a presentar su tema.|Leaving out known information does not mean dropping words at random. If the person changes or ambiguity arises, provide more information. This block first examines sentence endings, then how to introduce a topic.|Ometre informació coneguda no vol dir eliminar paraules a l’atzar. Si canvia la persona o hi ha ambigüitat, cal donar més informació. Primer observarem el final de la frase i després aprendrem a presentar-ne el tema.'],{sections:['1.2','1.3','3.10.4']});
  add('state-being-plain','だ — Declarar qué es algo|だ — State what something is|だ — Declarar què és una cosa',
    'Construir declaraciones nominales simples y reconocer dónde no encaja だ.|Build simple nominal statements and recognise where だ does not fit.|Construir declaracions nominals simples i reconèixer on no encaixa だ.',
    'だ puede cerrar una declaración con un nombre o un adjetivo な. No es un equivalente obligatorio de «ser».|だ can close a statement with a noun or a な-adjective. It is not an obligatory equivalent of “be”.|だ pot tancar una declaració amb un nom o un adjectiu な. No és un equivalent obligatori de «ser».',
    ['名詞 + だ','元気 + だ → 元気だ。'],[['学生だ。','がくせいだ。','Es estudiante.|Is a student.|És estudiant.'],['先生だ。','せんせいだ。','Es docente.|Is a teacher.|És docent.'],['元気だ。','げんきだ。','Está bien / tiene energía.|Is well / energetic.|Es troba bé / té energia.'],['静かだ。','しずかだ。','Es tranquilo.|Is quiet.|És tranquil.']],
    ['学生 nombra una categoría; だ presenta la afirmación de forma explícita. En una charla informal, 学生。 también puede ser una respuesta completa si el contexto basta. No añadas だ solo porque tu traducción contiene «ser».|学生 names a category; だ makes the assertion explicit. In casual conversation, 学生。 can also be a complete answer when context is sufficient. Do not add だ simply because your translation contains “be”.|学生 anomena una categoria; だ fa explícita l’afirmació. En una conversa informal, 学生。 també pot ser una resposta completa si el context basta. No afegeixis だ només perquè la traducció conté «ser».',
    '元気 y 静か pertenecen al grupo な. かわいい pertenece al grupo い y no admite este だ final. Estudiaremos los adjetivos en el Tema 02. 学生です es válido, pero です tiene usos propios: no lo pegues a だ ni lo trates como un recambio universal. El sistema cortés llegará en el Tema 05.|元気 and 静か belong to the な group. かわいい belongs to the い group and does not take this final だ. Adjectives come in Topic 02. 学生です is valid, but です has its own uses: do not attach it to だ or treat it as a universal replacement. Polite forms come in Topic 05.|元気 i 静か pertanyen al grup な. かわいい pertany al grup い i no admet aquest だ final. Estudiarem els adjectius al Tema 02. 学生です és vàlid, però です té usos propis: no l’enganxis a だ ni el tractis com un recanvi universal. El sistema cortès arribarà al Tema 05.'],
    {prerequisites:['sentence-structure-context'],sections:['3.2','4.1.5'],mistakes:[['かわいいだ。','かわいい。','El adjetivo い ya puede cerrar esta frase.|The い-adjective can already close this sentence.|L’adjectiu い ja pot tancar aquesta frase.'],['学生だです。','学生だ。','No apiles だ y です. Aquí practicamos la declaración simple.|Do not stack だ and です. Here we practise a plain statement.|No apilis だ i です. Aquí practiquem la declaració simple.']]});
  add('state-being-negative','じゃない — Decir que algo no es|じゃない — Say what something is not|じゃない — Dir què no és una cosa',
    'Negar una categoría o un estado nominal.|Negate a category or nominal state.|Negar una categoria o un estat nominal.',
    'Para negar, el nombre va seguido de じゃない. No conservamos だ delante.|To negate, follow the noun with じゃない. Do not keep だ before it.|Per negar, el nom va seguit de じゃない. No conservem だ al davant.',
    ['名詞 + じゃない'],[['学生じゃない。','がくせいじゃない。','No es estudiante.|Is not a student.|No és estudiant.'],['先生じゃない。','せんせいじゃない。','No es docente.|Is not a teacher.|No és docent.'],['元気じゃない。','げんきじゃない。','No se encuentra bien.|Is not feeling well.|No es troba bé.']],
    ['La negación cambia la información que afirmas, no la persona de la que hablas. 学生だ y 学生じゃない pueden referirse a la misma persona, pero no dicen lo mismo.|Negation changes what you assert, not who you are talking about. 学生だ and 学生じゃない can refer to the same person but do not say the same thing.|La negació canvia el que afirmes, no la persona de qui parles. 学生だ i 学生じゃない poden referir-se a la mateixa persona, però no diuen el mateix.',
    'Si alguien supone que eres estudiante y no lo eres, 学生じゃない corrige esa suposición. Con 元気 funciona igual porque pertenece al grupo な. No extiendas automáticamente esta forma a todos los adjetivos o verbos.|If someone assumes you are a student and you are not, 学生じゃない corrects that assumption. 元気 follows the same pattern because it belongs to the な group. Do not automatically extend this form to all adjectives or verbs.|Si algú suposa que ets estudiant i no ho ets, 学生じゃない corregeix aquella suposició. Amb 元気 funciona igual perquè pertany al grup な. No estenguis automàticament aquesta forma a tots els adjectius o verbs.'],
    {prerequisites:['state-being-plain'],sections:['3.2'],mistakes:[['学生だじゃない。','学生じゃない。','じゃない sustituye el cierre afirmativo; no se añade después de だ.|じゃない replaces the affirmative ending; it is not added after だ.|じゃない substitueix el final afirmatiu; no s’afegeix després de だ.']],contrasts:[['学生だ。','学生じゃない。','Afirmar y negar la misma categoría.|Affirming and denying the same category.|Afirmar i negar la mateixa categoria.']]});
  add('state-being-past','だった — Decir qué era algo|だった — Say what something was|だった — Dir què era una cosa',
    'Situar una afirmación nominal en el pasado.|Place a nominal statement in the past.|Situar una afirmació nominal en el passat.',
    'だった presenta el estado como pasado. La っ pequeña forma parte de la terminación.|だった presents a state as past. The small っ is part of the ending.|だった presenta l’estat com a passat. La っ petita forma part de la terminació.',
    ['名詞 + だった'],[['学生だった。','がくせいだった。','Era estudiante.|Was a student.|Era estudiant.'],['先生だった。','せんせいだった。','Era docente.|Was a teacher.|Era docent.'],['元気だった。','げんきだった。','Se encontraba bien.|Was feeling well.|Es trobava bé.']],
    ['Con 学生だった sitúas la descripción en una etapa anterior. No hace falta añadir una palabra equivalente a «era»: la terminación ya aporta ese tiempo.|With 学生だった you place the description in an earlier period. There is no need to add another word meaning “was”: the ending already supplies the tense.|Amb 学生だった situes la descripció en una etapa anterior. No cal afegir una altra paraula equivalent a «era»: la terminació ja aporta aquest temps.',
    'Hablar del pasado no demuestra por sí solo cómo es la situación ahora. El contexto puede aclararlo. Escribe だった con っ pequeña: だた no es esta forma.|Talking about the past does not by itself establish the situation now. Context can clarify it. Write だった with small っ: だた is not this form.|Parlar del passat no demostra per si sol com és la situació ara. El context pot aclarir-ho. Escriu だった amb っ petita: だた no és aquesta forma.'],
    {prerequisites:['state-being-plain'],sections:['3.2'],mistakes:[['学生だた。','学生だった。','Falta la っ pequeña de だった.|The small っ in だった is missing.|Falta la っ petita de だった.']]});
  add('state-being-past-negative','じゃなかった — Decir qué no era algo|じゃなかった — Say what something was not|じゃなかった — Dir què no era una cosa',
    'Combinar pasado y negación sin confundirlos.|Combine past tense and negation without confusing them.|Combinar passat i negació sense confondre’ls.',
    'じゃない pasa a じゃなかった. Tiempo y negación son dos decisiones que puedes combinar.|じゃない becomes じゃなかった. Time and negation are two choices you can combine.|じゃない passa a じゃなかった. El temps i la negació són dues decisions que pots combinar.',
    ['じゃない → じゃなかった'],[['学生じゃなかった。','がくせいじゃなかった。','No era estudiante.|Was not a student.|No era estudiant.'],['元気じゃなかった。','げんきじゃなかった。','No se encontraba bien.|Was not feeling well.|No es trobava bé.']],
    ['Primero decide si afirmas o niegas; después sitúa el estado en el tiempo. Para negar un estado pasado, cambia la い final de じゃない por かった. No unas だった y じゃない.|First decide whether you affirm or negate, then place the state in time. To negate a past state, replace the final い of じゃない with かった. Do not join だった and じゃない.|Primer decideix si afirmes o negues; després situa l’estat en el temps. Per negar un estat passat, canvia la い final de じゃない per かった. No uneixis だった i じゃない.',
    'Las cuatro formas de la tabla son japonés válido. Elegir la equivocada para una situación cambia el significado: no convierte automáticamente la frase en agramatical. «No pasado» incluye usos presentes y otros que dependen del contexto.|All four forms in the table are valid Japanese. Choosing the wrong one for a situation changes the meaning; it does not automatically make the sentence ungrammatical. “Non-past” includes present uses and others determined by context.|Les quatre formes de la taula són japonès vàlid. Triar-ne una d’inadequada per a una situació canvia el significat; no converteix automàticament la frase en agramatical. «No passat» inclou usos presents i altres que depenen del context.'],
    {prerequisites:['state-being-negative','state-being-past'],sections:['3.2']});
  concepts.at(-1).lesson.tables=[{captionKey:K('forms'),headerKeys:[K('positive'),K('negative')],rows:[{labelKey:K('nonpast'),cells:['学生だ','学生じゃない']},{labelKey:K('past'),cells:['学生だった','学生じゃなかった']}]}];
  add('particle-wa-topic','は — De qué estamos hablando|は — What we are talking about|は — De què estem parlant',
    'Presentar un tema y separar el tema de la información.|Introduce a topic and distinguish it from the information about it.|Presentar un tema i separar-lo de la informació.',
    'は marca el tema sobre el que damos información. Como partícula se lee わ.|は marks the topic we give information about. As a particle it is read わ.|は marca el tema sobre el qual donem informació. Com a partícula es llegeix わ.',
    ['田中さん は ｜ 学生だ'],[['田中さんは学生だ。','たなかさんはがくせいだ。','Hablando de Tanaka, es estudiante.|As for Tanaka, they are a student.|Parlant de Tanaka, és estudiant.'],['田中さんは学生？ → 学生だ。','たなかさんはがくせい？ → がくせいだ。','¿Tanaka es estudiante? → Sí, es estudiante; no hace falta repetir el tema.|Is Tanaka a student? → A student, yes; the topic need not be repeated.|Tanaka és estudiant? → Sí, és estudiant; no cal repetir el tema.']],
    ['Piensa en は como el marco de la información que viene después. En 田中さんは学生だ, 田中さん es el tema y 学生だ lo que comunicamos sobre él. は no significa «ser».|Think of は as the frame for the information that follows. In 田中さんは学生だ, 田中さん is the topic and 学生だ is what we communicate about them. は does not mean “be”.|Pensa en は com el marc de la informació que ve després. A 田中さんは学生だ, 田中さん és el tema i 学生だ és el que comuniquem sobre aquesta persona. は no significa «ser».',
    'Tema y sujeto no son etiquetas intercambiables en todas las frases. Este ejemplo puede parecer sencillo de traducir, pero la función de は es organizar de qué hablamos. Una vez fijado el tema, una respuesta puede omitirlo.|Topic and subject are not interchangeable labels in every sentence. This example may seem easy to translate, but は organises what we talk about. Once the topic is established, an answer can leave it out.|Tema i subjecte no són etiquetes intercanviables a totes les frases. Aquest exemple pot semblar fàcil de traduir, però は organitza de què parlem. Un cop fixat el tema, una resposta pot ometre’l.'],{prerequisites:['sentence-structure-context','state-being-plain'],sections:['3.3']});
  add('particle-mo-inclusive','も — También|も — Also|も — També',
    'Añadir otro elemento al que se aplica la misma información.|Add another item to which the same information applies.|Afegir un altre element al qual s’aplica la mateixa informació.',
    'も incluye otro elemento en una afirmación ya establecida. En este patrón ocupa el lugar de は.|も includes another item in an established statement. In this pattern it takes the place of は.|も inclou un altre element en una afirmació ja establerta. En aquest patró ocupa el lloc de は.',
    ['私は学生だ。 → 私も学生だ。'],[['田中さんは学生だ。山田さんも学生だ。','たなかさんはがくせいだ。やまださんもがくせいだ。','Tanaka es estudiante. Yamada también.|Tanaka is a student. Yamada is too.|Tanaka és estudiant. Yamada també.']],
    ['La idea de «también» necesita algo con lo que coincidir. En el ejemplo, ambas personas son estudiantes. Si solo quieres presentar a Yamada sin añadirlo a una información compartida, も no expresa esa intención.|“Also” needs something to match. In the example, both people are students. If you only want to introduce Yamada without adding them to shared information, も does not express that intention.|La idea de «també» necessita alguna cosa amb què coincidir. A l’exemple, totes dues persones són estudiants. Si només vols presentar Yamada sense afegir-lo a una informació compartida, も no expressa aquesta intenció.',
    'También se puede compartir una negación: 田中さんも学生じゃない añade a Tanaka al grupo de quienes no son estudiantes. Debe coincidir la información relevante, no solo aparecer la misma palabra.|A negative statement can be shared too: 田中さんも学生じゃない adds Tanaka to those who are not students. The relevant information must match; repeating a word is not enough.|També es pot compartir una negació: 田中さんも学生じゃない afegeix Tanaka al grup dels qui no són estudiants. Ha de coincidir la informació rellevant, no només una paraula.'],
    {prerequisites:['particle-wa-topic','state-being-negative'],sections:['3.3'],mistakes:[['私はも学生だ。','私も学生だ。','En este patrón も reemplaza は; no se acumulan.|In this pattern も replaces は; they do not stack.|En aquest patró も substitueix は; no s’acumulen.']]});
  add('particle-ga-identifier','が — Identificar quién o qué|が — Identify who or what|が — Identificar qui o què',
    'Responder a una búsqueda de identidad usando が.|Answer a question of identity using が.|Respondre a una cerca d’identitat amb が.',
    'が ayuda a identificar el elemento que cumple la descripción. 誰 significa «quién».|が helps identify the item that fits the description. 誰 means “who”.|が ajuda a identificar l’element que compleix la descripció. 誰 significa «qui».',
    ['誰 が 学生？ → 田中さん が 学生だ。'],[['誰が先生？ → 山田さんが先生だ。','だれがせんせい？ → やまださんがせんせいだ。','¿Quién es docente? → Yamada es quien lo es.|Who is a teacher? → Yamada is the one.|Qui és docent? → Yamada és qui ho és.']],
    ['En 誰が学生？ aún buscamos la persona. La respuesta 田中さんが学生だ coloca a Tanaka en ese hueco de identidad. No necesitamos traducir が por una palabra fija para entender lo que hace.|In 誰が学生？ we are still looking for the person. The answer 田中さんが学生だ fills that identity slot with Tanaka. We do not need a fixed word-for-word translation of が to understand its role.|A 誰が学生？ encara busquem la persona. La resposta 田中さんが学生だ omple aquest espai d’identitat amb Tanaka. No necessitem traduir が per una paraula fixa per entendre’n la funció.',
    'Este es un primer uso de が, no una definición exhaustiva. Más adelante lo encontrarás con existencia, gustos y capacidad. Memorizar solo «が = sujeto» no explica por qué elegimos esta partícula en este diálogo.|This is a first use of が, not an exhaustive definition. Later you will encounter it with existence, preferences and ability. Memorising only “が = subject” does not explain why we choose it in this dialogue.|Aquest és un primer ús de が, no una definició exhaustiva. Més endavant el trobaràs amb existència, gustos i capacitat. Memoritzar només «が = subjecte» no explica per què triem aquesta partícula en aquest diàleg.'],{prerequisites:['particle-wa-topic'],sections:['3.3']});
  add('particle-wa-vs-ga','は y が — Tema frente a identificación|は and が — Topic versus identification|は i が — Tema i identificació',
    'Elegir según qué información aporta la frase al diálogo.|Choose according to what information the sentence adds to the dialogue.|Triar segons quina informació aporta la frase al diàleg.',
    'は → «en cuanto a…». が → «el que / lo que…». Es un modelo inicial, no una traducción literal.|は → “as for…”. が → “the one / thing that…”. This is an initial model, not a literal translation.|は → «pel que fa a…». が → «qui / allò que…». És un model inicial, no una traducció literal.',
    [],[['田中さんは学生だ。','たなかさんはがくせいだ。','Sobre Tanaka, damos la información de que es estudiante.|About Tanaka, we give the information that they are a student.|Sobre Tanaka, donem la informació que és estudiant.'],['誰が学生？ → 田中さんが学生だ。','だれががくせい？ → たなかさんががくせいだ。','Buscamos quién; identificamos a Tanaka.|We ask who; we identify Tanaka.|Busquem qui; identifiquem Tanaka.']],
    ['Con は partimos de un tema para decir algo sobre él. Con el uso de が que practicamos, identificamos quién encaja en la descripción. El contexto decide qué información necesitamos destacar.|With は we start from a topic and say something about it. In the use of が practised here, we identify who fits a description. Context determines what information needs highlighting.|Amb は partim d’un tema per dir-ne alguna cosa. Amb l’ús de が que practiquem, identifiquem qui encaixa en la descripció. El context decideix quina informació cal destacar.',
    '田中さんは学生だ y 田中さんが学生だ son frases válidas. No conviertas una preferencia de contexto en una prohibición universal. Los ejercicios indican si buscamos presentar un tema o identificar a alguien; las sutilezas se ampliarán más adelante.|田中さんは学生だ and 田中さんが学生だ are both valid sentences. Do not turn a contextual preference into a universal ban. Exercises specify whether we introduce a topic or identify someone; finer distinctions come later.|田中さんは学生だ i 田中さんが学生だ són frases vàlides. No converteixis una preferència contextual en una prohibició universal. Els exercicis indiquen si presentem un tema o identifiquem algú; els matisos s’ampliaran més endavant.'],
    {prerequisites:['particle-wa-topic','particle-ga-identifier'],sections:['3.3'],contrasts:[['田中さんは学生だ。','田中さんが学生だ。','Misma persona y categoría; cambia cómo organizamos la información.|Same person and category; the information is organised differently.|Mateixa persona i categoria; canvia com organitzem la informació.']]});
  add('particle-no-noun-link','の — Relacionar nombres|の — Connect nouns|の — Relacionar noms',
    'Reconocer el nombre principal y el que lo especifica.|Recognise the head noun and the noun that specifies it.|Reconèixer el nom principal i el que l’especifica.',
    'En A の B, A especifica o relaciona a B. B es el núcleo; la relación no siempre es posesión.|In A の B, A specifies or relates to B. B is the head; the relationship is not always ownership.|A A の B, A especifica o es relaciona amb B. B és el nucli; la relació no sempre és possessió.',
    ['A の B'],[['ゆきさんの本','ゆきさんのほん','El libro de Yuki.|Yuki’s book.|El llibre de Yuki.'],['日本の車','にほんのくるま','Un coche de Japón.|A car from Japan.|Un cotxe del Japó.'],['日本語の先生','にほんごのせんせい','Docente de japonés.|A Japanese-language teacher.|Docent de japonès.']],
    ['Empieza por el final: 日本語の先生 habla de un docente, y 日本語 indica su especialidad. No significa que el idioma sea dueño de la persona. Con ゆきさんの本, la relación sí puede ser de pertenencia.|Start at the end: 日本語の先生 refers to a teacher, and 日本語 specifies their subject. It does not mean the language owns the person. With ゆきさんの本, the relationship can be ownership.|Comença pel final: 日本語の先生 parla d’un docent, i 日本語 n’indica l’especialitat. No significa que la llengua sigui propietària de la persona. Amb ゆきさんの本, la relació sí que pot ser de pertinença.',
    'Cambiar el orden cambia el núcleo. La secuencia que modifica va antes del nombre principal, aunque tu traducción la coloque después. Aquí estudiamos solo の entre nombres; sus otros usos vendrán después.|Changing the order changes the head. The modifying phrase comes before the main noun, even if your translation puts it after. Here we study only の between nouns; other uses come later.|Canviar l’ordre canvia el nucli. La seqüència que modifica va abans del nom principal, encara que la traducció la posi després. Aquí estudiem només の entre noms; els altres usos vindran més endavant.'],{prerequisites:['state-being-plain'],sections:['3.11.4']});
  add('demonstratives-ko-so-a-do','こ・そ・あ・ど — Señalar cosas y lugares|こ・そ・あ・ど — Point to things and places|こ・そ・あ・ど — Assenyalar coses i llocs',
    'Combinar distancia o contexto con la familia que necesita la frase.|Combine distance or context with the family the sentence needs.|Combinar distància o context amb la família que necessita la frase.',
    'Primero elige こ・そ・あ・ど; después decide si señalas una cosa, acompañas un nombre o indicas un lugar.|First choose こ・そ・あ・ど; then decide whether you point to a thing, accompany a noun or indicate a place.|Primer tria こ・そ・あ・ど; després decideix si assenyales una cosa, acompanyes un nom o indiques un lloc.',
    ['これ → これは本だ。','この + 本 → この本'],[['これは本だ。','これはほんだ。','Esto es un libro.|This is a book.|Això és un llibre.'],['この本','このほん','Este libro, cerca de quien habla.|This book, near the speaker.|Aquest llibre, a prop de qui parla.'],['ここ','ここ','Aquí, junto a quien habla.|Here, near the speaker.|Aquí, al costat de qui parla.']],
    ['これ funciona como un pronombre: puede ocupar el lugar de una cosa. この no sustituye al nombre, lo acompaña: この本. Para lugares usamos otra fila: ここ, そこ, あそこ y どこ. Aprende las filas como combinaciones de una misma idea.|これ acts as a pronoun: it can stand for a thing. この does not replace the noun; it accompanies it: この本. For places we use another row: ここ, そこ, あそこ and どこ. Learn the rows as combinations of one idea.|これ funciona com un pronom: pot ocupar el lloc d’una cosa. この no substitueix el nom, l’acompanya: この本. Per als llocs usem una altra fila: ここ, そこ, あそこ i どこ. Aprèn les files com a combinacions d’una mateixa idea.',
    'Para empezar, relaciona こ con quien habla, そ con el lado o contexto del oyente y あ con algo alejado de ambos. ど pregunta por la opción. そ también puede recuperar información de la conversación: no es una regla exclusivamente espacial.|To begin, connect こ with the speaker, そ with the listener’s side or context, and あ with something far from both. ど asks which option. そ can also refer back to information in conversation: the rule is not purely spatial.|Per començar, relaciona こ amb qui parla, そ amb el costat o context de l’oient i あ amb una cosa allunyada de tots dos. ど pregunta per l’opció. そ també pot recuperar informació de la conversa: no és una regla exclusivament espacial.'],
    {prerequisites:['particle-wa-topic','particle-no-noun-link'],mistakes:[['これ本','この本','Para acompañar directamente a 本 necesitas この, no el pronombre これ.|To accompany 本 directly, use この, not the pronoun これ.|Per acompanyar directament 本 necessites この, no el pronom これ.']]});
  concepts.at(-1).lesson.tables=[{captionKey:K('system'),headerKeys:[K('speaker'),K('listener'),K('far'),K('question')],rows:[{labelKey:K('thing'),cells:['これ','それ','あれ','どれ']},{labelKey:K('noun'),cells:['この','その','あの','どの']},{labelKey:K('place'),cells:['ここ','そこ','あそこ','どこ']}]}];
  concepts.forEach(c=>c.relatedIds=concepts.filter(other=>other.prerequisiteIds.includes(c.id)).map(other=>other.id));

  // Exercises are authored below. Every option carries its own explanation.
  const review=[];
  let current=concepts[0];let reviewing=false;
  const use=index=>{current=concepts[index];};
  const base=(kind,skill,prompt,explanation)=>{
    const number=reviewing?review.filter(e=>e.topicId===current.topicId).length+1:current.exercises.length+1;
    const id=reviewing?`topic${current.topicId}-review-${String(number).padStart(2,'0')}`:`${current.id}-${number}`;
    return {id,version:2,kind,skill,difficulty:reviewing?3:skill==='recognition'?1:2,topicId:current.topicId,lessonId:current.id,conceptId:current.id,
      labelKey:K('practice'),topicKey:K(current.topicId==='01'?'topic':`topic${current.topicId}`),questionKey:K(kind==='detect-error'?'detect':kind==='fill-gap'?'fill':kind==='matching'?'match':kind==='sentence-order'||kind==='sentence-builder'?'order':'choose'),promptKey:key(`${id}.prompt`,prompt),successKey:key(`${id}.explanation`,explanation),errorKey:K(`${id}.explanation`)};
  };
  const push=e=>(reviewing?review:current.exercises).push(e);
  const choice=(skill,prompt,options,answer,explanation,kind='multiple-choice')=>{
    const e=base(kind,skill,prompt,explanation);
    e.options=options.map(([text,feedback,status],i)=>({id:`${e.id}-option-${i}`,textKey:key(`${e.id}.option.${i}`,text),feedbackKey:key(`${e.id}.feedback.${i}`,feedback),...(status?{grammarStatus:status}:{})}));
    e.optionKeys=e.options.map(o=>o.textKey);e.answer=answer;push(e);
  };
  const fill=(prompt,answer,explanation)=>{const e=base('fill-gap','formation',prompt,explanation),answers=Array.isArray(answer)?answer:[answer];push({...e,acceptedAnswers:answers,solutionKey:key(`${e.id}.solution`,jp(answers[0])),kanaBank:grammarKanaBank(e.id,answers)});};
  const order=(prompt,tokens,solution,explanation,kind='sentence-order')=>{const e=base(kind,'ordering',prompt,explanation);push({...e,tokenKeys:tokens.map((t,i)=>key(`${e.id}.token.${i}`,jp(t))),solution,orderPolicy:'constrained'});};
  const matching=(prompt,pairs,explanation)=>{const e=base('matching','recognition',prompt,explanation);push({...e,pairs:pairs.map(([left,right],i)=>({leftKey:key(`${e.id}.left.${i}`,jp(left)),rightKey:key(`${e.id}.right.${i}`,right)}))});};
  const valid=(text,feedback)=>[jp(text),feedback,'valid'];
  const invalid=(text,feedback)=>[jp(text),feedback,'invalid'];
  const stateOptions=n=>[
    valid(`${n}だ。`,'Es una afirmación no pasada.|This is a non-past affirmative statement.|És una afirmació no passada.'),
    valid(`${n}じゃない。`,'Niega el estado sin situarlo en el pasado.|This denies the state without placing it in the past.|Nega l’estat sense situar-lo en el passat.'),
    valid(`${n}だった。`,'Afirma que ese era el estado en el pasado.|This affirms that it was the state in the past.|Afirma que aquell era l’estat en el passat.'),
    valid(`${n}じゃなかった。`,'Combina pasado y negación: no era así.|This combines past and negation: it was not so.|Combina passat i negació: no era així.')];
  const particles=[
    valid('は','は presenta un tema; no añade por sí solo «también» ni identifica la respuesta a 誰.|は introduces a topic; it does not by itself add “also” or identify the answer to 誰.|は presenta un tema; no afegeix per si sol «també» ni identifica la resposta a 誰.'),
    valid('も','も añade un elemento al que se aplica la misma información previa.|も adds an item to which the same preceding information applies.|も afegeix un element al qual s’aplica la mateixa informació prèvia.'),
    valid('が','が señala aquí quién encaja en la descripción buscada.|が indicates here who fits the description being sought.|が assenyala aquí qui encaixa en la descripció buscada.')];
  const omission='Si la persona ya está clara, no hace falta repetirla.|If the person is already clear, there is no need to repeat them.|Si la persona ja és clara, no cal repetir-la.';
  const predicate='学生 aporta la categoría y だ cierra la declaración.|学生 supplies the category and だ closes the statement.|学生 aporta la categoria i だ tanca la declaració.';
  choice('recognition','Dos amigos ya hablan de Yuki. ¿Qué puede omitirse al decir que es estudiante?|Two friends are already talking about Yuki. What can be omitted when saying they are a student?|Dos amics ja parlen de Yuki. Què es pot ometre en dir que és estudiant?',[
    ['El nombre de Yuki|Yuki’s name|El nom de Yuki',omission],['Siempre la información nueva «estudiante»|Always the new information “student”|Sempre la informació nova «estudiant»','La categoría es precisamente lo que queremos comunicar.|The category is precisely what we want to communicate.|La categoria és precisament el que volem comunicar.'],['Nada: siempre hay que decir yo/tú/él|Nothing: I/you/he must always be stated|Res: sempre cal dir jo/tu/ell','El japonés permite recuperar información del contexto.|Japanese allows information to be recovered from context.|El japonès permet recuperar informació del context.']],0,omission);
  choice('usage','Una amiga pregunta por Yuki: 学生？ Respondes 学生だ。 ¿De quién hablas?|A friend asks about Yuki: 学生？ You answer 学生だ。 Who do you mean?|Una amiga pregunta per Yuki: 学生？ Respons 学生だ。 De qui parles?',[
    ['De Yuki, por el contexto|Yuki, from context|De Yuki, pel context',omission],['Necesariamente de mí|Necessarily myself|Necessàriament de mi','No aparece una palabra que obligue a interpretar «yo».|No word requires an interpretation of “I”.|No hi ha cap paraula que obligui a interpretar «jo».'],['De toda persona|Every person|De tota persona','El diálogo trata de una persona concreta.|The dialogue concerns one particular person.|El diàleg tracta d’una persona concreta.']],0,omission);
  order('Forma una declaración: «Es estudiante».|Build a statement: “Is a student”.|Forma una declaració: «És estudiant».',['だ','学生'],[1,0],predicate);
  choice('usage','Ya saben de quién hablas. Elige una declaración nominal completa y natural.|They already know who you mean. Choose a complete, natural nominal statement.|Ja saben de qui parles. Tria una declaració nominal completa i natural.',[
    valid('学生だ。',predicate),invalid('だ学生。','El cierre だ va después de 学生.|The ending だ follows 学生.|El final だ va després de 学生.')],0,predicate);
  use(1);
  choice('recognition','¿Qué expresa 先生だ。?|What does 先生だ。 express?|Què expressa 先生だ。?',[
    ['Es docente.|Is a teacher.|És docent.',predicate],['No es docente.|Is not a teacher.|No és docent.','No hay negación en esta terminación.|There is no negation in this ending.|No hi ha negació en aquesta terminació.'],['Era docente.|Was a teacher.|Era docent.','El pasado nominal lleva だった, no だ.|The nominal past uses だった, not だ.|El passat nominal porta だった, no だ.']],0,'だ declara un estado no pasado.|だ states a non-past state.|だ declara un estat no passat.');
  fill('Completa la declaración simple: 学生＿。|Complete the plain statement: 学生＿。|Completa la declaració simple: 学生＿。','だ',predicate);
  choice('usage','En una conversación informal, ¿puede 学生。 ser una respuesta suficiente?|In casual conversation, can 学生。 be a sufficient answer?|En una conversa informal, pot 学生。 ser una resposta suficient?',[
    ['Sí, si el contexto aclara de quién se habla.|Yes, if context makes the person clear.|Sí, si el context aclareix de qui es parla.',omission],['No: siempre falta el equivalente de «ser».|No: an equivalent of “be” is always missing.|No: sempre hi falta l’equivalent de «ser».','だ no es obligatorio en toda respuesta nominal casual.|だ is not obligatory in every casual nominal answer.|だ no és obligatori en tota resposta nominal informal.']],0,omission);
  choice('error-detection','Selecciona la frase que apila dos cierres incompatibles.|Select the sentence that stacks two incompatible endings.|Selecciona la frase que apila dos finals incompatibles.',[
    valid('学生だ。','Esta declaración simple es válida.|This plain statement is valid.|Aquesta declaració simple és vàlida.'),
    invalid('学生だです。','Has encontrado la combinación incorrecta: だ y です no se apilan. Usa 学生だ。; 学生です。 también es válido y se estudiará más adelante.|You found the incorrect combination: だ and です do not stack. Use 学生だ。; 学生です。 is also valid and will be studied later.|Has trobat la combinació incorrecta: だ i です no s’apilen. Fes servir 学生だ。; 学生です。 també és vàlid i s’estudiarà més endavant.'),
    valid('学生です。','Es una forma válida que estudiarás en el Tema 05. No es la combinación incorrecta.|This is a valid form you will study in Topic 05. It is not the incorrect combination.|És una forma vàlida que estudiaràs al Tema 05. No és la combinació incorrecta.')],1,'No confundas identificar un error con aprenderlo como modelo correcto.|Do not confuse identifying an error with learning it as a correct model.|No confonguis identificar un error amb aprendre’l com a model correcte.','detect-error');
  choice('formation','¿Qué palabra admite directamente だ en este patrón?|Which word directly takes だ in this pattern?|Quina paraula admet directament だ en aquest patró?',[
    [jp('元気'),'元気 pertenece al grupo な: 元気だ.|元気 belongs to the な group: 元気だ.|元気 pertany al grup な: 元気だ.'],[jp('かわいい'),'かわいい pertenece al grupo い: かわいいだ no es válido.|かわいい belongs to the い group: かわいいだ is not valid.|かわいい pertany al grup い: かわいいだ no és vàlid.']],0,'El grupo de la palabra importa; no añadas だ a cualquier descripción.|The word’s group matters; do not add だ to every description.|El grup de la paraula importa; no afegeixis だ a qualsevol descripció.');
  use(2);
  choice('recognition','Elige «No es docente».|Choose “Is not a teacher”.|Tria «No és docent».',stateOptions('先生').slice(0,2),1,'La negación no pasada es じゃない.|The non-past negative is じゃない.|La negació no passada és じゃない.');
  fill('Cambia a negativo: 学生だ → 学生＿。|Change to negative: 学生だ → 学生＿。|Canvia a negatiu: 学生だ → 学生＿。','じゃない','Retira だ y usa じゃない.|Remove だ and use じゃない.|Treu だ i fes servir じゃない.');
  choice('usage','Creen que estás bien, pero quieres negar ese estado ahora. Elige la respuesta.|They think you are well, but you want to deny that state now. Choose the reply.|Creuen que et trobes bé, però vols negar aquest estat ara. Tria la resposta.',stateOptions('元気').slice(0,2),1,'元気じゃない niega que te encuentres bien.|元気じゃない denies that you are well.|元気じゃない nega que et trobis bé.');
  choice('error-detection','Busca la negación mal formada.|Find the malformed negative.|Busca la negació mal formada.',[
    valid('学生じゃない。','じゃない sigue directamente al nombre.|じゃない directly follows the noun.|じゃない segueix directament el nom.'),invalid('学生だじゃない。','Sobra だ: escribe 学生じゃない。|だ is extra: write 学生じゃない。|Sobra だ: escriu 学生じゃない。'),valid('先生じゃない。','先生 también admite じゃない.|先生 also takes じゃない.|先生 també admet じゃない.')],1,'La negación reemplaza el cierre afirmativo.|The negative replaces the affirmative ending.|La negació substitueix el final afirmatiu.','detect-error');
  matching('Relaciona afirmación y negación.|Match affirmation and negation.|Relaciona afirmació i negació.',[['学生だ','Es estudiante.|Is a student.|És estudiant.'],['学生じゃない','No es estudiante.|Is not a student.|No és estudiant.']],'Observa la terminación, no solo el nombre repetido.|Look at the ending, not just the repeated noun.|Observa la terminació, no només el nom repetit.');
  use(3);
  choice('recognition','Elige «Era estudiante».|Choose “Was a student”.|Tria «Era estudiant».',stateOptions('学生').slice(0,3),2,'だった sitúa la afirmación en el pasado.|だった places the statement in the past.|だった situa l’afirmació en el passat.');
  fill('Transforma al pasado: 先生だ → 先生＿。|Change to past: 先生だ → 先生＿。|Transforma al passat: 先生だ → 先生＿。','だった','Conserva el nombre y usa だった, con っ pequeña.|Keep the noun and use だった, with small っ.|Conserva el nom i fes servir だった, amb っ petita.');
  choice('usage','Hablas de cómo te encontrabas ayer: estabas bien. Elige la forma.|You describe how you felt yesterday: you were well. Choose the form.|Parles de com et trobaves ahir: estaves bé. Tria la forma.',stateOptions('元気').slice(0,3),2,'El contexto pide pasado afirmativo.|The context requires a past affirmative.|El context demana passat afirmatiu.');
  choice('error-detection','¿Qué forma de pasado está mal escrita?|Which past form is misspelled?|Quina forma de passat està mal escrita?',[
    valid('先生だった。','Contiene la terminación completa だった.|It contains the full ending だった.|Conté la terminació completa だった.'),invalid('学生だた。','Falta っ: la forma es 学生だった。|っ is missing: the form is 学生だった。|Falta っ: la forma és 学生だった。'),valid('元気だった。','元気 admite este pasado con だった.|元気 takes this past form with だった.|元気 admet aquest passat amb だった.')],1,'La escritura de だった incluye una pausa consonántica marcada por っ.|The spelling of だった includes the consonant pause marked by っ.|L’escriptura de だった inclou una pausa consonàntica marcada per っ.','detect-error');
  use(4);
  choice('recognition','Elige «No era estudiante».|Choose “Was not a student”.|Tria «No era estudiant».',stateOptions('学生'),3,'Necesitas pasado y negación a la vez.|You need past tense and negation together.|Necessites passat i negació alhora.');
  fill('Lleva al pasado: 先生じゃない → 先生＿。|Put into the past: 先生じゃない → 先生＿。|Porta al passat: 先生じゃない → 先生＿。','じゃなかった','La い de じゃない cambia a かった.|The い in じゃない changes to かった.|La い de じゃない canvia a かった.');
  choice('contrast','Hoy no te encuentras bien. Sin hablar del pasado, ¿qué forma eliges?|You are not well today. Without referring to the past, which form do you choose?|Avui no et trobes bé. Sense parlar del passat, quina forma tries?',stateOptions('元気'),1,'Aquí solo necesitas negación, no pasado.|Here you need negation only, not past tense.|Aquí només necessites negació, no passat.');
  choice('usage','En aquella época no eras docente. Elige la descripción.|At that time you were not a teacher. Choose the description.|En aquella època no eres docent. Tria la descripció.',stateOptions('先生'),3,'じゃなかった combina los dos rasgos solicitados.|じゃなかった combines the two requested features.|じゃなかった combina els dos trets demanats.');
  matching('Relaciona las cuatro formas de 学生.|Match the four forms of 学生.|Relaciona les quatre formes de 学生.',[['学生だ','Afirmativo no pasado|Non-past affirmative|Afirmatiu no passat'],['学生じゃない','Negativo no pasado|Non-past negative|Negatiu no passat'],['学生だった','Afirmativo pasado|Past affirmative|Afirmatiu passat'],['学生じゃなかった','Negativo pasado|Past negative|Negatiu passat']],'Tiempo y polaridad son dos ejes independientes.|Time and polarity are two independent axes.|Temps i polaritat són dos eixos independents.');
  use(5);
  choice('recognition','En 田中さんは学生だ, selecciona la partícula que marca el tema.|In 田中さんは学生だ, select the topic particle.|A 田中さんは学生だ, selecciona la partícula que marca el tema.',[
    [jp('田中さん'),'Es el tema, pero no es la partícula.|This is the topic, but not the particle.|És el tema, però no és la partícula.'],[jp('は'),'は marca el tema anterior.|は marks the preceding topic.|は assenyala el tema que el precedeix.'],[jp('学生だ'),'Es la información sobre el tema.|This is the information about the topic.|És la informació sobre el tema.']],1,'La partícula va después del elemento que marca.|The particle follows the item it marks.|La partícula va després de l’element que marca.','select-segment');
  choice('recognition','¿Qué función tiene は en esta lección?|What is the role of は in this lesson?|Quina funció té は en aquesta lliçó?',[
    ['Presentar de qué hablamos|Introduce what we talk about|Presentar de què parlem','は establece el tema de la información.|は establishes the topic of the information.|は estableix el tema de la informació.'],['Significar siempre «ser»|Always mean “be”|Significar sempre «ser»','El cierre nominal aporta el estado; は organiza el tema.|The nominal ending supplies the state; は organises the topic.|El final nominal aporta l’estat; は organitza el tema.'],['Marcar siempre todo sujeto|Always mark every subject|Marcar sempre tot subjecte','Tema y sujeto no son equivalentes absolutos.|Topic and subject are not absolute equivalents.|Tema i subjecte no són equivalents absoluts.']],0,'Tema: aquello sobre lo que vamos a dar información.|Topic: what we are about to give information about.|Tema: allò sobre el qual donarem informació.');
  fill('Presenta a Tanaka como tema: 田中さん＿学生だ。|Introduce Tanaka as the topic: 田中さん＿学生だ。|Presenta Tanaka com a tema: 田中さん＿学生だ。','は','Se escribe は y, como partícula, se lee わ.|It is written は and, as a particle, read わ.|S’escriu は i, com a partícula, es llegeix わ.');
  choice('usage','田中さんは学生？ Ya está claro el tema. ¿Qué respuesta afirmativa puede omitirlo?|田中さんは学生？ The topic is already clear. Which affirmative reply can omit it?|田中さんは学生？ El tema ja és clar. Quina resposta afirmativa el pot ometre?',[
    valid('学生だ。',omission),valid('学生じゃない。','Esta respuesta niega la información, pero pedimos afirmarla.|This reply denies the information, but we asked for affirmation.|Aquesta resposta nega la informació, però demanem afirmar-la.')],0,omission);
  use(6);
  fill('Tanaka es estudiante y Yamada también: 山田さん＿学生だ。|Tanaka is a student and Yamada is too: 山田さん＿学生だ。|Tanaka és estudiant i Yamada també: 山田さん＿学生だ。','も','も añade a Yamada a la misma afirmación.|も adds Yamada to the same statement.|も afegeix Yamada a la mateixa afirmació.');
  choice('recognition','¿Qué añade も en 山田さんも学生だ。?|What does も add in 山田さんも学生だ。?|Què afegeix も a 山田さんも学生だ。?',[
    ['Yamada también es estudiante.|Yamada is also a student.|Yamada també és estudiant.','Se aplica la misma información a otra persona.|The same information applies to another person.|S’aplica la mateixa informació a una altra persona.'],['Solo Yamada es estudiante.|Only Yamada is a student.|Només Yamada és estudiant.','も incluye; no significa «solo».|も includes; it does not mean “only”.|も inclou; no significa «només».'],['Yamada era estudiante.|Yamada was a student.|Yamada era estudiant.','も no marca pasado.|も does not mark past tense.|も no marca passat.']],0,'も señala una coincidencia con información previa.|も indicates a match with preceding information.|も assenyala una coincidència amb informació prèvia.');
  choice('usage','田中さんは先生だ。 Añade que Yamada también es docente: 山田さん＿先生だ。|田中さんは先生だ。 Add that Yamada is also a teacher: 山田さん＿先生だ。|田中さんは先生だ。 Afegeix que Yamada també és docent: 山田さん＿先生だ。',particles,1,'La coincidencia es ser docente.|The shared information is being a teacher.|La coincidència és ser docent.');
  choice('error-detection','Encuentra la acumulación incorrecta en el patrón «yo también».|Find the incorrect stacking in the “I also” pattern.|Troba l’acumulació incorrecta en el patró «jo també».',[
    invalid('私はも学生だ。','Usa 私も学生だ。; aquí も sustituye a は.|Use 私も学生だ。; here も replaces は.|Fes servir 私も学生だ。; aquí も substitueix は.'),valid('私も学生だ。','も aparece directamente después de 私.|も follows 私 directly.|も apareix directament després de 私.')],0,'No juntes は y も para esta función.|Do not combine は and も for this function.|No ajuntis は i も per a aquesta funció.','detect-error');
  choice('contrast','Tanaka es estudiante; Yamada no lo es. Sin otra persona que tampoco lo sea, ¿qué frase presenta a Yamada sin añadir «también no»?|Tanaka is a student; Yamada is not. With no other non-student mentioned, which sentence introduces Yamada without adding “also not”?|Tanaka és estudiant; Yamada no ho és. Sense cap altra persona que tampoc ho sigui, quina frase presenta Yamada sense afegir «tampoc»?',[
    valid('山田さんは学生じゃない。','は permite dar una información diferente sobre Yamada.|は allows different information about Yamada.|は permet donar una informació diferent sobre Yamada.'),valid('山田さんも学生じゃない。','Esta frase necesitaría otra negación compartida; el contexto solo estableció una afirmación.|This sentence would need a shared negative; the context established only an affirmative.|Aquesta frase necessitaria una negació compartida; el context només ha establert una afirmació.')],0,'Una frase válida puede necesitar un contexto diferente.|A valid sentence can need a different context.|Una frase vàlida pot necessitar un context diferent.');
  use(7);
  fill('Buscas identificar quién es estudiante: 誰＿学生？|You want to identify who is a student: 誰＿学生？|Busques identificar qui és estudiant: 誰＿学生？','が','誰が pregunta por la identidad que falta.|誰が asks for the missing identity.|誰が pregunta per la identitat que falta.');
  choice('usage','誰が先生？ Responde identificando a Yamada: 山田さん＿先生だ。|誰が先生？ Answer by identifying Yamada: 山田さん＿先生だ。|誰が先生？ Respon identificant Yamada: 山田さん＿先生だ。',particles,2,'Buscamos la persona que cumple la descripción.|We are looking for the person who fits the description.|Busquem la persona que compleix la descripció.');
  choice('recognition','¿Qué destaca が en 田中さんが学生だ, como respuesta a 誰が学生？|What does が highlight in 田中さんが学生だ as an answer to 誰が学生？|Què destaca が a 田中さんが学生だ, com a resposta a 誰が学生？',[
    ['La identidad: Tanaka|The identity: Tanaka|La identitat: Tanaka','Tanaka llena el hueco de 誰.|Tanaka fills the 誰 slot.|Tanaka omple l’espai de 誰.'],['El pasado|The past|El passat','が no cambia el tiempo nominal.|が does not change nominal tense.|が no canvia el temps nominal.'],['La posesión de un estudiante|Ownership of a student|La possessió d’un estudiant','Aquí no estamos relacionando dos nombres con の.|Here we are not linking two nouns with の.|Aquí no relacionem dos noms amb の.']],0,'La pregunta busca quién, y が destaca esa respuesta.|The question asks who, and が highlights that answer.|La pregunta busca qui, i が destaca aquesta resposta.');
  order('Identifica a Tanaka como docente: forma la respuesta a 誰が先生？|Identify Tanaka as the teacher: build the reply to 誰が先生？|Identifica Tanaka com a docent: forma la resposta a 誰が先生？',['先生だ','田中さん','が'],[1,2,0],'El elemento identificado precede a が.|The identified item precedes が.|L’element identificat precedeix が.','sentence-builder');
  use(8);
  choice('contrast','Completa la búsqueda de identidad: 誰＿学生？|Complete the search for identity: 誰＿学生？|Completa la cerca d’identitat: 誰＿学生？',particles,2,'Aquí el hueco por resolver es quién.|Here the missing information is who.|Aquí la informació que falta és qui.');
  choice('usage','Vas a presentar a Tanaka como tema y contar algo sobre él: 田中さん＿学生だ。|You will introduce Tanaka as the topic and give information about them: 田中さん＿学生だ。|Presentaràs Tanaka com a tema i en diràs alguna cosa: 田中さん＿学生だ。',particles,0,'La función solicitada es presentar un tema.|The requested function is introducing a topic.|La funció demanada és presentar un tema.');
  choice('usage','En respuesta a 誰が先生？, quieres destacar quién es: 山田さん＿先生だ。|In reply to 誰が先生？, you want to highlight who it is: 山田さん＿先生だ。|En resposta a 誰が先生？, vols destacar qui és: 山田さん＿先生だ。',particles,2,'La función solicitada es identificar, no añadir «también».|The requested function is identifying, not adding “also”.|La funció demanada és identificar, no afegir «també».');
  choice('contrast','田中さんは学生だ。 / 田中さんが学生だ。 ¿Cuál es la lectura más útil de la diferencia inicial?|田中さんは学生だ。 / 田中さんが学生だ。 What is the most useful initial distinction?|田中さんは学生だ。 / 田中さんが学生だ。 Quina és la distinció inicial més útil?',[
    ['Tema frente a identificación|Topic versus identification|Tema i identificació','Ambas pueden ser válidas; organizan la información de forma diferente.|Both can be valid; they organise information differently.|Totes dues poden ser vàlides; organitzen la informació de manera diferent.'],['Correcta frente a siempre incorrecta|Correct versus always incorrect|Correcta i sempre incorrecta','Ninguna de las dos es universalmente incorrecta.|Neither is universally incorrect.|Cap de les dues és universalment incorrecta.'],['Presente frente a pasado|Present versus past|Present i passat','La terminación だ es igual en ambas.|The ending だ is the same in both.|La terminació だ és igual en totes dues.']],0,'El modelo orienta la atención dentro del diálogo.|The model guides attention within the dialogue.|El model orienta l’atenció dins del diàleg.');
  choice('contrast','¿Podemos elegir は o が simplemente traduciendo ambas como «sujeto»?|Can we choose は or が simply by translating both as “subject”?|Podem triar は o が simplement traduint-les totes dues com a «subjecte»?',[
    ['No: debemos mirar la función y el contexto.|No: we must look at function and context.|No: hem de mirar la funció i el context.','La traducción por sí sola pierde la diferencia de información.|Translation alone loses the information distinction.|La traducció per si sola perd la diferència d’informació.'],['Sí: siempre son intercambiables.|Yes: they are always interchangeable.|Sí: sempre són intercanviables.','Esa regla borra precisamente lo que estamos aprendiendo a distinguir.|That rule removes precisely what we are learning to distinguish.|Aquesta regla esborra precisament el que aprenem a distingir.']],0,'Es un modelo inicial, no una traducción literal ni toda la teoría de は y が.|This is an initial model, not a literal translation or the whole theory of は and が.|És un model inicial, no una traducció literal ni tota la teoria de は i が.');
  use(9);
  order('Forma «el libro de Yuki».|Build “Yuki’s book”.|Forma «el llibre de Yuki».',['本','ゆきさん','の'],[1,2,0],'El nombre principal 本 queda al final.|The head noun 本 goes last.|El nom principal 本 queda al final.');
  choice('recognition','En 日本語の先生, ¿cuál es el núcleo?|In 日本語の先生, which is the head noun?|A 日本語の先生, quin és el nucli?',[
    [jp('先生'),'Hablamos de un docente, especificado por 日本語.|We are talking about a teacher, specified by 日本語.|Parlem d’un docent, especificat per 日本語.'],[jp('日本語'),'日本語 indica la especialidad, no el núcleo.|日本語 indicates the subject taught, not the head noun.|日本語 indica l’especialitat, no el nucli.'],[jp('の'),'の relaciona los nombres; no es un nombre.|の links the nouns; it is not a noun.|の relaciona els noms; no és un nom.']],0,'Busca B en A の B.|Look for B in A の B.|Busca B dins A の B.');
  fill('Un coche de Japón: 日本＿車。|A car from Japan: 日本＿車。|Un cotxe del Japó: 日本＿車。','の','の relaciona el origen con el nombre principal.|の connects the origin to the head noun.|の relaciona l’origen amb el nom principal.');
  order('Forma «docente de japonés».|Build “Japanese-language teacher”.|Forma «docent de japonès».',['の','先生','日本語'],[2,0,1],'La especialidad 日本語 especifica al docente 先生.|The subject 日本語 specifies the teacher 先生.|L’especialitat 日本語 especifica el docent 先生.');
  choice('recognition','¿Cuál describe mejor の en 日本語の先生?|Which best describes の in 日本語の先生?|Quina explicació descriu millor の a 日本語の先生?',[
    ['Relaciona la especialidad con el docente.|It links the subject taught to the teacher.|Relaciona l’especialitat amb el docent.','の no exige que exista un propietario.|の does not require an owner.|の no exigeix que hi hagi un propietari.'],['Siempre indica propiedad literal.|It always indicates literal ownership.|Sempre indica propietat literal.','Un idioma no posee al docente; aquí especifica su especialidad.|A language does not own the teacher; here it specifies their subject.|Una llengua no posseeix el docent; aquí n’especifica l’especialitat.']],0,'La relación entre nombres es más amplia que la posesión.|The relationship between nouns is broader than ownership.|La relació entre noms és més àmplia que la possessió.');
  use(10);
  const things=[valid('これ','こ sitúa aquí la cosa junto al hablante.|こ places the thing near the speaker here.|こ situa aquí l’objecte al costat de qui parla.'),valid('それ','そ sitúa aquí la cosa junto al oyente.|そ places the thing near the listener here.|そ situa aquí l’objecte al costat de l’oient.'),valid('あれ','あ sitúa aquí la cosa lejos de ambos.|あ places the thing far from both here.|あ situa aquí l’objecte lluny de tots dos.'),valid('どれ','ど pregunta cuál, no señala una cosa determinada.|ど asks which, rather than pointing to a specific thing.|ど pregunta quin, no assenyala un objecte determinat.')];
  choice('usage','Señalas un libro que sostienes tú, sin añadir un nombre. ¿Qué forma usas?|You point to a book you are holding, without adding a noun. Which form do you use?|Assenyales un llibre que sostens tu, sense afegir-hi un nom. Quina forma fas servir?',things,0,'La cosa está del lado de quien habla.|The thing is on the speaker’s side.|L’objecte és del costat de qui parla.');
  choice('usage','El objeto lo sostiene tu interlocutor, lejos de ti. Señálalo sin añadir un nombre.|Your listener holds the object, away from you. Point to it without adding a noun.|L’objecte el sosté el teu interlocutor, lluny de tu. Assenyala’l sense afegir-hi un nom.',things,1,'En este contexto espacial corresponde la familia そ.|In this spatial context, the そ family fits.|En aquest context espacial correspon la família そ.');
  fill('Completa «este libro», junto a ti: ＿本。|Complete “this book”, near you: ＿本。|Completa «aquest llibre», a prop teu: ＿本。','この','この acompaña directamente a 本.|この directly accompanies 本.|この acompanya directament 本.');
  choice('error-detection','Busca la combinación incorrecta para decir «este libro».|Find the incorrect combination for “this book”.|Busca la combinació incorrecta per dir «aquest llibre».',[
    valid('この本','この necesita un nombre y aquí lo tiene.|この needs a noun and has one here.|この necessita un nom i aquí el té.'),invalid('これ本','これ no acompaña directamente a 本; usa この本.|これ does not directly accompany 本; use この本.|これ no acompanya directament 本; fes servir この本.')],1,'Pronombre y acompañante de nombre pertenecen a filas distintas.|Pronoun and noun modifier belong to different rows.|Pronom i acompanyant del nom pertanyen a files diferents.','detect-error');
  matching('En una situación espacial, relaciona las cuatro familias.|In a spatial situation, match the four families.|En una situació espacial, relaciona les quatre famílies.',[['こ','Lado del hablante|Speaker’s side|Costat de qui parla'],['そ','Lado del oyente|Listener’s side|Costat de l’oient'],['あ','Lejos de ambos|Far from both|Lluny de tots dos'],['ど','Pregunta por la opción|Asks which option|Pregunta per l’opció']],'La distancia es un punto de partida; el contexto también cuenta.|Distance is a starting point; context matters too.|La distància és un punt de partida; el context també compta.');
  choice('recognition','Quieres preguntar por un lugar, no por una cosa. ¿Qué forma eliges?|You want to ask about a place, not a thing. Which form do you choose?|Vols preguntar per un lloc, no per una cosa. Quina forma tries?',[
    valid('どこ','どこ pregunta por un lugar.|どこ asks about a place.|どこ pregunta per un lloc.'),valid('どれ','どれ pregunta por una cosa entre opciones.|どれ asks which thing among options.|どれ pregunta per una cosa entre opcions.'),[jp('どの'),'どの necesita un nombre después.|どの needs a following noun.|どの necessita un nom després.']],0,'Escoge la fila de lugares.|Choose the row for places.|Tria la fila dels llocs.');
  matching('Relaciona cada forma con su uso.|Match each form with its use.|Relaciona cada forma amb el seu ús.',[['これ','Esta cosa, sin nombre detrás|This thing, with no noun after it|Aquesta cosa, sense nom al darrere'],['その','Ese… junto al oyente, con nombre detrás|That… near the listener, followed by a noun|Aquell… a prop de l’oient, amb nom al darrere'],['あそこ','Aquel lugar, lejos de ambos|That place, far from both|Aquell lloc, lluny de tots dos'],['どの','Qué… entre opciones, con nombre detrás|Which… among options, followed by a noun|Quin… entre opcions, amb nom al darrere']],'Combina la familia de distancia con el tipo de palabra que necesitas.|Combine the distance family with the word type you need.|Combina la família de distància amb el tipus de paraula que necessites.');

  // Fifteen distinct cumulative questions, retaining the original semantic concept.
  reviewing=true;
  use(1);order('Declara «Es tranquilo» con 静か.|State “It is quiet” using 静か.|Declara «És tranquil» amb 静か.',['だ','静か'],[1,0],'静か pertenece al grupo な.|静か belongs to the な group.|静か pertany al grup な.','sentence-builder');
  use(2);fill('Niega que sea tranquilo ahora: 静か＿。|Deny that it is quiet now: 静か＿。|Nega que sigui tranquil ara: 静か＿。','じゃない','No pasado negativo: じゃない.|Non-past negative: じゃない.|No passat negatiu: じゃない.');
  use(3);choice('usage','Recuerdas que antes ese lugar era tranquilo.|You recall that the place used to be quiet.|Recordes que abans aquell lloc era tranquil.',stateOptions('静か'),2,'La descripción es afirmativa y pasada.|The description is affirmative and past.|La descripció és afirmativa i passada.');
  use(4);choice('usage','Ayer el lugar no era tranquilo. ¿Qué descripción corresponde?|Yesterday the place was not quiet. Which description fits?|Ahir el lloc no era tranquil. Quina descripció correspon?',stateOptions('静か'),3,'La descripción combina negación y pasado.|The description combines negation and past tense.|La descripció combina negació i passat.');
  use(5);choice('usage','Presenta a Yuki como tema: ゆきさん＿先生だ。|Introduce Yuki as the topic: ゆきさん＿先生だ。|Presenta Yuki com a tema: ゆきさん＿先生だ。',particles,0,'Se pide un tema, no una identidad buscada.|A topic is requested, not a sought identity.|Es demana un tema, no una identitat cercada.');
  use(6);fill('Yuki está bien. Tú también: 私＿元気だ。|Yuki is well. You are too: 私＿元気だ。|Yuki es troba bé. Tu també: 私＿元気だ。','も','Ambas personas comparten el mismo estado.|Both people share the same state.|Totes dues persones comparteixen el mateix estat.');
  use(7);fill('Quieres averiguar quién es docente: 誰＿先生？|You want to find out who is a teacher: 誰＿先生？|Vols esbrinar qui és docent: 誰＿先生？','が','が señala el hueco de identidad.|が marks the identity slot.|が assenyala l’espai d’identitat.');
  use(6);choice('usage','Yuki no es estudiante; tú tampoco. Completa 私＿学生じゃない。|Yuki is not a student; neither are you. Complete 私＿学生じゃない。|Yuki no és estudiant; tu tampoc. Completa 私＿学生じゃない。',particles,1,'も también puede compartir una negación.|も can also share a negative statement.|も també pot compartir una negació.');
  use(8);choice('contrast','Ya hablamos de Yamada y queremos dar información sobre ese tema: 山田さん＿元気だ。|We are already talking about Yamada and want to give information about that topic: 山田さん＿元気だ。|Ja parlem de Yamada i volem donar informació sobre aquest tema: 山田さん＿元気だ。',particles,0,'は corresponde a la función de tema solicitada.|は fits the requested topic function.|は correspon a la funció de tema demanada.');
  choice('contrast','誰が学生？ Elige la partícula para identificarte como respuesta: 私＿学生だ。|誰が学生？ Choose the particle to identify yourself as the answer: 私＿学生だ。|誰が学生？ Tria la partícula per identificar-te com a resposta: 私＿学生だ。',particles,2,'が destaca quién responde a 誰.|が highlights who answers 誰.|が destaca qui respon a 誰.');
  use(9);order('Forma «el coche de Yamada».|Build “Yamada’s car”.|Forma «el cotxe de Yamada».',['車','の','山田さん'],[2,1,0],'車 es el núcleo, especificado por 山田さん.|車 is the head, specified by 山田さん.|車 és el nucli, especificat per 山田さん.');
  choice('recognition','En 日本の本, ¿de qué tipo de cosa hablamos?|In 日本の本, what kind of thing are we talking about?|A 日本の本, de quin tipus de cosa parlem?',[
    [jp('本'),'El núcleo es el nombre después de の.|The head is the noun after の.|El nucli és el nom després de の.'],[jp('日本'),'日本 especifica la relación, pero no es el núcleo.|日本 specifies the relationship, but is not the head.|日本 especifica la relació, però no és el nucli.']],0,'Busca el nombre principal al final.|Look for the head noun at the end.|Busca el nom principal al final.');
  use(10);choice('usage','Ves una cosa lejos de ti y de tu interlocutor. Señálala sin nombre detrás.|You see a thing far from you and your listener. Point to it with no noun after it.|Veus una cosa lluny de tu i del teu interlocutor. Assenyala-la sense nom al darrere.',things,2,'あれ señala una cosa alejada de ambos.|あれ points to a thing far from both.|あれ assenyala una cosa allunyada de tots dos.');
  fill('Un libro junto al oyente: ＿本。|A book next to the listener: ＿本。|Un llibre al costat de l’oient: ＿本。','その','その acompaña un nombre y corresponde aquí al lado del oyente.|その accompanies a noun and here refers to the listener’s side.|その acompanya un nom i correspon aquí al costat de l’oient.');
  choice('usage','Quieres señalar el lugar donde tú estás. Elige la forma de lugar.|You want to point to the place where you are. Choose the place form.|Vols assenyalar el lloc on ets tu. Tria la forma de lloc.',[
    valid('ここ','ここ señala el lugar del hablante.|ここ indicates the speaker’s place.|ここ assenyala el lloc de qui parla.'),valid('これ','これ señala una cosa, no un lugar.|これ indicates a thing, not a place.|これ assenyala una cosa, no un lloc.'),valid('そこ','そこ señala aquí el lado del oyente.|そこ indicates the listener’s side here.|そこ assenyala aquí el costat de l’oient.')],0,'Para un lugar usa la fila ここ・そこ・あそこ・どこ.|For a place use the ここ・そこ・あそこ・どこ row.|Per a un lloc fes servir la fila ここ・そこ・あそこ・どこ.');
  reviewing=false;
  addAdjectivesV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addVerbsV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addLocationV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addPoliteV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addClausesV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addTeV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addInteractionV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addConnectionsV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  reviewing=false;
  addExperienceV2({add,key,K,choice,fill,order,matching,valid,invalid,jp,
    use:id=>{current=concepts.find(c=>c.id===id);if(!current)throw new Error(`Unknown concept ${id}`);},
    startReview:()=>{reviewing=true;}});
  concepts.forEach(c=>c.relatedIds=concepts.filter(other=>other.prerequisiteIds.includes(c.id)).map(other=>other.id));
  return {concepts,review,copy,editorialReferences};
}
