// Generated by scripts/generate-countries.mjs from world-countries,
// i18n-iso-countries and flag-icons. Do not edit entries manually.
import { Country } from '../core/models/country.model';

export const COUNTRIES: readonly Country[] = [
  {
    "id": "af",
    "iso2": "AF",
    "iso3": "AFG",
    "names": {
      "es": "Afganistán",
      "en": "Afghanistan",
      "ca": "Afganistan"
    },
    "studyRegion": "asia",
    "flagCode": "af",
    "capitals": [
      {
        "es": "Kabul",
        "en": "Kabul",
        "ca": "Kabul"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "al",
    "iso2": "AL",
    "iso3": "ALB",
    "names": {
      "es": "Albania",
      "en": "Albania",
      "ca": "Albània"
    },
    "studyRegion": "europe",
    "flagCode": "al",
    "capitals": [
      {
        "es": "Tirana",
        "en": "Tirana",
        "ca": "Tirana"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "dz",
    "iso2": "DZ",
    "iso3": "DZA",
    "names": {
      "es": "Argelia",
      "en": "Algeria",
      "ca": "Algèria"
    },
    "studyRegion": "africa",
    "flagCode": "dz",
    "capitals": [
      {
        "es": "Argel",
        "en": "Algiers",
        "ca": "Alger"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ad",
    "iso2": "AD",
    "iso3": "AND",
    "names": {
      "es": "Andorra",
      "en": "Andorra",
      "ca": "Andorra"
    },
    "studyRegion": "europe",
    "flagCode": "ad",
    "capitals": [
      {
        "es": "Andorra la Vella",
        "en": "Andorra la Vella",
        "ca": "Andorra la Vella"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ao",
    "iso2": "AO",
    "iso3": "AGO",
    "names": {
      "es": "Angola",
      "en": "Angola",
      "ca": "Angola"
    },
    "studyRegion": "africa",
    "flagCode": "ao",
    "capitals": [
      {
        "es": "Luanda",
        "en": "Luanda",
        "ca": "Luanda"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ag",
    "iso2": "AG",
    "iso3": "ATG",
    "names": {
      "es": "Antigua y Barbuda",
      "en": "Antigua and Barbuda",
      "ca": "Antigua i Barbuda"
    },
    "studyRegion": "north-america",
    "flagCode": "ag",
    "capitals": [
      {
        "es": "Saint John's",
        "en": "Saint John's",
        "ca": "Saint John's"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ar",
    "iso2": "AR",
    "iso3": "ARG",
    "names": {
      "es": "Argentina",
      "en": "Argentina",
      "ca": "Argentina"
    },
    "studyRegion": "south-america",
    "flagCode": "ar",
    "capitals": [
      {
        "es": "Buenos Aires",
        "en": "Buenos Aires",
        "ca": "Buenos Aires"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "am",
    "iso2": "AM",
    "iso3": "ARM",
    "names": {
      "es": "Armenia",
      "en": "Armenia",
      "ca": "Armènia"
    },
    "studyRegion": "asia",
    "flagCode": "am",
    "capitals": [
      {
        "es": "Ereván",
        "en": "Yerevan",
        "ca": "Erevan"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "au",
    "iso2": "AU",
    "iso3": "AUS",
    "names": {
      "es": "Australia",
      "en": "Australia",
      "ca": "Austràlia"
    },
    "studyRegion": "oceania",
    "flagCode": "au",
    "capitals": [
      {
        "es": "Canberra",
        "en": "Canberra",
        "ca": "Canberra"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "at",
    "iso2": "AT",
    "iso3": "AUT",
    "names": {
      "es": "Austria",
      "en": "Austria",
      "ca": "Àustria"
    },
    "studyRegion": "europe",
    "flagCode": "at",
    "capitals": [
      {
        "es": "Viena",
        "en": "Vienna",
        "ca": "Viena"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "az",
    "iso2": "AZ",
    "iso3": "AZE",
    "names": {
      "es": "Azerbaiyán",
      "en": "Azerbaijan",
      "ca": "Azerbaidjan"
    },
    "studyRegion": "asia",
    "flagCode": "az",
    "capitals": [
      {
        "es": "Bakú",
        "en": "Baku",
        "ca": "Bakú"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bs",
    "iso2": "BS",
    "iso3": "BHS",
    "names": {
      "es": "Bahamas",
      "en": "Bahamas",
      "ca": "Bahames"
    },
    "studyRegion": "north-america",
    "flagCode": "bs",
    "capitals": [
      {
        "es": "Nassau",
        "en": "Nassau",
        "ca": "Nassau"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bh",
    "iso2": "BH",
    "iso3": "BHR",
    "names": {
      "es": "Bahrein",
      "en": "Bahrain",
      "ca": "Bahrain"
    },
    "studyRegion": "asia",
    "flagCode": "bh",
    "capitals": [
      {
        "es": "Manama",
        "en": "Manama",
        "ca": "Manama"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bd",
    "iso2": "BD",
    "iso3": "BGD",
    "names": {
      "es": "Bangladesh",
      "en": "Bangladesh",
      "ca": "Bangla Desh"
    },
    "studyRegion": "asia",
    "flagCode": "bd",
    "capitals": [
      {
        "es": "Dhaka",
        "en": "Dhaka",
        "ca": "Dhaka"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bb",
    "iso2": "BB",
    "iso3": "BRB",
    "names": {
      "es": "Barbados",
      "en": "Barbados",
      "ca": "Barbados"
    },
    "studyRegion": "north-america",
    "flagCode": "bb",
    "capitals": [
      {
        "es": "Bridgetown",
        "en": "Bridgetown",
        "ca": "Bridgetown"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "by",
    "iso2": "BY",
    "iso3": "BLR",
    "names": {
      "es": "Bielorrusia",
      "en": "Belarus",
      "ca": "Bielorússia"
    },
    "studyRegion": "europe",
    "flagCode": "by",
    "capitals": [
      {
        "es": "Minsk",
        "en": "Minsk",
        "ca": "Minsk"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "be",
    "iso2": "BE",
    "iso3": "BEL",
    "names": {
      "es": "Bélgica",
      "en": "Belgium",
      "ca": "Bèlgica"
    },
    "studyRegion": "europe",
    "flagCode": "be",
    "capitals": [
      {
        "es": "Bruselas",
        "en": "Brussels",
        "ca": "Brussel·les"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bz",
    "iso2": "BZ",
    "iso3": "BLZ",
    "names": {
      "es": "Belice",
      "en": "Belize",
      "ca": "Belize"
    },
    "studyRegion": "north-america",
    "flagCode": "bz",
    "capitals": [
      {
        "es": "Belmopan",
        "en": "Belmopan",
        "ca": "Belmopan"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bj",
    "iso2": "BJ",
    "iso3": "BEN",
    "names": {
      "es": "Benin",
      "en": "Benin",
      "ca": "Benín"
    },
    "studyRegion": "africa",
    "flagCode": "bj",
    "capitals": [
      {
        "es": "Porto-Novo",
        "en": "Porto-Novo",
        "ca": "Porto-Novo"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "bt",
    "iso2": "BT",
    "iso3": "BTN",
    "names": {
      "es": "Bután",
      "en": "Bhutan",
      "ca": "Bhutan"
    },
    "studyRegion": "asia",
    "flagCode": "bt",
    "capitals": [
      {
        "es": "Thimphu",
        "en": "Thimphu",
        "ca": "Thimphu"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bo",
    "iso2": "BO",
    "iso3": "BOL",
    "names": {
      "es": "Bolivia",
      "en": "Bolivia",
      "ca": "Bolívia"
    },
    "studyRegion": "south-america",
    "flagCode": "bo",
    "capitals": [
      {
        "es": "Sucre",
        "en": "Sucre",
        "ca": "Sucre"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "ba",
    "iso2": "BA",
    "iso3": "BIH",
    "names": {
      "es": "Bosnia y Herzegovina",
      "en": "Bosnia and Herzegovina",
      "ca": "Bòsnia i Hercegovina"
    },
    "studyRegion": "europe",
    "flagCode": "ba",
    "capitals": [
      {
        "es": "Sarajevo",
        "en": "Sarajevo",
        "ca": "Sarajevo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bw",
    "iso2": "BW",
    "iso3": "BWA",
    "names": {
      "es": "Botswana",
      "en": "Botswana",
      "ca": "Botswana"
    },
    "studyRegion": "africa",
    "flagCode": "bw",
    "capitals": [
      {
        "es": "Gaborone",
        "en": "Gaborone",
        "ca": "Gaborone"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "br",
    "iso2": "BR",
    "iso3": "BRA",
    "names": {
      "es": "Brasil",
      "en": "Brazil",
      "ca": "Brasil"
    },
    "studyRegion": "south-america",
    "flagCode": "br",
    "capitals": [
      {
        "es": "Brasilia",
        "en": "Brasília",
        "ca": "Brasília"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bn",
    "iso2": "BN",
    "iso3": "BRN",
    "names": {
      "es": "Brunei Darussalam",
      "en": "Brunei Darussalam",
      "ca": "Brunei"
    },
    "studyRegion": "asia",
    "flagCode": "bn",
    "capitals": [
      {
        "es": "Bandar Seri Begawan",
        "en": "Bandar Seri Begawan",
        "ca": "Bandar Seri Begawan"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bg",
    "iso2": "BG",
    "iso3": "BGR",
    "names": {
      "es": "Bulgaria",
      "en": "Bulgaria",
      "ca": "Bulgària"
    },
    "studyRegion": "europe",
    "flagCode": "bg",
    "capitals": [
      {
        "es": "Sofia",
        "en": "Sofia",
        "ca": "Sofia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bf",
    "iso2": "BF",
    "iso3": "BFA",
    "names": {
      "es": "Burkina Faso",
      "en": "Burkina Faso",
      "ca": "Burkina Faso"
    },
    "studyRegion": "africa",
    "flagCode": "bf",
    "capitals": [
      {
        "es": "Ouagadougou",
        "en": "Ouagadougou",
        "ca": "Ouagadougou"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "bi",
    "iso2": "BI",
    "iso3": "BDI",
    "names": {
      "es": "Burundi",
      "en": "Burundi",
      "ca": "Burundi"
    },
    "studyRegion": "africa",
    "flagCode": "bi",
    "capitals": [
      {
        "es": "Gitega",
        "en": "Gitega",
        "ca": "Gitega"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kh",
    "iso2": "KH",
    "iso3": "KHM",
    "names": {
      "es": "Camboya",
      "en": "Cambodia",
      "ca": "Cambodja"
    },
    "studyRegion": "asia",
    "flagCode": "kh",
    "capitals": [
      {
        "es": "Nom Pen",
        "en": "Phnom Penh",
        "ca": "Phnom Penh"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cm",
    "iso2": "CM",
    "iso3": "CMR",
    "names": {
      "es": "Camerún",
      "en": "Cameroon",
      "ca": "Camerun"
    },
    "studyRegion": "africa",
    "flagCode": "cm",
    "capitals": [
      {
        "es": "Yaoundé",
        "en": "Yaoundé",
        "ca": "Yaoundé"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ca",
    "iso2": "CA",
    "iso3": "CAN",
    "names": {
      "es": "Canadá",
      "en": "Canada",
      "ca": "Canadà"
    },
    "studyRegion": "north-america",
    "flagCode": "ca",
    "capitals": [
      {
        "es": "Ottawa",
        "en": "Ottawa",
        "ca": "Ottawa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cv",
    "iso2": "CV",
    "iso3": "CPV",
    "names": {
      "es": "Cabo Verde",
      "en": "Cape Verde",
      "ca": "Cap Verd"
    },
    "studyRegion": "africa",
    "flagCode": "cv",
    "capitals": [
      {
        "es": "Praia",
        "en": "Praia",
        "ca": "Praia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cf",
    "iso2": "CF",
    "iso3": "CAF",
    "names": {
      "es": "República Centroafricana",
      "en": "Central African Republic",
      "ca": "Centreafricana, República"
    },
    "studyRegion": "africa",
    "flagCode": "cf",
    "capitals": [
      {
        "es": "Bangui",
        "en": "Bangui",
        "ca": "Bangui"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "td",
    "iso2": "TD",
    "iso3": "TCD",
    "names": {
      "es": "Chad",
      "en": "Chad",
      "ca": "Txad"
    },
    "studyRegion": "africa",
    "flagCode": "td",
    "capitals": [
      {
        "es": "N'Djamena",
        "en": "N'Djamena",
        "ca": "N'Djamena"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cl",
    "iso2": "CL",
    "iso3": "CHL",
    "names": {
      "es": "Chile",
      "en": "Chile",
      "ca": "Xile"
    },
    "studyRegion": "south-america",
    "flagCode": "cl",
    "capitals": [
      {
        "es": "Santiago",
        "en": "Santiago",
        "ca": "Santiago"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "co",
    "iso2": "CO",
    "iso3": "COL",
    "names": {
      "es": "Colombia",
      "en": "Colombia",
      "ca": "Colòmbia"
    },
    "studyRegion": "south-america",
    "flagCode": "co",
    "capitals": [
      {
        "es": "Bogotá",
        "en": "Bogotá",
        "ca": "Bogotà"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "km",
    "iso2": "KM",
    "iso3": "COM",
    "names": {
      "es": "Comoras",
      "en": "Comoros",
      "ca": "Comores"
    },
    "studyRegion": "africa",
    "flagCode": "km",
    "capitals": [
      {
        "es": "Moroni",
        "en": "Moroni",
        "ca": "Moroni"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cr",
    "iso2": "CR",
    "iso3": "CRI",
    "names": {
      "es": "Costa Rica",
      "en": "Costa Rica",
      "ca": "Costa Rica"
    },
    "studyRegion": "north-america",
    "flagCode": "cr",
    "capitals": [
      {
        "es": "San José",
        "en": "San José",
        "ca": "San José"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ci",
    "iso2": "CI",
    "iso3": "CIV",
    "names": {
      "es": "Costa de Marfil",
      "en": "Cote d'Ivoire",
      "ca": "Costa d'Ivori"
    },
    "studyRegion": "africa",
    "flagCode": "ci",
    "capitals": [
      {
        "es": "Yamoussoukro",
        "en": "Yamoussoukro",
        "ca": "Yamoussoukro"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "hr",
    "iso2": "HR",
    "iso3": "HRV",
    "names": {
      "es": "Croacia",
      "en": "Croatia",
      "ca": "Croàcia"
    },
    "studyRegion": "europe",
    "flagCode": "hr",
    "capitals": [
      {
        "es": "Zagreb",
        "en": "Zagreb",
        "ca": "Zagreb"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cu",
    "iso2": "CU",
    "iso3": "CUB",
    "names": {
      "es": "Cuba",
      "en": "Cuba",
      "ca": "Cuba"
    },
    "studyRegion": "north-america",
    "flagCode": "cu",
    "capitals": [
      {
        "es": "La Habana",
        "en": "Havana",
        "ca": "l’Havana"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cy",
    "iso2": "CY",
    "iso3": "CYP",
    "names": {
      "es": "Chipre",
      "en": "Cyprus",
      "ca": "Xipre"
    },
    "studyRegion": "europe",
    "flagCode": "cy",
    "capitals": [
      {
        "es": "Nicosia",
        "en": "Nicosia",
        "ca": "Nicòsia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cz",
    "iso2": "CZ",
    "iso3": "CZE",
    "names": {
      "es": "República Checa",
      "en": "Czech Republic",
      "ca": "Txèquia"
    },
    "studyRegion": "europe",
    "flagCode": "cz",
    "capitals": [
      {
        "es": "Praga",
        "en": "Prague",
        "ca": "Praga"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cd",
    "iso2": "CD",
    "iso3": "COD",
    "names": {
      "es": "Congo (República Democrática del)",
      "en": "Democratic Republic of the Congo",
      "ca": "Congo, República Democràtica del"
    },
    "studyRegion": "africa",
    "flagCode": "cd",
    "capitals": [
      {
        "es": "Kinsasa",
        "en": "Kinshasa",
        "ca": "Kinshasa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "dk",
    "iso2": "DK",
    "iso3": "DNK",
    "names": {
      "es": "Dinamarca",
      "en": "Denmark",
      "ca": "Dinamarca"
    },
    "studyRegion": "europe",
    "flagCode": "dk",
    "capitals": [
      {
        "es": "Copenhague",
        "en": "Copenhagen",
        "ca": "Copenhaguen"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "dj",
    "iso2": "DJ",
    "iso3": "DJI",
    "names": {
      "es": "Yibuti",
      "en": "Djibouti",
      "ca": "Djibouti"
    },
    "studyRegion": "africa",
    "flagCode": "dj",
    "capitals": [
      {
        "es": "Djibouti",
        "en": "Djibouti",
        "ca": "Djibouti"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "dm",
    "iso2": "DM",
    "iso3": "DMA",
    "names": {
      "es": "Dominica",
      "en": "Dominica",
      "ca": "Dominica"
    },
    "studyRegion": "north-america",
    "flagCode": "dm",
    "capitals": [
      {
        "es": "Roseau",
        "en": "Roseau",
        "ca": "Roseau"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "do",
    "iso2": "DO",
    "iso3": "DOM",
    "names": {
      "es": "República Dominicana",
      "en": "Dominican Republic",
      "ca": "Dominicana, República"
    },
    "studyRegion": "north-america",
    "flagCode": "do",
    "capitals": [
      {
        "es": "Santo Domingo",
        "en": "Santo Domingo",
        "ca": "Santo Domingo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ec",
    "iso2": "EC",
    "iso3": "ECU",
    "names": {
      "es": "Ecuador",
      "en": "Ecuador",
      "ca": "Equador"
    },
    "studyRegion": "south-america",
    "flagCode": "ec",
    "capitals": [
      {
        "es": "Quito",
        "en": "Quito",
        "ca": "Quito"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "eg",
    "iso2": "EG",
    "iso3": "EGY",
    "names": {
      "es": "Egipto",
      "en": "Egypt",
      "ca": "Egipte"
    },
    "studyRegion": "africa",
    "flagCode": "eg",
    "capitals": [
      {
        "es": "El Cairo",
        "en": "Cairo",
        "ca": "el Caire"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sv",
    "iso2": "SV",
    "iso3": "SLV",
    "names": {
      "es": "El Salvador",
      "en": "El Salvador",
      "ca": "Salvador, El"
    },
    "studyRegion": "north-america",
    "flagCode": "sv",
    "capitals": [
      {
        "es": "San Salvador",
        "en": "San Salvador",
        "ca": "San Salvador"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gq",
    "iso2": "GQ",
    "iso3": "GNQ",
    "names": {
      "es": "Guinea Ecuatorial",
      "en": "Equatorial Guinea",
      "ca": "Guinea Equatorial"
    },
    "studyRegion": "africa",
    "flagCode": "gq",
    "capitals": [
      {
        "es": "Malabo",
        "en": "Malabo",
        "ca": "Malabo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "er",
    "iso2": "ER",
    "iso3": "ERI",
    "names": {
      "es": "Eritrea",
      "en": "Eritrea",
      "ca": "Eritrea"
    },
    "studyRegion": "africa",
    "flagCode": "er",
    "capitals": [
      {
        "es": "Asmara",
        "en": "Asmara",
        "ca": "Asmara"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ee",
    "iso2": "EE",
    "iso3": "EST",
    "names": {
      "es": "Estonia",
      "en": "Estonia",
      "ca": "Estònia"
    },
    "studyRegion": "europe",
    "flagCode": "ee",
    "capitals": [
      {
        "es": "Tallin",
        "en": "Tallinn",
        "ca": "Tallinn"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sz",
    "iso2": "SZ",
    "iso3": "SWZ",
    "names": {
      "es": "Esuatini",
      "en": "Eswatini",
      "ca": "Swazilàndia"
    },
    "studyRegion": "africa",
    "flagCode": "sz",
    "capitals": [
      {
        "es": "Lobamba",
        "en": "Lobamba",
        "ca": "Lobamba"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "et",
    "iso2": "ET",
    "iso3": "ETH",
    "names": {
      "es": "Etiopía",
      "en": "Ethiopia",
      "ca": "Etiòpia"
    },
    "studyRegion": "africa",
    "flagCode": "et",
    "capitals": [
      {
        "es": "Adís Abeba",
        "en": "Addis Ababa",
        "ca": "Addis Abeba"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "fj",
    "iso2": "FJ",
    "iso3": "FJI",
    "names": {
      "es": "Fiji",
      "en": "Fiji",
      "ca": "Fiji"
    },
    "studyRegion": "oceania",
    "flagCode": "fj",
    "capitals": [
      {
        "es": "Suva",
        "en": "Suva",
        "ca": "Suva"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "fi",
    "iso2": "FI",
    "iso3": "FIN",
    "names": {
      "es": "Finlandia",
      "en": "Finland",
      "ca": "Finlàndia"
    },
    "studyRegion": "europe",
    "flagCode": "fi",
    "capitals": [
      {
        "es": "Helsinki",
        "en": "Helsinki",
        "ca": "Helsinki"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "fr",
    "iso2": "FR",
    "iso3": "FRA",
    "names": {
      "es": "Francia",
      "en": "France",
      "ca": "França"
    },
    "studyRegion": "europe",
    "flagCode": "fr",
    "capitals": [
      {
        "es": "Paris",
        "en": "Paris",
        "ca": "Paris"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ga",
    "iso2": "GA",
    "iso3": "GAB",
    "names": {
      "es": "Gabón",
      "en": "Gabon",
      "ca": "Gabon"
    },
    "studyRegion": "africa",
    "flagCode": "ga",
    "capitals": [
      {
        "es": "Libreville",
        "en": "Libreville",
        "ca": "Libreville"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ge",
    "iso2": "GE",
    "iso3": "GEO",
    "names": {
      "es": "Georgia",
      "en": "Georgia",
      "ca": "Geòrgia"
    },
    "studyRegion": "asia",
    "flagCode": "ge",
    "capitals": [
      {
        "es": "Tiflis",
        "en": "Tbilisi",
        "ca": "Tbilissi"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "de",
    "iso2": "DE",
    "iso3": "DEU",
    "names": {
      "es": "Alemania",
      "en": "Germany",
      "ca": "Alemanya"
    },
    "studyRegion": "europe",
    "flagCode": "de",
    "capitals": [
      {
        "es": "Berlin",
        "en": "Berlin",
        "ca": "Berlin"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gh",
    "iso2": "GH",
    "iso3": "GHA",
    "names": {
      "es": "Ghana",
      "en": "Ghana",
      "ca": "Ghana"
    },
    "studyRegion": "africa",
    "flagCode": "gh",
    "capitals": [
      {
        "es": "Accra",
        "en": "Accra",
        "ca": "Accra"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gr",
    "iso2": "GR",
    "iso3": "GRC",
    "names": {
      "es": "Grecia",
      "en": "Greece",
      "ca": "Grècia"
    },
    "studyRegion": "europe",
    "flagCode": "gr",
    "capitals": [
      {
        "es": "Atenas",
        "en": "Athens",
        "ca": "Atenes"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gd",
    "iso2": "GD",
    "iso3": "GRD",
    "names": {
      "es": "Granada",
      "en": "Grenada",
      "ca": "Grenada"
    },
    "studyRegion": "north-america",
    "flagCode": "gd",
    "capitals": [
      {
        "es": "St. George's",
        "en": "St. George's",
        "ca": "St. George's"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gt",
    "iso2": "GT",
    "iso3": "GTM",
    "names": {
      "es": "Guatemala",
      "en": "Guatemala",
      "ca": "Guatemala"
    },
    "studyRegion": "north-america",
    "flagCode": "gt",
    "capitals": [
      {
        "es": "Ciudad de Guatemala",
        "en": "Guatemala City",
        "ca": "Ciutat de Guatemala"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gn",
    "iso2": "GN",
    "iso3": "GIN",
    "names": {
      "es": "Guinea",
      "en": "Guinea",
      "ca": "República de Guinea"
    },
    "studyRegion": "africa",
    "flagCode": "gn",
    "capitals": [
      {
        "es": "Conakry",
        "en": "Conakry",
        "ca": "Conakry"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gw",
    "iso2": "GW",
    "iso3": "GNB",
    "names": {
      "es": "Guinea Bissau",
      "en": "Guinea-Bissau",
      "ca": "Guinea Bissau"
    },
    "studyRegion": "africa",
    "flagCode": "gw",
    "capitals": [
      {
        "es": "Bissau",
        "en": "Bissau",
        "ca": "Bissau"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gy",
    "iso2": "GY",
    "iso3": "GUY",
    "names": {
      "es": "Guyana",
      "en": "Guyana",
      "ca": "Guyana"
    },
    "studyRegion": "south-america",
    "flagCode": "gy",
    "capitals": [
      {
        "es": "Georgetown",
        "en": "Georgetown",
        "ca": "Georgetown"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ht",
    "iso2": "HT",
    "iso3": "HTI",
    "names": {
      "es": "Haití",
      "en": "Haiti",
      "ca": "Haití"
    },
    "studyRegion": "north-america",
    "flagCode": "ht",
    "capitals": [
      {
        "es": "Puerto Príncipe",
        "en": "Port-au-Prince",
        "ca": "Port-au-Prince"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "va",
    "iso2": "VA",
    "iso3": "VAT",
    "names": {
      "es": "Santa Sede",
      "en": "Holy See (Vatican City State)",
      "ca": "Vaticà, Ciutat del"
    },
    "studyRegion": "europe",
    "flagCode": "va",
    "capitals": [
      {
        "es": "Vatican City",
        "en": "Vatican City",
        "ca": "Vatican City"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "hn",
    "iso2": "HN",
    "iso3": "HND",
    "names": {
      "es": "Honduras",
      "en": "Honduras",
      "ca": "Hondures"
    },
    "studyRegion": "north-america",
    "flagCode": "hn",
    "capitals": [
      {
        "es": "Tegucigalpa",
        "en": "Tegucigalpa",
        "ca": "Tegucigalpa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "hu",
    "iso2": "HU",
    "iso3": "HUN",
    "names": {
      "es": "Hungría",
      "en": "Hungary",
      "ca": "Hongria"
    },
    "studyRegion": "europe",
    "flagCode": "hu",
    "capitals": [
      {
        "es": "Budapest",
        "en": "Budapest",
        "ca": "Budapest"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "is",
    "iso2": "IS",
    "iso3": "ISL",
    "names": {
      "es": "Islandia",
      "en": "Iceland",
      "ca": "Islàndia"
    },
    "studyRegion": "europe",
    "flagCode": "is",
    "capitals": [
      {
        "es": "Reikiavik",
        "en": "Reykjavik",
        "ca": "Reykjavík"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "in",
    "iso2": "IN",
    "iso3": "IND",
    "names": {
      "es": "India",
      "en": "India",
      "ca": "Índia"
    },
    "studyRegion": "asia",
    "flagCode": "in",
    "capitals": [
      {
        "es": "Nueva Delhi",
        "en": "New Delhi",
        "ca": "Nova Delhi"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "id",
    "iso2": "ID",
    "iso3": "IDN",
    "names": {
      "es": "Indonesia",
      "en": "Indonesia",
      "ca": "Indonèsia"
    },
    "studyRegion": "asia",
    "flagCode": "id",
    "capitals": [
      {
        "es": "Jakarta",
        "en": "Jakarta",
        "ca": "Jakarta"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "iq",
    "iso2": "IQ",
    "iso3": "IRQ",
    "names": {
      "es": "Iraq",
      "en": "Iraq",
      "ca": "Iraq"
    },
    "studyRegion": "asia",
    "flagCode": "iq",
    "capitals": [
      {
        "es": "Bagdad",
        "en": "Baghdad",
        "ca": "Bagdad"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ie",
    "iso2": "IE",
    "iso3": "IRL",
    "names": {
      "es": "Irlanda",
      "en": "Ireland",
      "ca": "Irlanda"
    },
    "studyRegion": "europe",
    "flagCode": "ie",
    "capitals": [
      {
        "es": "Dublín",
        "en": "Dublin",
        "ca": "Dublín"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ir",
    "iso2": "IR",
    "iso3": "IRN",
    "names": {
      "es": "Irán",
      "en": "Islamic Republic of Iran",
      "ca": "Iran"
    },
    "studyRegion": "asia",
    "flagCode": "ir",
    "capitals": [
      {
        "es": "Teherán",
        "en": "Tehran",
        "ca": "Teheran"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "il",
    "iso2": "IL",
    "iso3": "ISR",
    "names": {
      "es": "Israel",
      "en": "Israel",
      "ca": "Israel"
    },
    "studyRegion": "asia",
    "flagCode": "il",
    "capitals": [
      {
        "es": "Jerusalén",
        "en": "Jerusalem",
        "ca": "Jerusalem"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "it",
    "iso2": "IT",
    "iso3": "ITA",
    "names": {
      "es": "Italia",
      "en": "Italy",
      "ca": "Itàlia"
    },
    "studyRegion": "europe",
    "flagCode": "it",
    "capitals": [
      {
        "es": "Roma",
        "en": "Rome",
        "ca": "Roma"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "jm",
    "iso2": "JM",
    "iso3": "JAM",
    "names": {
      "es": "Jamaica",
      "en": "Jamaica",
      "ca": "Jamaica"
    },
    "studyRegion": "north-america",
    "flagCode": "jm",
    "capitals": [
      {
        "es": "Kingston",
        "en": "Kingston",
        "ca": "Kingston"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "jp",
    "iso2": "JP",
    "iso3": "JPN",
    "names": {
      "es": "Japón",
      "en": "Japan",
      "ca": "Japó"
    },
    "studyRegion": "asia",
    "flagCode": "jp",
    "capitals": [
      {
        "es": "Tokio",
        "en": "Tokyo",
        "ca": "Tòquio"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "jo",
    "iso2": "JO",
    "iso3": "JOR",
    "names": {
      "es": "Jordania",
      "en": "Jordan",
      "ca": "Jordània"
    },
    "studyRegion": "asia",
    "flagCode": "jo",
    "capitals": [
      {
        "es": "Amman",
        "en": "Amman",
        "ca": "Amman"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kz",
    "iso2": "KZ",
    "iso3": "KAZ",
    "names": {
      "es": "Kazajistán",
      "en": "Kazakhstan",
      "ca": "Kazakhstan"
    },
    "studyRegion": "asia",
    "flagCode": "kz",
    "capitals": [
      {
        "es": "Astana",
        "en": "Astana",
        "ca": "Astana"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ke",
    "iso2": "KE",
    "iso3": "KEN",
    "names": {
      "es": "Kenia",
      "en": "Kenya",
      "ca": "Kenya"
    },
    "studyRegion": "africa",
    "flagCode": "ke",
    "capitals": [
      {
        "es": "Nairobi",
        "en": "Nairobi",
        "ca": "Nairobi"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ki",
    "iso2": "KI",
    "iso3": "KIR",
    "names": {
      "es": "Kiribati",
      "en": "Kiribati",
      "ca": "Kiribati"
    },
    "studyRegion": "oceania",
    "flagCode": "ki",
    "capitals": [
      {
        "es": "South Tarawa",
        "en": "South Tarawa",
        "ca": "South Tarawa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kw",
    "iso2": "KW",
    "iso3": "KWT",
    "names": {
      "es": "Kuwait",
      "en": "Kuwait",
      "ca": "Kuwait"
    },
    "studyRegion": "asia",
    "flagCode": "kw",
    "capitals": [
      {
        "es": "Kuwait City",
        "en": "Kuwait City",
        "ca": "Kuwait City"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kg",
    "iso2": "KG",
    "iso3": "KGZ",
    "names": {
      "es": "Kirguistán",
      "en": "Kyrgyzstan",
      "ca": "Kirguizistan"
    },
    "studyRegion": "asia",
    "flagCode": "kg",
    "capitals": [
      {
        "es": "Bishkek",
        "en": "Bishkek",
        "ca": "Bishkek"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "la",
    "iso2": "LA",
    "iso3": "LAO",
    "names": {
      "es": "República Democrática Popular de Lao",
      "en": "Lao People's Democratic Republic",
      "ca": "Laos"
    },
    "studyRegion": "asia",
    "flagCode": "la",
    "capitals": [
      {
        "es": "Vientiane",
        "en": "Vientiane",
        "ca": "Vientiane"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lv",
    "iso2": "LV",
    "iso3": "LVA",
    "names": {
      "es": "Letonia",
      "en": "Latvia",
      "ca": "Letònia"
    },
    "studyRegion": "europe",
    "flagCode": "lv",
    "capitals": [
      {
        "es": "Riga",
        "en": "Riga",
        "ca": "Riga"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lb",
    "iso2": "LB",
    "iso3": "LBN",
    "names": {
      "es": "Líbano",
      "en": "Lebanon",
      "ca": "Líban"
    },
    "studyRegion": "asia",
    "flagCode": "lb",
    "capitals": [
      {
        "es": "Beirut",
        "en": "Beirut",
        "ca": "Beirut"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ls",
    "iso2": "LS",
    "iso3": "LSO",
    "names": {
      "es": "Lesoto",
      "en": "Lesotho",
      "ca": "Lesotho"
    },
    "studyRegion": "africa",
    "flagCode": "ls",
    "capitals": [
      {
        "es": "Maseru",
        "en": "Maseru",
        "ca": "Maseru"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lr",
    "iso2": "LR",
    "iso3": "LBR",
    "names": {
      "es": "Liberia",
      "en": "Liberia",
      "ca": "Libèria"
    },
    "studyRegion": "africa",
    "flagCode": "lr",
    "capitals": [
      {
        "es": "Monrovia",
        "en": "Monrovia",
        "ca": "Monrovia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ly",
    "iso2": "LY",
    "iso3": "LBY",
    "names": {
      "es": "Libia",
      "en": "Libya",
      "ca": "Líbia"
    },
    "studyRegion": "africa",
    "flagCode": "ly",
    "capitals": [
      {
        "es": "Trípoli",
        "en": "Tripoli",
        "ca": "Trípoli"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "li",
    "iso2": "LI",
    "iso3": "LIE",
    "names": {
      "es": "Liechtenstein",
      "en": "Liechtenstein",
      "ca": "Liechtenstein"
    },
    "studyRegion": "europe",
    "flagCode": "li",
    "capitals": [
      {
        "es": "Vaduz",
        "en": "Vaduz",
        "ca": "Vaduz"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lt",
    "iso2": "LT",
    "iso3": "LTU",
    "names": {
      "es": "Lituania",
      "en": "Lithuania",
      "ca": "Lituània"
    },
    "studyRegion": "europe",
    "flagCode": "lt",
    "capitals": [
      {
        "es": "Vilnius",
        "en": "Vilnius",
        "ca": "Vilnius"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lu",
    "iso2": "LU",
    "iso3": "LUX",
    "names": {
      "es": "Luxemburgo",
      "en": "Luxembourg",
      "ca": "Luxemburg"
    },
    "studyRegion": "europe",
    "flagCode": "lu",
    "capitals": [
      {
        "es": "Luxembourg",
        "en": "Luxembourg",
        "ca": "Luxembourg"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mg",
    "iso2": "MG",
    "iso3": "MDG",
    "names": {
      "es": "Madagascar",
      "en": "Madagascar",
      "ca": "Madagascar"
    },
    "studyRegion": "africa",
    "flagCode": "mg",
    "capitals": [
      {
        "es": "Antananarivo",
        "en": "Antananarivo",
        "ca": "Antananarivo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mw",
    "iso2": "MW",
    "iso3": "MWI",
    "names": {
      "es": "Malaui",
      "en": "Malawi",
      "ca": "Malawi"
    },
    "studyRegion": "africa",
    "flagCode": "mw",
    "capitals": [
      {
        "es": "Lilongwe",
        "en": "Lilongwe",
        "ca": "Lilongwe"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "my",
    "iso2": "MY",
    "iso3": "MYS",
    "names": {
      "es": "Malasia",
      "en": "Malaysia",
      "ca": "Malàisia"
    },
    "studyRegion": "asia",
    "flagCode": "my",
    "capitals": [
      {
        "es": "Kuala Lumpur",
        "en": "Kuala Lumpur",
        "ca": "Kuala Lumpur"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "mv",
    "iso2": "MV",
    "iso3": "MDV",
    "names": {
      "es": "Maldivas",
      "en": "Maldives",
      "ca": "Maldives"
    },
    "studyRegion": "asia",
    "flagCode": "mv",
    "capitals": [
      {
        "es": "Malé",
        "en": "Malé",
        "ca": "Malé"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ml",
    "iso2": "ML",
    "iso3": "MLI",
    "names": {
      "es": "Malí",
      "en": "Mali",
      "ca": "Mali"
    },
    "studyRegion": "africa",
    "flagCode": "ml",
    "capitals": [
      {
        "es": "Bamako",
        "en": "Bamako",
        "ca": "Bamako"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mt",
    "iso2": "MT",
    "iso3": "MLT",
    "names": {
      "es": "Malta",
      "en": "Malta",
      "ca": "Malta"
    },
    "studyRegion": "europe",
    "flagCode": "mt",
    "capitals": [
      {
        "es": "Valletta",
        "en": "Valletta",
        "ca": "Valletta"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mh",
    "iso2": "MH",
    "iso3": "MHL",
    "names": {
      "es": "Islas Marshall",
      "en": "Marshall Islands",
      "ca": "Marshall, illes"
    },
    "studyRegion": "oceania",
    "flagCode": "mh",
    "capitals": [
      {
        "es": "Majuro",
        "en": "Majuro",
        "ca": "Majuro"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mr",
    "iso2": "MR",
    "iso3": "MRT",
    "names": {
      "es": "Mauritania",
      "en": "Mauritania",
      "ca": "Mauritània"
    },
    "studyRegion": "africa",
    "flagCode": "mr",
    "capitals": [
      {
        "es": "Nouakchott",
        "en": "Nouakchott",
        "ca": "Nouakchott"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mu",
    "iso2": "MU",
    "iso3": "MUS",
    "names": {
      "es": "Mauricio",
      "en": "Mauritius",
      "ca": "Maurici"
    },
    "studyRegion": "africa",
    "flagCode": "mu",
    "capitals": [
      {
        "es": "Port Louis",
        "en": "Port Louis",
        "ca": "Port Louis"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mx",
    "iso2": "MX",
    "iso3": "MEX",
    "names": {
      "es": "México",
      "en": "Mexico",
      "ca": "Mèxic"
    },
    "studyRegion": "north-america",
    "flagCode": "mx",
    "capitals": [
      {
        "es": "Ciudad de México",
        "en": "Mexico City",
        "ca": "Ciutat de Mèxic"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "fm",
    "iso2": "FM",
    "iso3": "FSM",
    "names": {
      "es": "Micronesia",
      "en": "Micronesia, Federated States of",
      "ca": "Micronèsia, Estats Federats de"
    },
    "studyRegion": "oceania",
    "flagCode": "fm",
    "capitals": [
      {
        "es": "Palikir",
        "en": "Palikir",
        "ca": "Palikir"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "md",
    "iso2": "MD",
    "iso3": "MDA",
    "names": {
      "es": "Moldavia",
      "en": "Moldova, Republic of",
      "ca": "Moldàvia"
    },
    "studyRegion": "europe",
    "flagCode": "md",
    "capitals": [
      {
        "es": "Chișinău",
        "en": "Chișinău",
        "ca": "Chișinău"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mc",
    "iso2": "MC",
    "iso3": "MCO",
    "names": {
      "es": "Mónaco",
      "en": "Monaco",
      "ca": "Mònaco"
    },
    "studyRegion": "europe",
    "flagCode": "mc",
    "capitals": [
      {
        "es": "Monaco",
        "en": "Monaco",
        "ca": "Monaco"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mn",
    "iso2": "MN",
    "iso3": "MNG",
    "names": {
      "es": "Mongolia",
      "en": "Mongolia",
      "ca": "Mongòlia"
    },
    "studyRegion": "asia",
    "flagCode": "mn",
    "capitals": [
      {
        "es": "Ulan Bator",
        "en": "Ulan Bator",
        "ca": "Ulan Bator"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "me",
    "iso2": "ME",
    "iso3": "MNE",
    "names": {
      "es": "Montenegro",
      "en": "Montenegro",
      "ca": "Montenegro"
    },
    "studyRegion": "europe",
    "flagCode": "me",
    "capitals": [
      {
        "es": "Podgorica",
        "en": "Podgorica",
        "ca": "Podgorica"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ma",
    "iso2": "MA",
    "iso3": "MAR",
    "names": {
      "es": "Marruecos",
      "en": "Morocco",
      "ca": "Marroc"
    },
    "studyRegion": "africa",
    "flagCode": "ma",
    "capitals": [
      {
        "es": "Rabat",
        "en": "Rabat",
        "ca": "Rabat"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mz",
    "iso2": "MZ",
    "iso3": "MOZ",
    "names": {
      "es": "Mozambique",
      "en": "Mozambique",
      "ca": "Moçambic"
    },
    "studyRegion": "africa",
    "flagCode": "mz",
    "capitals": [
      {
        "es": "Maputo",
        "en": "Maputo",
        "ca": "Maputo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mm",
    "iso2": "MM",
    "iso3": "MMR",
    "names": {
      "es": "Myanmar",
      "en": "Myanmar",
      "ca": "Myanmar"
    },
    "studyRegion": "asia",
    "flagCode": "mm",
    "capitals": [
      {
        "es": "Naypyidaw",
        "en": "Naypyidaw",
        "ca": "Naypyidaw"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "na",
    "iso2": "NA",
    "iso3": "NAM",
    "names": {
      "es": "Namibia",
      "en": "Namibia",
      "ca": "Namíbia"
    },
    "studyRegion": "africa",
    "flagCode": "na",
    "capitals": [
      {
        "es": "Windhoek",
        "en": "Windhoek",
        "ca": "Windhoek"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "nr",
    "iso2": "NR",
    "iso3": "NRU",
    "names": {
      "es": "Nauru",
      "en": "Nauru",
      "ca": "Nauru"
    },
    "studyRegion": "oceania",
    "flagCode": "nr",
    "capitals": [
      {
        "es": "Yaren",
        "en": "Yaren",
        "ca": "Yaren"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "np",
    "iso2": "NP",
    "iso3": "NPL",
    "names": {
      "es": "Nepal",
      "en": "Nepal",
      "ca": "Nepal"
    },
    "studyRegion": "asia",
    "flagCode": "np",
    "capitals": [
      {
        "es": "Kathmandu",
        "en": "Kathmandu",
        "ca": "Kathmandu"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "nl",
    "iso2": "NL",
    "iso3": "NLD",
    "names": {
      "es": "Países Bajos",
      "en": "Netherlands",
      "ca": "Països Baixos"
    },
    "studyRegion": "europe",
    "flagCode": "nl",
    "capitals": [
      {
        "es": "Amsterdam",
        "en": "Amsterdam",
        "ca": "Amsterdam"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "nz",
    "iso2": "NZ",
    "iso3": "NZL",
    "names": {
      "es": "Nueva Zelanda",
      "en": "New Zealand",
      "ca": "Nova Zelanda"
    },
    "studyRegion": "oceania",
    "flagCode": "nz",
    "capitals": [
      {
        "es": "Wellington",
        "en": "Wellington",
        "ca": "Wellington"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ni",
    "iso2": "NI",
    "iso3": "NIC",
    "names": {
      "es": "Nicaragua",
      "en": "Nicaragua",
      "ca": "Nicaragua"
    },
    "studyRegion": "north-america",
    "flagCode": "ni",
    "capitals": [
      {
        "es": "Managua",
        "en": "Managua",
        "ca": "Managua"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ne",
    "iso2": "NE",
    "iso3": "NER",
    "names": {
      "es": "Níger",
      "en": "Niger",
      "ca": "Níger"
    },
    "studyRegion": "africa",
    "flagCode": "ne",
    "capitals": [
      {
        "es": "Niamey",
        "en": "Niamey",
        "ca": "Niamey"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ng",
    "iso2": "NG",
    "iso3": "NGA",
    "names": {
      "es": "Nigeria",
      "en": "Nigeria",
      "ca": "Nigèria"
    },
    "studyRegion": "africa",
    "flagCode": "ng",
    "capitals": [
      {
        "es": "Abuya",
        "en": "Abuja",
        "ca": "Abuja"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kp",
    "iso2": "KP",
    "iso3": "PRK",
    "names": {
      "es": "República Popular Democrática de Corea",
      "en": "North Korea",
      "ca": "Corea del Nord"
    },
    "studyRegion": "asia",
    "flagCode": "kp",
    "capitals": [
      {
        "es": "Pyongyang",
        "en": "Pyongyang",
        "ca": "Pyongyang"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "no",
    "iso2": "NO",
    "iso3": "NOR",
    "names": {
      "es": "Noruega",
      "en": "Norway",
      "ca": "Noruega"
    },
    "studyRegion": "europe",
    "flagCode": "no",
    "capitals": [
      {
        "es": "Oslo",
        "en": "Oslo",
        "ca": "Oslo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "om",
    "iso2": "OM",
    "iso3": "OMN",
    "names": {
      "es": "Omán",
      "en": "Oman",
      "ca": "Oman"
    },
    "studyRegion": "asia",
    "flagCode": "om",
    "capitals": [
      {
        "es": "Muscat",
        "en": "Muscat",
        "ca": "Muscat"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pk",
    "iso2": "PK",
    "iso3": "PAK",
    "names": {
      "es": "Pakistán",
      "en": "Pakistan",
      "ca": "Pakistan"
    },
    "studyRegion": "asia",
    "flagCode": "pk",
    "capitals": [
      {
        "es": "Islamabad",
        "en": "Islamabad",
        "ca": "Islamabad"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pw",
    "iso2": "PW",
    "iso3": "PLW",
    "names": {
      "es": "Palau",
      "en": "Palau",
      "ca": "Palau"
    },
    "studyRegion": "oceania",
    "flagCode": "pw",
    "capitals": [
      {
        "es": "Ngerulmud",
        "en": "Ngerulmud",
        "ca": "Ngerulmud"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pa",
    "iso2": "PA",
    "iso3": "PAN",
    "names": {
      "es": "Panamá",
      "en": "Panama",
      "ca": "Panamà"
    },
    "studyRegion": "north-america",
    "flagCode": "pa",
    "capitals": [
      {
        "es": "Ciudad de Panamá",
        "en": "Panama City",
        "ca": "Ciutat de Panamà"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pg",
    "iso2": "PG",
    "iso3": "PNG",
    "names": {
      "es": "Papua Nueva Guinea",
      "en": "Papua New Guinea",
      "ca": "Papua Nova Guinea"
    },
    "studyRegion": "oceania",
    "flagCode": "pg",
    "capitals": [
      {
        "es": "Puerto Moresby",
        "en": "Port Moresby",
        "ca": "Port Moresby"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "py",
    "iso2": "PY",
    "iso3": "PRY",
    "names": {
      "es": "Paraguay",
      "en": "Paraguay",
      "ca": "Paraguai"
    },
    "studyRegion": "south-america",
    "flagCode": "py",
    "capitals": [
      {
        "es": "Asunción",
        "en": "Asunción",
        "ca": "Asunción"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cn",
    "iso2": "CN",
    "iso3": "CHN",
    "names": {
      "es": "China",
      "en": "People's Republic of China",
      "ca": "Xina"
    },
    "studyRegion": "asia",
    "flagCode": "cn",
    "capitals": [
      {
        "es": "Pekín",
        "en": "Beijing",
        "ca": "Pequín"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pe",
    "iso2": "PE",
    "iso3": "PER",
    "names": {
      "es": "Perú",
      "en": "Peru",
      "ca": "Perú"
    },
    "studyRegion": "south-america",
    "flagCode": "pe",
    "capitals": [
      {
        "es": "Lima",
        "en": "Lima",
        "ca": "Lima"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ph",
    "iso2": "PH",
    "iso3": "PHL",
    "names": {
      "es": "Filipinas",
      "en": "Philippines",
      "ca": "Filipines"
    },
    "studyRegion": "asia",
    "flagCode": "ph",
    "capitals": [
      {
        "es": "Manila",
        "en": "Manila",
        "ca": "Manila"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pl",
    "iso2": "PL",
    "iso3": "POL",
    "names": {
      "es": "Polonia",
      "en": "Poland",
      "ca": "Polònia"
    },
    "studyRegion": "europe",
    "flagCode": "pl",
    "capitals": [
      {
        "es": "Varsovia",
        "en": "Warsaw",
        "ca": "Varsòvia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "pt",
    "iso2": "PT",
    "iso3": "PRT",
    "names": {
      "es": "Portugal",
      "en": "Portugal",
      "ca": "Portugal"
    },
    "studyRegion": "europe",
    "flagCode": "pt",
    "capitals": [
      {
        "es": "Lisboa",
        "en": "Lisbon",
        "ca": "Lisboa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "qa",
    "iso2": "QA",
    "iso3": "QAT",
    "names": {
      "es": "Catar",
      "en": "Qatar",
      "ca": "Qatar"
    },
    "studyRegion": "asia",
    "flagCode": "qa",
    "capitals": [
      {
        "es": "Doha",
        "en": "Doha",
        "ca": "Doha"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "cg",
    "iso2": "CG",
    "iso3": "COG",
    "names": {
      "es": "Congo",
      "en": "Republic of the Congo",
      "ca": "Congo, República del"
    },
    "studyRegion": "africa",
    "flagCode": "cg",
    "capitals": [
      {
        "es": "Brazzaville",
        "en": "Brazzaville",
        "ca": "Brazzaville"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gm",
    "iso2": "GM",
    "iso3": "GMB",
    "names": {
      "es": "Gambia",
      "en": "Republic of The Gambia",
      "ca": "Gàmbia"
    },
    "studyRegion": "africa",
    "flagCode": "gm",
    "capitals": [
      {
        "es": "Banjul",
        "en": "Banjul",
        "ca": "Banjul"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ro",
    "iso2": "RO",
    "iso3": "ROU",
    "names": {
      "es": "Rumanía",
      "en": "Romania",
      "ca": "Romania"
    },
    "studyRegion": "europe",
    "flagCode": "ro",
    "capitals": [
      {
        "es": "Bucarest",
        "en": "Bucharest",
        "ca": "Bucarest"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ru",
    "iso2": "RU",
    "iso3": "RUS",
    "names": {
      "es": "Rusia",
      "en": "Russian Federation",
      "ca": "Rússia"
    },
    "studyRegion": "europe",
    "flagCode": "ru",
    "capitals": [
      {
        "es": "Moscú",
        "en": "Moscow",
        "ca": "Moscou"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "rw",
    "iso2": "RW",
    "iso3": "RWA",
    "names": {
      "es": "Ruanda",
      "en": "Rwanda",
      "ca": "Ruanda"
    },
    "studyRegion": "africa",
    "flagCode": "rw",
    "capitals": [
      {
        "es": "Kigali",
        "en": "Kigali",
        "ca": "Kigali"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "kn",
    "iso2": "KN",
    "iso3": "KNA",
    "names": {
      "es": "Saint Kitts y Nevis",
      "en": "Saint Kitts and Nevis",
      "ca": "Saint Kitts i Nevis"
    },
    "studyRegion": "north-america",
    "flagCode": "kn",
    "capitals": [
      {
        "es": "Basseterre",
        "en": "Basseterre",
        "ca": "Basseterre"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lc",
    "iso2": "LC",
    "iso3": "LCA",
    "names": {
      "es": "Santa Lucía",
      "en": "Saint Lucia",
      "ca": "Saint Lucia"
    },
    "studyRegion": "north-america",
    "flagCode": "lc",
    "capitals": [
      {
        "es": "Castries",
        "en": "Castries",
        "ca": "Castries"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "vc",
    "iso2": "VC",
    "iso3": "VCT",
    "names": {
      "es": "San Vicente y las Granadinas",
      "en": "Saint Vincent and the Grenadines",
      "ca": "Saint Vincent i les Grenadines"
    },
    "studyRegion": "north-america",
    "flagCode": "vc",
    "capitals": [
      {
        "es": "Kingstown",
        "en": "Kingstown",
        "ca": "Kingstown"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ws",
    "iso2": "WS",
    "iso3": "WSM",
    "names": {
      "es": "Samoa",
      "en": "Samoa",
      "ca": "Samoa"
    },
    "studyRegion": "oceania",
    "flagCode": "ws",
    "capitals": [
      {
        "es": "Apia",
        "en": "Apia",
        "ca": "Apia"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sm",
    "iso2": "SM",
    "iso3": "SMR",
    "names": {
      "es": "San Marino",
      "en": "San Marino",
      "ca": "San Marino"
    },
    "studyRegion": "europe",
    "flagCode": "sm",
    "capitals": [
      {
        "es": "City of San Marino",
        "en": "City of San Marino",
        "ca": "City of San Marino"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "st",
    "iso2": "ST",
    "iso3": "STP",
    "names": {
      "es": "Santo Tomé y Príncipe",
      "en": "Sao Tome and Principe",
      "ca": "São Tomé i Príncipe"
    },
    "studyRegion": "africa",
    "flagCode": "st",
    "capitals": [
      {
        "es": "São Tomé",
        "en": "São Tomé",
        "ca": "São Tomé"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sa",
    "iso2": "SA",
    "iso3": "SAU",
    "names": {
      "es": "Arabia Saudita",
      "en": "Saudi Arabia",
      "ca": "Aràbia Saudita"
    },
    "studyRegion": "asia",
    "flagCode": "sa",
    "capitals": [
      {
        "es": "Riad",
        "en": "Riyadh",
        "ca": "Riad"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sn",
    "iso2": "SN",
    "iso3": "SEN",
    "names": {
      "es": "Senegal",
      "en": "Senegal",
      "ca": "Senegal"
    },
    "studyRegion": "africa",
    "flagCode": "sn",
    "capitals": [
      {
        "es": "Dakar",
        "en": "Dakar",
        "ca": "Dakar"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "rs",
    "iso2": "RS",
    "iso3": "SRB",
    "names": {
      "es": "Serbia",
      "en": "Serbia",
      "ca": "Sèrbia"
    },
    "studyRegion": "europe",
    "flagCode": "rs",
    "capitals": [
      {
        "es": "Belgrado",
        "en": "Belgrade",
        "ca": "Belgrad"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sc",
    "iso2": "SC",
    "iso3": "SYC",
    "names": {
      "es": "Seychelles",
      "en": "Seychelles",
      "ca": "Seychelles"
    },
    "studyRegion": "africa",
    "flagCode": "sc",
    "capitals": [
      {
        "es": "Victoria",
        "en": "Victoria",
        "ca": "Victoria"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sl",
    "iso2": "SL",
    "iso3": "SLE",
    "names": {
      "es": "Sierra Leona",
      "en": "Sierra Leone",
      "ca": "Sierra Leone"
    },
    "studyRegion": "africa",
    "flagCode": "sl",
    "capitals": [
      {
        "es": "Freetown",
        "en": "Freetown",
        "ca": "Freetown"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sg",
    "iso2": "SG",
    "iso3": "SGP",
    "names": {
      "es": "Singapur",
      "en": "Singapore",
      "ca": "Singapur"
    },
    "studyRegion": "asia",
    "flagCode": "sg",
    "capitals": [
      {
        "es": "Singapur",
        "en": "Singapore",
        "ca": "Singapur"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sk",
    "iso2": "SK",
    "iso3": "SVK",
    "names": {
      "es": "Eslovaquia",
      "en": "Slovakia",
      "ca": "Eslovàquia"
    },
    "studyRegion": "europe",
    "flagCode": "sk",
    "capitals": [
      {
        "es": "Bratislava",
        "en": "Bratislava",
        "ca": "Bratislava"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "si",
    "iso2": "SI",
    "iso3": "SVN",
    "names": {
      "es": "Eslovenia",
      "en": "Slovenia",
      "ca": "Eslovènia"
    },
    "studyRegion": "europe",
    "flagCode": "si",
    "capitals": [
      {
        "es": "Liubliana",
        "en": "Ljubljana",
        "ca": "Ljubljana"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sb",
    "iso2": "SB",
    "iso3": "SLB",
    "names": {
      "es": "Islas Salomón",
      "en": "Solomon Islands",
      "ca": "Salomó"
    },
    "studyRegion": "oceania",
    "flagCode": "sb",
    "capitals": [
      {
        "es": "Honiara",
        "en": "Honiara",
        "ca": "Honiara"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "so",
    "iso2": "SO",
    "iso3": "SOM",
    "names": {
      "es": "Somalia",
      "en": "Somalia",
      "ca": "Somàlia"
    },
    "studyRegion": "africa",
    "flagCode": "so",
    "capitals": [
      {
        "es": "Mogadishu",
        "en": "Mogadishu",
        "ca": "Mogadishu"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "za",
    "iso2": "ZA",
    "iso3": "ZAF",
    "names": {
      "es": "Sudáfrica",
      "en": "South Africa",
      "ca": "Sud-àfrica"
    },
    "studyRegion": "africa",
    "flagCode": "za",
    "capitals": [
      {
        "es": "Pretoria",
        "en": "Pretoria",
        "ca": "Pretòria"
      },
      {
        "es": "Bloemfontein",
        "en": "Bloemfontein",
        "ca": "Bloemfontein"
      },
      {
        "es": "Cape Town",
        "en": "Cape Town",
        "ca": "Cape Town"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "kr",
    "iso2": "KR",
    "iso3": "KOR",
    "names": {
      "es": "República de Corea",
      "en": "South Korea",
      "ca": "Corea del Sud"
    },
    "studyRegion": "asia",
    "flagCode": "kr",
    "capitals": [
      {
        "es": "Seúl",
        "en": "Seoul",
        "ca": "Seül"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ss",
    "iso2": "SS",
    "iso3": "SSD",
    "names": {
      "es": "Sudán del Sur",
      "en": "South Sudan",
      "ca": "Sudan del Sud"
    },
    "studyRegion": "africa",
    "flagCode": "ss",
    "capitals": [
      {
        "es": "Juba",
        "en": "Juba",
        "ca": "Juba"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "es",
    "iso2": "ES",
    "iso3": "ESP",
    "names": {
      "es": "España",
      "en": "Spain",
      "ca": "Espanya"
    },
    "studyRegion": "europe",
    "flagCode": "es",
    "capitals": [
      {
        "es": "Madrid",
        "en": "Madrid",
        "ca": "Madrid"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "lk",
    "iso2": "LK",
    "iso3": "LKA",
    "names": {
      "es": "Sri Lanka",
      "en": "Sri Lanka",
      "ca": "Sri Lanka"
    },
    "studyRegion": "asia",
    "flagCode": "lk",
    "capitals": [
      {
        "es": "Colombo",
        "en": "Colombo",
        "ca": "Colombo"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "ps",
    "iso2": "PS",
    "iso3": "PSE",
    "names": {
      "es": "Palestina",
      "en": "State of Palestine",
      "ca": "Palestina"
    },
    "studyRegion": "asia",
    "flagCode": "ps",
    "capitals": [
      {
        "es": "Ramallah",
        "en": "Ramallah",
        "ca": "Ramallah"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "sd",
    "iso2": "SD",
    "iso3": "SDN",
    "names": {
      "es": "Sudán",
      "en": "Sudan",
      "ca": "Sudan"
    },
    "studyRegion": "africa",
    "flagCode": "sd",
    "capitals": [
      {
        "es": "Jartum",
        "en": "Khartoum",
        "ca": "Khartum"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sr",
    "iso2": "SR",
    "iso3": "SUR",
    "names": {
      "es": "Suriname",
      "en": "Suriname",
      "ca": "Surinam"
    },
    "studyRegion": "south-america",
    "flagCode": "sr",
    "capitals": [
      {
        "es": "Paramaribo",
        "en": "Paramaribo",
        "ca": "Paramaribo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "se",
    "iso2": "SE",
    "iso3": "SWE",
    "names": {
      "es": "Suecia",
      "en": "Sweden",
      "ca": "Suècia"
    },
    "studyRegion": "europe",
    "flagCode": "se",
    "capitals": [
      {
        "es": "Estocolmo",
        "en": "Stockholm",
        "ca": "Estocolm"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ch",
    "iso2": "CH",
    "iso3": "CHE",
    "names": {
      "es": "Suiza",
      "en": "Switzerland",
      "ca": "Suïssa"
    },
    "studyRegion": "europe",
    "flagCode": "ch",
    "capitals": [
      {
        "es": "Berna",
        "en": "Bern",
        "ca": "Berna"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "sy",
    "iso2": "SY",
    "iso3": "SYR",
    "names": {
      "es": "República Árabe Siria",
      "en": "Syrian Arab Republic",
      "ca": "Síria"
    },
    "studyRegion": "asia",
    "flagCode": "sy",
    "capitals": [
      {
        "es": "Damasco",
        "en": "Damascus",
        "ca": "Damasc"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tj",
    "iso2": "TJ",
    "iso3": "TJK",
    "names": {
      "es": "Tayikistán",
      "en": "Tajikistan",
      "ca": "Tadjikistan"
    },
    "studyRegion": "asia",
    "flagCode": "tj",
    "capitals": [
      {
        "es": "Dushanbe",
        "en": "Dushanbe",
        "ca": "Dushanbe"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "th",
    "iso2": "TH",
    "iso3": "THA",
    "names": {
      "es": "Tailandia",
      "en": "Thailand",
      "ca": "Tailàndia"
    },
    "studyRegion": "asia",
    "flagCode": "th",
    "capitals": [
      {
        "es": "Bangkok",
        "en": "Bangkok",
        "ca": "Bangkok"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "mk",
    "iso2": "MK",
    "iso3": "MKD",
    "names": {
      "es": "Macedonia del Norte",
      "en": "The Republic of North Macedonia",
      "ca": "Macedònia del Nord"
    },
    "studyRegion": "europe",
    "flagCode": "mk",
    "capitals": [
      {
        "es": "Skopje",
        "en": "Skopje",
        "ca": "Skopje"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tl",
    "iso2": "TL",
    "iso3": "TLS",
    "names": {
      "es": "Timor-Leste",
      "en": "Timor-Leste",
      "ca": "Timor Oriental"
    },
    "studyRegion": "asia",
    "flagCode": "tl",
    "capitals": [
      {
        "es": "Dili",
        "en": "Dili",
        "ca": "Dili"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tg",
    "iso2": "TG",
    "iso3": "TGO",
    "names": {
      "es": "Togo",
      "en": "Togo",
      "ca": "Togo"
    },
    "studyRegion": "africa",
    "flagCode": "tg",
    "capitals": [
      {
        "es": "Lomé",
        "en": "Lomé",
        "ca": "Lomé"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "to",
    "iso2": "TO",
    "iso3": "TON",
    "names": {
      "es": "Tonga",
      "en": "Tonga",
      "ca": "Tonga"
    },
    "studyRegion": "oceania",
    "flagCode": "to",
    "capitals": [
      {
        "es": "Nuku'alofa",
        "en": "Nuku'alofa",
        "ca": "Nuku'alofa"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tt",
    "iso2": "TT",
    "iso3": "TTO",
    "names": {
      "es": "Trinidad y Tobago",
      "en": "Trinidad and Tobago",
      "ca": "Trinitat i Tobago"
    },
    "studyRegion": "north-america",
    "flagCode": "tt",
    "capitals": [
      {
        "es": "Port of Spain",
        "en": "Port of Spain",
        "ca": "Port of Spain"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tn",
    "iso2": "TN",
    "iso3": "TUN",
    "names": {
      "es": "Túnez",
      "en": "Tunisia",
      "ca": "Tunísia"
    },
    "studyRegion": "africa",
    "flagCode": "tn",
    "capitals": [
      {
        "es": "Túnez",
        "en": "Tunis",
        "ca": "Tunis"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tr",
    "iso2": "TR",
    "iso3": "TUR",
    "names": {
      "es": "Turquía",
      "en": "Türkiye",
      "ca": "Turquia"
    },
    "studyRegion": "asia",
    "flagCode": "tr",
    "capitals": [
      {
        "es": "Ankara",
        "en": "Ankara",
        "ca": "Ankara"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tm",
    "iso2": "TM",
    "iso3": "TKM",
    "names": {
      "es": "Turkmenistán",
      "en": "Turkmenistan",
      "ca": "Turkmenistan"
    },
    "studyRegion": "asia",
    "flagCode": "tm",
    "capitals": [
      {
        "es": "Ashgabat",
        "en": "Ashgabat",
        "ca": "Ashgabat"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tv",
    "iso2": "TV",
    "iso3": "TUV",
    "names": {
      "es": "Tuvalu",
      "en": "Tuvalu",
      "ca": "Tuvalu"
    },
    "studyRegion": "oceania",
    "flagCode": "tv",
    "capitals": [
      {
        "es": "Funafuti",
        "en": "Funafuti",
        "ca": "Funafuti"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ug",
    "iso2": "UG",
    "iso3": "UGA",
    "names": {
      "es": "Uganda",
      "en": "Uganda",
      "ca": "Uganda"
    },
    "studyRegion": "africa",
    "flagCode": "ug",
    "capitals": [
      {
        "es": "Kampala",
        "en": "Kampala",
        "ca": "Kampala"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ua",
    "iso2": "UA",
    "iso3": "UKR",
    "names": {
      "es": "Ucrania",
      "en": "Ukraine",
      "ca": "Ucraïna"
    },
    "studyRegion": "europe",
    "flagCode": "ua",
    "capitals": [
      {
        "es": "Kyiv",
        "en": "Kyiv",
        "ca": "Kyiv"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ae",
    "iso2": "AE",
    "iso3": "ARE",
    "names": {
      "es": "Emiratos Árabes Unidos",
      "en": "United Arab Emirates",
      "ca": "Emirats Àrabs Units"
    },
    "studyRegion": "asia",
    "flagCode": "ae",
    "capitals": [
      {
        "es": "Abu Dhabi",
        "en": "Abu Dhabi",
        "ca": "Abu Dhabi"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "gb",
    "iso2": "GB",
    "iso3": "GBR",
    "names": {
      "es": "Reino Unido",
      "en": "United Kingdom",
      "ca": "Regne Unit"
    },
    "studyRegion": "europe",
    "flagCode": "gb",
    "capitals": [
      {
        "es": "Londres",
        "en": "London",
        "ca": "Londres"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "tz",
    "iso2": "TZ",
    "iso3": "TZA",
    "names": {
      "es": "Tanzania",
      "en": "United Republic of Tanzania",
      "ca": "Tanzània"
    },
    "studyRegion": "africa",
    "flagCode": "tz",
    "capitals": [
      {
        "es": "Dodoma",
        "en": "Dodoma",
        "ca": "Dodoma"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "us",
    "iso2": "US",
    "iso3": "USA",
    "names": {
      "es": "Estados Unidos",
      "en": "United States of America",
      "ca": "Estats Units (EUA)"
    },
    "studyRegion": "north-america",
    "flagCode": "us",
    "capitals": [
      {
        "es": "Washington D.C.",
        "en": "Washington D.C.",
        "ca": "Washington D.C."
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "uy",
    "iso2": "UY",
    "iso3": "URY",
    "names": {
      "es": "Uruguay",
      "en": "Uruguay",
      "ca": "Uruguai"
    },
    "studyRegion": "south-america",
    "flagCode": "uy",
    "capitals": [
      {
        "es": "Montevideo",
        "en": "Montevideo",
        "ca": "Montevideo"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "uz",
    "iso2": "UZ",
    "iso3": "UZB",
    "names": {
      "es": "Uzbekistán",
      "en": "Uzbekistan",
      "ca": "Uzbekistan"
    },
    "studyRegion": "asia",
    "flagCode": "uz",
    "capitals": [
      {
        "es": "Tashkent",
        "en": "Tashkent",
        "ca": "Tashkent"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "vu",
    "iso2": "VU",
    "iso3": "VUT",
    "names": {
      "es": "Vanuatu",
      "en": "Vanuatu",
      "ca": "Vanuatu"
    },
    "studyRegion": "oceania",
    "flagCode": "vu",
    "capitals": [
      {
        "es": "Port Vila",
        "en": "Port Vila",
        "ca": "Port Vila"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ve",
    "iso2": "VE",
    "iso3": "VEN",
    "names": {
      "es": "Venezuela",
      "en": "Venezuela",
      "ca": "Veneçuela"
    },
    "studyRegion": "south-america",
    "flagCode": "ve",
    "capitals": [
      {
        "es": "Caracas",
        "en": "Caracas",
        "ca": "Caracas"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "vn",
    "iso2": "VN",
    "iso3": "VNM",
    "names": {
      "es": "Vietnam",
      "en": "Vietnam",
      "ca": "Vietnam"
    },
    "studyRegion": "asia",
    "flagCode": "vn",
    "capitals": [
      {
        "es": "Hanói",
        "en": "Hanoi",
        "ca": "Hanoi"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "ye",
    "iso2": "YE",
    "iso3": "YEM",
    "names": {
      "es": "Yemen",
      "en": "Yemen",
      "ca": "Iemen"
    },
    "studyRegion": "asia",
    "flagCode": "ye",
    "capitals": [
      {
        "es": "Sana'a",
        "en": "Sana'a",
        "ca": "Sana'a"
      }
    ],
    "capitalQuizEnabled": false,
    "enabled": true
  },
  {
    "id": "zm",
    "iso2": "ZM",
    "iso3": "ZMB",
    "names": {
      "es": "Zambia",
      "en": "Zambia",
      "ca": "Zàmbia"
    },
    "studyRegion": "africa",
    "flagCode": "zm",
    "capitals": [
      {
        "es": "Lusaka",
        "en": "Lusaka",
        "ca": "Lusaka"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  },
  {
    "id": "zw",
    "iso2": "ZW",
    "iso3": "ZWE",
    "names": {
      "es": "Zimbabue",
      "en": "Zimbabwe",
      "ca": "Zimbabwe"
    },
    "studyRegion": "africa",
    "flagCode": "zw",
    "capitals": [
      {
        "es": "Harare",
        "en": "Harare",
        "ca": "Harare"
      }
    ],
    "capitalQuizEnabled": true,
    "enabled": true
  }
];
