/* Generated by scripts/generate-japanese-1500.mjs. Do not edit manually. */
export const JAPANESE_1500_METADATA = {
  "id": "japanese-1500",
  "nameKey": "anki.deck.japanese1500.name",
  "cardCount": 1500,
  "contentType": "japanese-word"
} as const;
